### ISSUE TITLE
Unable to use gganimate

### ISSUE THREAD

**Issue by pavanthanuj** [thomasp85/gganimate#100]
![image](https://user-images.githubusercontent.com/41346246/42843515-8b17bfd4-89cd-11e8-8de7-f6907207bcbb.png)

I tried installing gganimate()package . But it give me the following error "Error: package or namespace load failed for ‘gganimate’:
 object ‘.complete_states’ is not exported by 'namespace:tweenr".

Additional I tried downloading through numerous other ways insisted in google( installing dev ops ,etc).
But I could not get gganimate going. I am interested in plotting animated packages.

**Comment by DavisVaughan** [comment]
Possibly you have an old version of `tweenr`? `gganimate` seems to currently use the development version of `tweenr`. Try:

```r
devtools::install_github("thomasp85/tweenr")
devtools::install_github("thomasp85/gganimate")
```

Then restart R and try again.
