### ISSUE TITLE
gganimate fails with `geom_contour()`

### ISSUE THREAD

**Issue by eliocamp** [thomasp85/gganimate#101]
Animations seems to fail with `geom_contour()`. Here's a reprex:

``` r
library(ggplot2)
library(gganimate)

v <- reshape2::melt(volcano)
v <- rbind(transform(v, time = 1), transform(v, time = 2))
```

Here’s the two states

``` r
ggplot(v, aes(Var1, Var2)) +
  geom_contour(aes(z = value)) +
  facet_wrap(~time) 
```

![](https://i.imgur.com/uzOuwON.png)

Using `transition_states()` gives an error

``` r
ggplot(v, aes(Var1, Var2)) +
  geom_contour(aes(z = value)) +
  transition_states(time, 
                    transition_length = 1,
                    state_length = 1)
#> Warning in (function (d, t, en, ex, es) : NAs introduced by coercion
#> Error in `$<-.data.frame`(`*tmp*`, ".phase", value = "raw"): replacement has 1 row, data has 0
```

And using `transition_time()` gives a *different* error.

``` r
ggplot(v, aes(Var1, Var2)) +
  geom_contour(aes(z = value)) +
  transition_time(time)
#> Warning in (function (d, t, en, ex, es) : NAs introduced by coercion
#> Error in if (times[1] <= 1) {: missing value where TRUE/FALSE needed
```

Finally `transition_manual()` doesn’t give an error, but the output is blank

``` r
ggplot(v, aes(Var1, Var2)) +
  geom_contour(aes(z = value)) +
  transition_manual(time) +
  labs(title = "{current_frame}")
#> Warning in split.default(x = seq_len(nrow(x)), f = f, drop = drop, ...):
#> NAs introduced by coercion
#> nframes adjusted to match plot
```

![](https://i.imgur.com/Z2cbUW1.gif)

Created on 2018-07-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Using `geom_tile()` does work. 

My apologies if this is an error on my part --I'm just now testing this new API-- and congratulations on your work with `gganimate`. It's awesome!

**Comment by ginolhac** [comment]
I think this is because `geom_contour()` does the binning and conversion to density_2d and `gganimate` needs direct coordinates to tween between. So for `geom_tile` it's works well.

But, using `geom_contour()` and then `ggplot_build()` we can fetch the actual lines after this conversion to density_2d.

Here is the code, note that I added noise between the 2 fake time points. In your example, it was identical values.

``` r
library(tidyverse)
library(gganimate)

# get a smaller example
reshape2::melt(volcano) %>%
  as_tibble() %>%
  filter(Var1 < 20, Var2 < 20) -> volc

# add noise and time points
bind_rows(mutate(volc, time = 1L),
          mutate(volc, time = 2L,
                 value = value + rnorm(nrow(volc), mean = 20))) -> volc2
# create plot to get the density_2d computed
volc2 %>% 
  ggplot(aes(x = Var1, y = Var2)) + 
  geom_contour(aes(z = value)) +
  facet_wrap(~ time) -> p

p

# extract the data after conversion

p_build <- ggplot_build(p)

# check if we get the right plot after stat_contour
p_build$data[[1]] %>%
  ggplot(aes(x, y, group = piece)) +
  geom_point() +
  geom_path() +
  facet_wrap(~ PANEL)
```

![](https://i.imgur.com/D5wL40u.png)

fine, now we do the animation

``` r

p_build$data[[1]] %>%
  mutate(time = as.integer(PANEL)) %>%
  ggplot(aes(x, y, group = group)) +
  geom_path() +
  transition_time(time) +
  labs(title = "{frame_time}") -> va
animate(va, nframes = 50)
```

![](https://i.imgur.com/UTipnsQ.gif)

Created on 2018-07-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
Yeah, geom_contour is one of those odd ones that I’ll need to look into a bit more to provide a better approach. While @ginolhac approach works somewhat it should not be necessary in the long run

**Comment by thomasp85** [comment]
This led me down a path :-)

But should be fixed now

```r
volc2 %>% 
  ggplot(aes(x = Var1, y = Var2)) + 
  geom_contour(aes(z = value)) + 
  transition_time(time)
```

![contour](https://user-images.githubusercontent.com/1775316/43192303-7e0adf3e-8ffd-11e8-833f-326f6463b699.gif)

This is still not the best approach for this sort of thing as it doesn't truthfully represent the change in contour. Better would be to tween the underlying data/calculated distribution, but I don't see a clear route for this yet...
