### ISSUE TITLE
labs(title = 'Month: {frame_time}

### ISSUE THREAD

**Issue by rbenel** [thomasp85/gganimate#103]
I am trying to animate a graph according to the month of the year which is as such (see below), and I would really like to apply to the label just the number which corresponds to the month; however, in the actual plot I see 1.1111, 1.222... 9.3333,9.4444. Even better I would like to show the actual name of the month, but I looked at the `transition_time` function and it only takes an int, numeric, or full date.. 
` df$month
 [1]  1  1  1  1  2  2  2  2  3  3  3  3  4  4  4  4  5  5  5  5  6  6  6  6  7  7  7  7  8  8  8
[32]  8  9  9  9  9 10 10 10 10 11 11 11 11 12 12 12 12`

Is it possible to just see 1,2,3...?
Thank!

**Comment by ginolhac** [comment]
you can give a try to `transition_states(month, transition_length = 1, state_length = 1)` 

and use `labs(title = 'Month: {closest_state}')`

**Comment by thomasp85** [comment]
Yeah, transition_time works on a continuous time scale and will give you the actual time for the frames which might not be a whole number. If you want to use transition time I’d advice you to incode your months as a Date and then use the formatting available for that to just show the month

**Comment by rbenel** [comment]
@ginolhac 
I tried your suggestion, but without too much success... 

Error in transition_time(month, transition_length = 1, state_length = 1) : 
  unused arguments (transition_length = 1, state_length = 1) 
and when I remove `(transition_length = 1, state_length = 1)`, I receive
Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 'closest_state' not found

@thomasp85 the problem with the actual date, is that I am representing average monthly values, so I only have a range of values. If I insert the actual date for a day at random it is misleading, and one might think that it represents that actual day...

**Comment by ginolhac** [comment]
@rbenel you need `transition_states()`  not `time` to test closest_state

**Comment by rbenel** [comment]
@ginolhac - of course, and it worked! 
Thank you so much!
