### ISSUE TITLE
transition_time() throws error using geom_polygon()

### ISSUE THREAD

**Issue by motman440** [thomasp85/gganimate#104]
I've been trying to generate a map. The below is a representation, throwing the same error.
`transition_manual()` works

Code:
```
x <- rep(c(1,2,3,4,5,6,5,4,3,2,1,1,1,1,1,1), 20)
y <- rep(c(1,2,3,4,5,6,6,6,6,6,6,5,4,3,2,1), 20)
value <- rep(sample(1:20,20), each = 16)
year <- rep(c(1990:2009), each = 16)
dat <- data_frame(x,y,value, group = 1, year)
ggplot(data = dat, aes(x= x, y= y, group = group, fill = value)) + 
           geom_polygon() +
           transition_time(year)
```

Error:
`Error: $ operator is invalid for atomic vectors`

Edit: Formatting

**Comment by raheem03** [comment]
I have a similar issue, also while generating a map. It appears both` transition_time()` and `transition_states()` throw this error (`transition_manual()` seems to be fine).

**Comment by thomasp85** [comment]
This was a bug in transformr that has been fixed now - please reinstall transformr from GitHub to fix
