### ISSUE TITLE
Appveyor build

### ISSUE THREAD

**Issue by maelle** [thomasp85/gganimate#107]
For the Windows users who need artifacts to easily install the dev version 🙂 :pray: 

When ropensci had 20 or so broken webhooks (😣) I got this advice from Appveyor

"If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account."

Or, if history isn't important, re-create the Appveyor project

**Comment by thomasp85** [comment]
Should be fixed now

**Comment by maelle** [comment]
Fantastic thanks a ton!

https://ci.appveyor.com/project/thomasp85/gganimate/build/1.0.15/artifacts 💎
