### ISSUE TITLE
Object 'viewer' not found since implementation of ffmpeg renderer

### ISSUE THREAD

**Issue by gregrs-uk** [thomasp85/gganimate#108]
When running your README example:

```r
library(ggplot2)
library(gganimate)

ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot() + 
  # Here comes the gganimate code
  transition_states(
    gear,
    transition_length = 2,
    state_length = 1
  ) +
  enter_fade() + 
  exit_shrink() +
  ease_aes('sine-in-out')
```

I get the following error:

```
Frame 99 (100%)
Finalizing encoding... done!
Error in print.gif_image(anim, info = FALSE) : object 'viewer' not found
```

If I install the commit before the ffmpeg renderer was implemented using `devtools::install_github('thomasp85/gganimate', ref='55edfa2126af8cc58db78c2ff4d1f1ca94b4fd94')`, it works fine and displays the gif in the RStudio viewer.

macOS 10.12.6
R 3.5.0
RStudio 1.1.423

**Comment by thomasp85** [comment]
Blunder on my part - should be fixed now

**Comment by gregrs-uk** [comment]
No problem. Thanks very much. Works nicely now.
