### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by superzucca** [thomasp85/gganimate#11]
Hello! I am currently trying to install the gganimate package but seem unable to.
I am running Win 10, Rx64 3.3.0 and Rstudio 0.99.896;
the following command:
`devtools::install_github("dgrtwo/gganimate")`
will throw this error:

```
Downloading GitHub repo dgrtwo/gganimate@master
from URL https://api.github.com/repos/dgrtwo/gganimate/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)
```

So after a few hours of despair, I decided to try and install the package manually. I followed this link:
[http://stackoverflow.com/questions/14806705/manually-downloading-and-installing-packages-in-r?lq=1](url)

the following command:
`install.packages(pkgs = "C:/Users/Superzucca/Desktop/gganimate-master.zip", repos = NULL)`
results in:
`Installing package into ‘C:/Users/Superzucca/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)`
but then when I call:
`library("gganimate-master") #as suggsted by R itself!!` 
this error is thown:
`Error in library("gganimate-master") : 
  there is no package called ‘gganimate-master’`

please, help. I don't have any problems installing other pkgs and honestly don't know what else to try.
Thank you in advance,
Superzucca

**Comment by filipwastberg** [comment]
You can manually set the SSL Verifypeer through:
```
library(httr)
set_config(config(ssl_verifypeer = 0L))
```

Does it for me, read more here: [http://stackoverflow.com/a/24794044/5094439]

**Comment by everiste** [comment]
Several months after the original post here, I am also having big problems installing gganimate. I am using Windows 10 and R version 3.3.2. The error I get is different from the one discussed above. I've read and followed the instructions in the relevant SO posts. Here is the command I enter:

    library(devtools)
    library(RCurl)
    library(httr)
    set_config( config( ssl_verifypeer = 0L ) )
    devtools::install_github("RcppCore/Rcpp")
    devtools::install_github("dgrtwo/gganimate")

And here is the error I am getting:

    * installing *source* package 'gganimate' ...
    ** R
    ** tests
    ** preparing package for lazy loading
    Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
    there is no package called 'Rcpp'
    ERROR: lazy loading failed for package 'gganimate'
    * removing 'C:/.../R/win-library/3.3/gganimate'
    Error: Command failed (1)

**Comment by jshah710** [comment]
Try this : 
library(devtools)
install.packages("Rcpp")
install_github("dgrtwo/gganimate")

It worked for me.

**Comment by ravivissa** [comment]
Hello jshah710,
                         I tried what you tried but I was able to install only rcpp and the other two are not installed.

Any suggestions?

Below are the errors -
***********
library(devtools)
Error in library(devtools) : there is no package called ‘devtools’
***********
install_github("dgrtwo/gganimate")
Error in install_github("dgrtwo/gganimate") : 
  could not find function "install_github"
***********
Regards
Ravi Kiran V

**Comment by AshPrasad** [comment]
generating .png files but not output .gif ...
Error: C:\Program' is not recognized as an internal or external command,
operable program or batch file. when

**Comment by saiprp** [comment]
Try this. It's working for me.

    library(devtools)
    library(RCurl)
    library(httr)
    set_config( config( ssl_verifypeer = 0L ) )
    devtools::install_github("dgrtwo/gganimate")

**Comment by ahsan-iftikhar** [comment]
I am getting the following error. Can anybody help in installing gganimate.

* installing *source* package 'gganimate' ...
** R
** tests
** preparing package for lazy loading
** help
Warning: C:/Users/Ahsan Iftikhar/AppData/Local/Temp/Rtmp650zI5/devtoolsb107c1e5520/dgrtwo-gganimate-bf82002/man/gganimate_save.Rd:19: unexpected RCODE '[pkg=ggplot2]{ggsave', expecting '{'
Warning: C:/Users/Ahsan Iftikhar/AppData/Local/Temp/Rtmp650zI5/devtoolsb107c1e5520/dgrtwo-gganimate-bf82002/man/gganimate_save.Rd:20: unexpected RCODE '[pkg=animate]{saveVideo', expecting '{'
Warning: C:/Users/Ahsan Iftikhar/AppData/Local/Temp/Rtmp650zI5/devtoolsb107c1e5520/dgrtwo-gganimate-bf82002/man/gganimate_save.Rd:20: unexpected '}'
Warning: C:/Users/Ahsan Iftikhar/AppData/Local/Temp/Rtmp650zI5/devtoolsb107c1e5520/dgrtwo-gganimate-bf82002/man/gganimate_save.Rd:20: All text must be in a section
*** installing help indices
  converting help for package 'gganimate'
    finding HTML links ... done
    animation_saver                         html  
    auto_browse                             html  
    gganimate                               html  
    gganimate_save                          html  
    gganimate_tempfile                      html  
    plot_ggplot_build                       html  
    finding level-2 HTML links ... done

    print.gganimate                         html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Fatal error: cannot open file 'C:\Users\Ahsan': No such file or directory

*** arch - x64
Fatal error: cannot open file 'C:\Users\Ahsan': No such file or directory

ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Ahsan Iftikhar/Documents/R/win-library/3.4/gganimate'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by HMichaelPower** [comment]
Try again without the space in "C:/Users/Ahsan Iftikhar/“


On 5 Jan 2018, at 06:02, Ahsan Iftikhar Qureshi <notifications@github.com<mailto:notifications@github.com>> wrote:

C:/Users/Ahsan Iftikhar/

**Comment by rameshbalan** [comment]
I tried all the solutions mentioned above with no success. Here is my error
```
> library(Rcpp)
> devtools::install_github("dgrtwo/gganimate")
Downloading GitHub repo dgrtwo/gganimate@master
from URL https://api.github.com/repos/dgrtwo/gganimate/zipball/master
Installing gganimate
Installation failed: cannot open the connection
Warning messages:
1: In normalizePath(path) :
  path[1]="/tmp/work/Rcpp.tar.gz": No such file or directory
2: In read.dcf(path) :
  cannot open compressed file '/tmp/work/Rcpp.tar.gz/DESCRIPTION', probable reason 'No such file or directory'
```
Any help is much appreciated 😅

**Comment by stewartli** [comment]
above does not work for me too.

**Comment by pradeepdeep69** [comment]
Hope this works....
install.packages("devtools")
install.packages("Rcpp")
install.packages("httr")
library(devtools)
library(httr)
set_config(config(ssl_verifypeer = 0L))
devtools::install_github("dgrtwo/gganimate")

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
