### ISSUE TITLE
Row values changing to different rows during transition

### ISSUE THREAD

**Issue by brentthorne** [thomasp85/gganimate#110]
How can I ensure that the points mapped on this plot do not change between transition periods. I wanted to visually show each sample move to its next xy location based on the new state but when the animation occurs they just switch around to other sample ID's. It is hard to explain so I have included the gif output from my specific problem but will also try and make a reproducible version asap. I apologies for how rough this may be as it is in very early stages. 

You will notice that when transitioning the labels change to a different value even though they have a matching value in the upcoming state. 

![fileabc2047786e](https://user-images.githubusercontent.com/15312739/43269427-d684b518-90c0-11e8-89d9-451460c30c42.gif)

Thank you for this package by the way it looks great and I will post my reproducible version as soon as it is done.

Cheers.

**Comment by thomasp85** [comment]
Graphic elements are matched based on the group aesthetic so simply add a column identifying the points between states should work. If you don’t specify a group aesthetic elements are matched by row index

**Comment by brentthorne** [comment]
Thanks I realized that the grouping aesthetics I used were set within individual geom lines rather than at the beginning which seems to have solved the problem. Thanks!
