### ISSUE TITLE
FR: allow delay at start/end when using transition_time

### ISSUE THREAD

**Issue by gregrs-uk** [thomasp85/gganimate#111]
It would be useful to be able to add a delay at the start and end of the animation when using `transition_time`. This could potentially be specified using the `range` argument if values outside the range of the supplied data were allowed.

For example in the animation below (which could show some musical notes appearing in real time), perhaps you could set `range = c(0, 5.5)` to have a 1-unit delay at the start (before the point `time=1`) and a 1-unit delay at the end (after the point `time=4.5`).

```
library(gganimate)

data <- tibble::tibble(
  time = c(1, 2.5, 3, 4.5),
  x = c(1, 2.5, 3, 4.5)
)

p <- ggplot(data, aes(x, y = 1, group = time)) +
  geom_point(size = 10) +
  transition_time(time, range = c(1, 4.5)) +
  shadow_mark(colour = 'gray70', size = 5)
  
animate(p, nframes = 20)
```

![fr](https://user-images.githubusercontent.com/7353938/43334423-5aa39ada-91c5-11e8-8eaf-85ffbb495ae0.gif)

Currently if you try to set `range = c(0, 5.5)`, you receive the following error:

```
Error in `$<-.data.frame`(`*tmp*`, ".phase", value = "raw") : 
  replacement has 1 row, data has 0
```

Thanks.

**Comment by thomasp85** [comment]
This should be possible and thus, you have stumbled on a bug. Will fix

**Comment by gregrs-uk** [comment]
Great, thanks

**Comment by thomasp85** [comment]
Updating tweenr+transformr should fix this now

**Comment by gregrs-uk** [comment]
Thanks very much.
