### ISSUE TITLE
Wrapping / Pausing / Labeling in `transition_manual()`

### ISSUE THREAD

**Issue by calebasaraba** [thomasp85/gganimate#112]
Fantastic package -- I know it is under development, but does the grammar currently support wrapping / pausing / or labeling options across the different `transition_*` tools? 

I am using `transition_manual()` and am trying to animate without wrapping around and also adding an increased pause time between states. It does not seem like that is possible yet with `transition_manual()` , or is it?

It would also be great to label using my manual variable the way one can with `{frame_time}` for `transition_time()` or `{closest_state}` for `transition_states()`. Is there something similar for `transition_manual()`?

Thanks for the help, if these features are available I'd be willing to add examples of them in action to the README or help files.

**Comment by thomasp85** [comment]
For the first question, transition_manual doesn't have any distinct states. If you want to increase the time spend on each frame, set `fps` in `animate()`. If you don't want the animation to loop you can also set `loop = FALSE` in the renderer you use. In combination:

```r
animate(p, fps = 2, renderer = gifski_renderer(loop = FALSE))
```

For second question, I've now added the possibility of specifying additional frame information in transition_manual (the value of the `frame` variable was already accessible with `{current_frame}`)
