### ISSUE TITLE
geom_line vs geom_point warning and plot not rendering

### ISSUE THREAD

**Issue by scworland** [thomasp85/gganimate#113]
I am trying to make a simple plot where a line grows from the left to the right. This works fine with geom_point:

```r
df <- airquality %>%
  group_by(Day) %>%
  summarize(min_temp = min(Temp)) 

ggplot(df, aes(Day,min_temp)) +
  geom_point(color = 'red', size = 1) +
  transition_time(Day) +
  shadow_trail(trail_distance = 1)
```
but with geom_line,

```r
ggplot(df,aes(Day,min_temp, group=1)) +
  geom_line(color = 'red', size = 1) +
  transition_time(Day) +
  shadow_trail(trail_distance = 1)
```

I see the following error: `Each group consists of only one observation. Do you need to adjust the group aesthetic?
geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?` and the plot doesn't render properly (i.e., only plots the axes). This error is normally associated with a factor-plotting variable, and `group=1` in `aes()` takes care of it. It does not in this case. The plot issue may not even be related to the warning.

Issue #97 has an example of what I am trying to do,

```r
library(tibbletime)
data("FB")

FB %>%
  ggplot(aes(x = date, y = close)) +
  geom_line() +
  transition_time(date) +
  shadow_mark()
```

Although that example works fine, I cannot recreate it with the dataset used in my original examples above,

```r
airquality %>%
  group_by(Day) %>%
  summarize(min_temp = min(Temp)) %>%
  ungroup() %>%
  ggplot(aes(x = Day, y = min_temp)) +
  geom_line() +
  transition_time(Day) +
  shadow_mark()
```

**Comment by scworland** [comment]
I am going to close this in anticipation of `transition_reveal()`. Thank you for your work on this package.

**Comment by ginolhac** [comment]
You can use `geom_path()`

**Comment by scworland** [comment]
The behavior is the same with geom_path.

```r
ggplot(df, aes(Day,min_temp)) +
  geom_path(color = 'red', size = 1) +
  transition_time(Day) +
  shadow_trail(trail_distance = 1)
```
The axes are rendered but the line is not:

![image](https://user-images.githubusercontent.com/11577981/43519599-1aab43a0-955e-11e8-9126-7db5997ac7a9.png)

**Comment by thomasp85** [comment]
As Scott already points out this is a job for transition_reveal and not shadow_*. shadows draws each frame data as separate groups and lines/paths will thus only consist of single observations
