### ISSUE TITLE
installing gganimate in Windows 10 

### ISSUE THREAD

**Issue by kho7** [thomasp85/gganimate#115]
I have no problem in Mac but my students were unable to install gganimate in Windows environments (Windows 10).  Any suggestions?

**Comment by thomasp85** [comment]
Not unless I'm provided with the errors :-)

It can be that Rtools haven't been installed (required for compiling packages on windows)... 🤷‍♂️

**Comment by kho7** [comment]
Thomas:

Thanks for your prompt reply.  Will the following messages help?

> install.packages("gganimate")
Installing package into ‘c:/R/Library’
(as ‘lib’ is unspecified)
Warning in install.packages :
 package ‘gganimate’ is not available (for R version 3.5.1)


Karl

**Comment by thomasp85** [comment]
This shouldn’t work on either Mac or Windows as gganimate is not yet on CRAN. please follow the installation instructions in the readme

**Comment by kho7** [comment]
We followed the Readme.md file to do the following:

# install.packages('devtools')
devtools::install_github('thomasp85/gganimate')
It works in macOS (10.13.6) but not Windows.  Actually it works great in Mac and the output was fantastic.  Thanks for great package.

**Comment by thomasp85** [comment]
So, what is the error on windows?

**Comment by kho7** [comment]
Thanks again for following up.  Screenshots are as follows:

**Comment by thomasp85** [comment]
I don’t think you can email reply with images - you can add them in the thread directly from GitHub.com

**Comment by kho7** [comment]
Please find screenshots below:

![image](https://user-images.githubusercontent.com/34260946/43522072-bdbea174-95ca-11e8-971c-8d343c6c3465.png)
![image](https://user-images.githubusercontent.com/34260946/43522073-bdf17f54-95ca-11e8-8f06-434ab2374975.png)
![image](https://user-images.githubusercontent.com/34260946/43522074-be19ca04-95ca-11e8-9863-725b8d01821c.png)

**Comment by thomasp85** [comment]
Yeah, that's an Rtools issue. Windows doesn't come with the necessary compilers so Rtools needs to be installed to install packages with compiled code

**Comment by calebasaraba** [comment]
@kho7 I had trouble with this until I found the workaround described here: https://github.com/r-lib/devtools/issues/1772

**Comment by McCartneyAC** [comment]
I'm having similar problems--RTools is updated to 3.5 but R is 3.5.1, so it says it was incompatible: 

```
> devtools::install_github("thomasp85/tweenr")
Downloading GitHub repo thomasp85/tweenr@master
from URL https://api.github.com/repos/thomasp85/tweenr/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installation failed: Could not find build tools necessary to build tweenr
```

**Comment by kho7** [comment]
This thread may help:

https://github.com/r-lib/devtools/issues/1772

**Comment by ghost** [comment]
i have this issue "MAKE NOT FOUND"
![image](https://user-images.githubusercontent.com/68527676/88485586-84e60d00-cf94-11ea-9be5-8d77bc533393.png)
