### ISSUE TITLE
transition_time throws error in thomasp85 gganimate example

### ISSUE THREAD

**Issue by dan-banas** [thomasp85/gganimate#120]
Example from gganimate: https://github.com/thomasp85/gganimate
Found similar error (Issue #104) from 10 days ago and reinstalled transformr but still not working

`library(gapminder)
ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')`

**Error in transition_time(year) : 
  could not find function "transition_time"**

**Comment by thomasp85** [comment]
it seems like you haven't loaded gganimate

**Comment by lmccully10** [comment]
Did you figure this out?

**Comment by dan-banas** [comment]
Yes, thank you
