### ISSUE TITLE
shadow_wake with color

### ISSUE THREAD

**Issue by EmilHvitfeldt** [thomasp85/gganimate#126]
In much the same way that shadow_wake allows for objects to be left in the animation for some time with varying transformation to the size and shape. It would be useful if the same thing could be done with colors.

Example have colors appear in red but `wake` to yellow before disappearing.

```r
# Mock code
data.frame(x = seq_len(150),
           y = seq_len(150)) %>%
  ggplot(aes(x, y)) +
  geom_point() +
  transition_time(y) +
  shadow_wake(wake_length = 0.15, colors = c("yellow", "red"))
```
![](https://i.imgur.com/Bq2enYT.gif)

**Comment by thomasp85** [comment]
I think the reason for me not doing it (I remember considering it) was that every part of the wake might have a different starting colour and thus a separate interpolation to the end color requiring excessive calculations for the effect. I'll look into it again as I agree it would be nice...

**Comment by davechristianson** [comment]
I agree, I was just looking into this and looking at whether or not the wake could also match the same scale_color_gradient defined for the point.
