### ISSUE TITLE
R version dependency

### ISSUE THREAD

**Issue by kdorheim** [thomasp85/gganimate#127]
Hi @thomasp85 

I am trying to use `gganimate` but `devtools::install_github` fails with R 3.4.4. What version of R does your package depend on? 

Thanks!

**Comment by thomasp85** [comment]
There is no inherent version dependency for gganimate itself, but it might be that dependencies such as gifski has... If you could post the error message it would be easier to troubleshoot

**Comment by kdorheim** [comment]
Huh, I got it to install. Sorry about that. 

Thanks for your time.
