### ISSUE TITLE
animate() replaces gganimate()? Running into issues

### ISSUE THREAD

**Issue by FootyNumb3rs** [thomasp85/gganimate#130]
Just installed ggnimate, running into the following issue.

d<-ggplot(
  na.omit(US), 
  aes(x = `AverageTemperature`, y = `Mon`),frame=Year
) +
  geom_density_ridges_gradient(
    aes(fill = ..x..), scale = 3, size = 0.3
  ) +
  scale_fill_gradientn(
    colours = c("#0D0887FF", "#CC4678FF", "#F0F921FF"),
    name = "Temp. [F]"
  )+
  labs(title = 'Temp by Month') 

animate(d)

Returns...

Error in seq.default(1, nframes_final, length.out = nframes) : 
  'to' must be of length 1

The plot displays fine, but the animate(d) returns the above issue.

**Comment by thomasp85** [comment]
See [the readme](https://github.com/thomasp85/gganimate#old-api) - the old api doesn't work anymore
