### ISSUE TITLE
Huge dependencies on Linux

### ISSUE THREAD

**Issue by EoinTravers** [thomasp85/gganimate#132]
I'm installing gganimate on Ubuntu 18.04, and running into some huge dependency requirements. So far, I've had to 

- `apt install libudunits2-dev`, which was quite small.
- `apt install libgdal-dev` (200 MB+)
- `apt install cargo` (also 200 MB+, including installing the entire Rust language)
- Compile `gifski` from source on Rust, including a whole pile of dependencies (pasted below). I don't know how much disk space this has used.

I'm opening this issue because I don't know if all of these are essential components without with gganimate won't work, or if something has gone wrong in the installation process here.
I just wanted to animate a scatter plot!

gifski dependencies:
```
   Compiling rayon-core v1.4.0                                                  
   Compiling scopeguard v0.3.3
   Compiling nodrop v0.1.12
   Compiling either v1.5.0
   Compiling ansi_term v0.11.0
   Compiling memoffset v0.2.1
   Compiling imgref v1.3.4
   Compiling bitflags v1.0.3
   Compiling lazy_static v1.0.0
   Compiling wild v0.1.1
   Compiling cc v1.0.15
   Compiling lzw v0.10.0
   Compiling rgb v0.8.7
   Compiling rustc-demangle v0.1.8
   Compiling vec_map v0.8.0
   Compiling winapi-build v0.1.1
   Compiling glob v0.2.11
   Compiling winapi v0.2.8
   Compiling unicode-width v0.1.4
   Compiling resize v0.3.0
   Compiling cfg-if v0.1.3
   Compiling libc v0.2.40
   Compiling strsim v0.7.0
   Compiling color_quant v1.0.0
   Compiling arrayvec v0.4.7
   Compiling kernel32-sys v0.2.2
   Compiling textwrap v0.9.0
   Compiling crossbeam-utils v0.2.2
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling time v0.1.39
   Compiling atty v0.2.10
   Compiling lodepng v2.1.5
   Compiling gif v0.9.2
   Compiling imagequant-sys v2.11.9
   Compiling backtrace-sys v0.1.16
   Compiling crossbeam-epoch v0.3.1
   Compiling clap v2.31.2
   Compiling gif-dispose v2.1.0
   Compiling crossbeam-deque v0.2.0
   Compiling pbr v1.0.0
   Compiling rayon v0.9.0
   Compiling imagequant v2.11.9
   Compiling backtrace v0.3.7
   Compiling error-chain v0.11.0
   Compiling gifski v0.8.3
   Compiling myrustlib v0.1.0 (file:///tmp/Rtmp3DbzYh/devtools4360676c5fa3/gifski/src/myrustlib)
```

**Comment by thomasp85** [comment]
Both `sf` (responsible for udunits and gdal) and `gifski` (responsible for cargo) are hard dependencies (sf through `gganimate`s need for `transformr`). It is unlikely that I’ll be able to provide the `gganimate` functionality without them
