### ISSUE TITLE
wiki: Remaking ‘Luminance-gradient-dependent lightness illusion’

### ISSUE THREAD

**Issue by ColinFay** [thomasp85/gganimate#136]
I remade the well-know optical illusion with `{gganimate}`:

https://rtask.thinkr.fr/blog/luminance-gradient-dependent-lightness-illusion/ 

![](https://rtask.thinkr.fr/wp-content/uploads/lightness_illustion.gif)

**Comment by thomasp85** [comment]
can i get you to post below the content of the wiki page as you would like it to appear

**Comment by ColinFay** [comment]
Ah, of course, sorry. Here it is:

--- 

# ‘Luminance-gradient-dependent lightness illusion’

_submitted by [Colin Fay](https://github.com/ColinFay)_

This animation is an example of a “gradient illusion”, which is an illustration of how the perception of a color is influenced by the surrounding of this color. 

When looking at the animation, we perceive the color in the square as changing (from darker to lighter), when in fact it stays the same (as you can see, the `fill` is argument is always `#7E7E7E`).

## The Code

``` r
# Coordinates for 10 squares
d <- data.frame(
  x1 = 1:10, x2 = 2:11,
  y1 = 4, y2 = 5,
  t = 1:10
)

# Creating the gradient background
library(grid)
g <- rasterGrob(
  t(colorRampPalette(c("#000000", "#FFFFFF"))(1000)),
  width = unit(1, "npc"), height = unit(1, "npc")
)

# Creating the animation
library(ggplot2)
library(ggmap) # For theme_nothing()
library(gganimate)
ggplot() +
  annotation_custom(g, -Inf, Inf, -Inf, Inf) +
  geom_rect(
    data = d,
    mapping = aes(xmin = x1, xmax = x2, ymin = y1, ymax = y2),
    color = "black", fill = "#7E7E7E"
  ) +
  ylim(c(1, 8)) +
  theme_nothing() +
  transition_time(t) +
  ease_aes("linear")
```

![](https://rtask.thinkr.fr/wp-content/uploads/lightness_illustion.gif)

## Source 

[Remaking ‘Luminance-gradient-dependent lightness illusion’ with R](https://rtask.thinkr.fr/blog/luminance-gradient-dependent-lightness-illusion/)

**Comment by thomasp85** [comment]
Do you want any exposition in there as well as I have done with the gapminder entry?

**Comment by ColinFay** [comment]
If possible, yes :) 

I've update my comment to include a link to my github account, and a little introductory sentence to explain the animation.

**Comment by thomasp85** [comment]
Perfect! I'll always link to the author and potential blogpost if the example comes from there

**Comment by thomasp85** [comment]
https://github.com/thomasp85/gganimate/wiki/Optical-Illusion
