### ISSUE TITLE
wiki: basic examples for transition_states()

### ISSUE THREAD

**Issue by felixgolcher** [thomasp85/gganimate#137]
see resubmission below

**Comment by felixgolcher** [comment]
I'm not sure this is the format you need. I'm trying to approach what I found in the other examples.

**Comment by felixgolcher** [comment]
## transition_states()

_submitted by [Felix Golcher](https://github.com/felixgolcher)_



This little collection is supposed to explore the features of ```transition_states()```. The code is very basic. It was not made for fancy results, but in order to understand the working of gganimate. It's what I had to understand, maybe it helps others to understand faster.


```r
library(gganimate)
```

We start with the animation of two states, one consisting of one point, the other of two.


```r
myps <- 10
dta <- data.frame(y = c(1,1.5,0.5),
                  x = c(1,2,2),
                  tstep = c("a","b","b"))
(gg1 <- ggplot(dta,
              aes(x,y))+geom_point(size=myps)+
    theme_void()+
    labs(title="state: {closest_state}")+
    transition_states(states=tstep,
                      transition_length = 1,
                      state_length = 1)+
    ease_aes('linear')+
    enter_fade()+
    exit_fade())
```

![](http://korpling.german.hu-berlin.de/~felix/test_files/figure-html/mychunk-1.gif)


Two states are identified: the point on the left (state a) morphs into the upper point of state b.
but why this one? What determines, what points are identified? 
It's not by distance, as the next animation shows:


```r
dtb <- dta
dtb$x[3] <- 1.1
dtb$y[3] <- 1

gg1 %+% dtb
```

![](http://korpling.german.hu-berlin.de/~felix/test_files/figure-html/unnamed-chunk-2-1.gif)

Though the lower point of state b is now much closer to the point of state a, the state a point still morphs into the upper point of state b.


There is only one option left: We conclude it should be determined by ordering of points:


```r
gg1 %+% dta[c(1,3,2),]
```

![](http://korpling.german.hu-berlin.de/~felix/test_files/figure-html/bla-1.gif)
Indeed.

If we introduce colors for different, we see another detail: Only points of the exact same quality are identified: If the two states have different colours, no points are identified, no morphing occurs.


```r
(gg2 <- ggplot(dta,
               aes(x,y,col=tstep))+
   geom_point(size=myps,show.legend = F)+
   theme_void()+
   transition_states(states=tstep,
                     transition_length = 1,
                     state_length = 1)+
   labs(title="state: {closest_state}")+
   ease_aes('linear')+
   enter_fade()+
   exit_fade())
```

![](http://korpling.german.hu-berlin.de/~felix/test_files/figure-html/fig2-1.gif)


If we color more sensibly across states, only points with the same color are identified:

```r
dta$id <- c("A","B","A")
(gg3 <- ggplot(dta,
               aes(x,y,col=id))+
    geom_point(size=myps,show.legend = F)+
    theme_void()+
    labs(title="state: {closest_state}")+
    transition_states(states=tstep,
                      transition_length = 1,
                      state_length = 1)+
    ease_aes('linear')+
    enter_fade()+
    exit_fade())
```

![](http://korpling.german.hu-berlin.de/~felix/test_files/figure-html/col1-1.gif)


Of course, if we add new points, ordering is again used for identifying points:

```r
dtd <- rbind(dta, data.frame(x=1.5,y=1,tstep="b",id="A"))
## We should get a new point near the disappearing one.
gg3 %+% dtd
```

![](http://korpling.german.hu-berlin.de/~felix/test_files/figure-html/unnamed-chunk-3-1.gif)

If you want to avoid identification of object across states, the states can be assigned to different groups:

```r
ggplot(dta,
       aes(x,y,group=tstep))+geom_point(size=myps)+
  theme_void()+
  transition_states(states=tstep,
                    transition_length = 1,
                    state_length = 1)+
  ease_aes('linear')+
  enter_fade()+
  exit_fade()
```

![](http://korpling.german.hu-berlin.de/~felix/test_files/figure-html/figf-1.gif)

**Comment by thomasp85** [comment]
This could be really good if reframed from a focus on transition_states and instead focusing on how gganimate matches up elements (either index or the group aesthetic). The examples could be left as is, but a bit of rewording would be good. Would you be willing to do that?

Also, a last option - if the grouping is not unique, points are matched first by group and then by index within the groups

**Comment by felixgolcher** [comment]
I'll try my best with pleasure.

**Comment by felixgolcher** [comment]
maybe like this:

## Object permanence: Which data points describe the same object?

_submitted by [Felix Golcher](https://github.com/felixgolcher)_



This little collection is supposed to explore the rules determining which data points are seen by ```gganimate``` as representing the *same* object across the animation and which are not. The code is very basic. It was not made for fancy looks but in order to understand the working of gganimate. It's what I had to understand, maybe it helps others to understand faster.


```r
library(tidyverse)
library(gganimate)
```

We start with the animation of two states ```a``` and ```b```, ```a``` consisting of one point, ```b``` consisting of two.


```r
myps <- 10
dta <- data.frame(y =     c(1,   1.3, 0.7),
                  x =     c(1,   2,   2),
                  tstep = c("a", "b", "b"))
(gg1 <- ggplot(dta,
              aes(x,y))+geom_point(size=myps)+
    theme_void()+
    coord_equal()+
    labs(title="state: {closest_state}")+
    transition_states(states=tstep,
                      transition_length = 1,
                      state_length = 1)+
    ease_aes('linear')+
    enter_fade()+
    exit_fade())
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/mychunk-1.gif" title="Basis: Two state solution." alt="Basis: Two state solution." style="display: block; margin: auto;" />

Two of the points are identified as belonging to the same object: the point on the left (state ```a```) morphs into the upper point of state ```b```.
but why this one? What determines, what points are identified? 
Distance doesn't play a role as the next animation shows:


```r
dtb <- dta
dtb$x[3] <- 1.1
dtb$y[3] <- 1

gg1 %+% dtb
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/c2-1.gif" title="The points further apart are identified and tranform into each other." alt="The points further apart are identified and tranform into each other." style="display: block; margin: auto;" />
Though the lower point of state ```b``` is now much closer to the point of state ```a```, the state a point still morphs into the upper point of state ```b```.


There is only one option left: We conclude it should be determined by the ordering of points:


```r
gg1 %+% dta[c(1,3,2),]
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/bla-1.gif" title="Now the two other points are morphed into each other." alt="Now the two other points are morphed into each other." style="display: block; margin: auto;" />
If we introduce color, we see another detail: Only points of the exact same quality are identified: If the two states have different colours, no points are identified, no morphing occurs.


```r
(gg2 <- ggplot(dta,
               aes(x,y,col=tstep))+
   geom_point(size=myps,show.legend = F)+
   theme_void()+
   coord_equal()+
   transition_states(states=tstep,
                     transition_length = 1,
                     state_length = 1)+
   labs(title="state: {closest_state}")+
   ease_aes('linear')+
   enter_fade()+
   exit_fade())
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/fig2-1.gif" title="Now, no points are identified with each other." alt="Now, no points are identified with each other." style="display: block; margin: auto;" />
If we color more sensibly across states, only points with the same color are identified:

```r
dta$id <- c("A","B","A")
(gg3 <- ggplot(dta,
               aes(x,y,col=id))+
    geom_point(size=myps,show.legend = F)+
    theme_void()+
    coord_equal()+
    labs(title="state: {closest_state}")+
    transition_states(states=tstep,
                      transition_length = 1,
                      state_length = 1)+
    ease_aes('linear')+
    enter_fade()+
    exit_fade())
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/col1-1.gif" title="The two red points morph into each other." alt="The two red points morph into each other." style="display: block; margin: auto;" />
If we add new points, ordering is again used for identifying points as describing the same object:

```r
dtd <- rbind(dta, data.frame(x=1.5,y=1,tstep="b",id="A"))
gg3 %+% dtd
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/c3-1.gif" title="plot of chunk c3" alt="plot of chunk c3" style="display: block; margin: auto;" />
If you want to avoid identification of object across states without using color, the states can be assigned to different groups:

```r
ggplot(dta,
       aes(x,y,group=tstep))+geom_point(size=myps)+
  theme_void()+
  coord_equal()+
  transition_states(states=tstep,
                    transition_length = 1,
                    state_length = 1)+
  ease_aes('linear')+
  enter_fade()+
  exit_fade()
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/figf-1.gif" title="Do not identify points over different states." alt="Do not identify points over different states." style="display: block; margin: auto;" />

**In summary:** data points which match in all aesthetics, including group, describe the same object. If ambiguities remain, the ordering of the data is used for matching up objects.

Our last animation in this series repeats the first. But now we add a fourth data point, which is now connected with the orphaned data point. There are two objects on the move:


```r
dtg <- rbind(dta, data.frame(x=1,y=1.1,tstep="a",id=NA))
gg1 %+% dtg
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/figg-1.gif" title="plot of chunk figg" alt="plot of chunk figg" style="display: block; margin: auto;" />


If you **want** to identify data points across different qualities, you can explicitly identify them by using ```transition_components```.


```r
dtc <- data.frame(x =    c(1,   2,   2,    1),
                  y =    c(1.4, 1,   1.4,  1),
                  id =   c("a", "a", "b",  "b"),
                  time = c(1,   2,   2.1,  3.1),
                  element = paste0("e",1:4))
(gg4 <- ggplot(dtc, aes(x,y,label=element,col=element)) +
    geom_point(size=20, show.legend = F) +
    geom_text(size=10, show.legend = F, col="black") +
    theme_void()+
    coord_equal()+
    labs(title="Time {round(frame_time,2)}")+
    transition_components(id=id,
                          time=time,
                          enter_length = .2,
                          exit_length = .2,
                          range=c(0,6))+
    enter_fade())
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/tc1-1.gif" title="plot of chunk tc1" alt="plot of chunk tc1" style="display: block; margin: auto;" />

If there are more elements with a specific ID at some time than at others, the old rules apply and ordering comes into play again: The Element ```e5```, added at the end of the data frame, appears from nowhere.


```r
dte <- rbind(dtc, data.frame(x=2,y=1.2,id="a",time=2.0,element="e5"))
gg4 %+% dte
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/tc2-1.gif" title="plot of chunk tc2" alt="plot of chunk tc2" style="display: block; margin: auto;" />
If we pull it to the top of the data frame, ```e1``` now morphs into the new element and ```e2```, now further down in the data, appears only later:

```r
gg4 %+% dte[c(5,1:4),]
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/tc3-1.gif" title="plot of chunk tc3" alt="plot of chunk tc3" style="display: block; margin: auto;" />

There are transitions which do not seem to allow movement of objects at all, as the following examples show.


```r
homo <- data.frame(from=c(-2.3e5, -2e5, -7e5, -3e5),
                   to=c(-3e4, 0, -3e5, -2e5),
                   spec=c("Neanderthalensis","Sapiens","Heidelbergensis","(archaic) Sapiens"),
                   x=c(1,1,1,1),
                   y=c(1,2,2,2))
ggplot(homo, aes(x,y,label=spec))+
  geom_text(size=10)+
  theme_void()+
  coord_equal()+
  xlim(c(-2,4))+
  ylim(c(.5,2.5))+
  transition_events(start=from,
                    end=to,
                    exit_length = 1e4)+
  labs(title="{-round(frame_time/1000)*1000} BCE")+
  exit_fade()+
  ease_aes('linear')
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/te1-1.gif" title="plot of chunk te1" alt="plot of chunk te1" style="display: block; margin: auto;" />


```r
dtf <- data.frame(x=rnorm(100),
                  y=rnorm(100))
ggplot(dtf, aes(x,y))+
  geom_point()+
  transition_filter(transition_length = 1,
                    filter_length = 1,
                    x>y,x<y,x>-y,x< -y)
```

<img src="http://korpling.german.hu-berlin.de/~felix/figure/tf1-1.gif" title="plot of chunk tf1" alt="plot of chunk tf1" style="display: block; margin: auto;" />

**Comment by thomasp85** [comment]
This looks very good - I think I might want to split it up into several as it will get very gif heavy otherwise

**Comment by felixgolcher** [comment]
You can change it in every way it seems suitable to you, including editing my grauenhaft English. Tell me if I shall add or edit something.

**Comment by thomasp85** [comment]
This is good - I just need some time to go through it

**Comment by neilstats** [comment]
I've found these examples useful to understanding how `gganimate` matches up elements, however I have some problem with the last example:

```R
dtf <- data.frame(x=rnorm(100),
                  y=rnorm(100))
ggplot(dtf, aes(x,y))+
  geom_point()+
  transition_filter(transition_length = 1,
                    filter_length = 1,
                    x>y,x<y,x>-y,x< -y)
```

I get the error:
`Error: from and to must have identical columns`

**Comment by felixgolcher** [comment]
I could reproduce. I found no easy fix.

**Comment by thomasp85** [comment]
@felixgolcher the bug is now fixed and your wiki is at https://github.com/thomasp85/gganimate/wiki/Object-permanence:-Which-data-points-describe-the-same-object%3F
