### ISSUE TITLE
wik: intro stats animation examples

### ISSUE THREAD

**Issue by CrumpLab** [thomasp85/gganimate#138]
I've been using gganimate to make GIFs for an intro stats textbook. I added a chapter to the end of the textbook containing all of the source code and some descriptions for each animation. 

https://crumplab.github.io/statistics/gifs.html

I wasn't sure exactly what kind of formatting you would like for these wiki posts. Once I see some more examples, I may post some individual examples with code. Most of my animations are pretty basic. Thanks for the work on gganimate, it's awesome!

**Comment by thomasp85** [comment]
Have a look at some of the examples that are up now :-)

**Comment by thomasp85** [comment]
@CrumpLab are you interested in writing some wiki's ? otherwise I'll close this (no pressure)

**Comment by CrumpLab** [comment]
I don't think I'll have time right now to add more beyond that one i did on having multiple plots. Happy to have this closed. If I end up making more animations that do something interesting, I'll come back and add to the wiki. Thanks again for all your work on gganimate!

**Comment by thomasp85** [comment]
No problem at all - feel free to add something at a later stage
