### ISSUE TITLE
transition fails for ggraph

### ISSUE THREAD

**Issue by systats** [thomasp85/gganimate#139]
Hi!

I am trying to mix gganimate with ggraph but unfortunately I encounter the following error. 

`Error in data.frame(..., check.names = FALSE) : `
`arguments imply differing number of rows: 21, 100` 

I am not sure how to deal with it. There seems to be a [similar issue](https://github.com/thomasp85/gganimate/issues/122) already open with a different geom but the error is the same.

Here is a *reproducible example*:

**Some example data:**

```
library(ggplot2)
library(ggraph)
library(gganimate)
library(dplyr)

df <- tibble(
  from = c(
    "A" , "B",
    "A" , "C",
    "B" , "D",
    "C" , "D",
    "C" , "B",
    "D" , "E"
  ),
  to = c(
    "C" , "B",
    "B" , "C",
    "B" , "A",
    "D" , "D",
    "C" , "A",
    "A" , "D"
  ),
  date = rep(c(as.Date("2018-08-12"), as.Date("2018-08-13")), 6)
)
```

**the plot:**

```
p <- df %>% 
  graph_from_data_frame() %>%
    ggraph() +
    geom_node_point() + 
    geom_edge_arc() 
```

**facet_wrap works just fine:**

```
p +
    facet_wrap(~date)
```

![image](https://user-images.githubusercontent.com/22753281/44215192-39087780-a172-11e8-81ce-c2a481bb7f85.png)

**but the animation fails:**

```
p +
    transition_time(date)
````

`Error in data.frame(..., check.names = FALSE) : `
`arguments imply differing number of rows: 21, 100`

**Comment by favstats** [comment]
I've been struggling with the exact same thing. Following.

**Comment by thomasp85** [comment]
Thanks. Haven't thoroughly tested ggraph integration yet and this is a great reprex to dig into it!

**Comment by thomasp85** [comment]
I have traced this to the underlying stats in ggforce overwriting the group aesthetic, which gganimate uses to keep track of row information. Should be an easy fix

**Comment by khailper** [comment]
When trying to reproduce this issue, I got a different error message:
"Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) :
 zero-length inputs cannot be mixed with those of non-zero length"

The only difference is I included `library(igraph)` to import graph_from_data_frame().

**Comment by thomasp85** [comment]
gganimate code is still in flux so it is quite possible that the change in error is due to changes in gganimate rather than the change in your code
