### ISSUE TITLE
transition_manual fails ("Additional frame variables must have the same length as the number of frames")

### ISSUE THREAD

**Issue by mjskay** [thomasp85/gganimate#141]
I have been trying to use `transition_manual` and have been unable to get it to work. For example, I tried running the example code at the bottom of the README:

```r
ggplot(mtcars) + 
  geom_boxplot(aes(factor(cyl), mpg)) + 
  transition_manual(gear)
```

```
# Error: Additional frame variables must have the same length as the number of frames
```

This same error is given no matter what I set the number of output frames to; for example:

```r
p = ggplot(mtcars) + 
  geom_boxplot(aes(factor(cyl), mpg)) + 
  transition_manual(gear)

# I have tried many different values of nframes below to no avail
animate(p, nframes = length(unique(mtcars$gear)))
```

```
# Error: Additional frame variables must have the same length as the number of frames
```

Am I missing something?

**Comment by BillPetti** [comment]
I am having a similar issue. Just updated to `R 3.5.1` this morning as well as `gganimate  0.9.9.9999`. `transition_manual` was working fine before making these two updates.

```
g <- ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot() + 
  transition_manual(gear)

animate(g)  
```
```
Error: Additional frame variables must have the same length as the number of frames
```

**Comment by mjskay** [comment]
To add to this: I think that for both this and maybe even other transition types, it would be great if the default behavior was to calculate a reasonable minimum number of frames necessary, rather having the default be a fixed number. Then most of the time API users would not need to manually tweak frame counts.

**Comment by thomasp85** [comment]
I think it makes sense to have a fixed default, but transition types have the power to alter this if necessary - the heuristics obviously needs some tweaking
