### ISSUE TITLE
Error due to tweenr numeric state interpolator

### ISSUE THREAD

**Issue by robertlennox** [thomasp85/gganimate#144]
I updated R to the newest version and my animation no longer runs- I have tried reinstalling tweenr, transformr, and gganimate using force=T and restarting everything but still get the following error:

Error in .Call("_tweenr_numeric_state_interpolator", PACKAGE = "tweenr",  : 
  "_tweenr_numeric_state_interpolator" not available for .Call() for package "tweenr"

Thanks for any advice, amazing package!

**Comment by thomasp85** [comment]
I expect you are on windows - I've had other report issues with the latest windows version... I believe it might be due to problems with RTools, but since I'm not on windows I can't really investigate

**Comment by jamesrozier9** [comment]
@robertlennox I had received a similar error with the tween_states function and was able to resolve using a workaround code listed below. After that, I reinstalled tweenr. Hope this works for you.

[Source: [AntoineC](https://community.rstudio.com/t/error-dependency-transformr-is-not-available-for-package-gganimate/11134/6)]
`# Set path of Rtools`
`Sys.setenv(PATH = paste(Sys.getenv("PATH"), "*InstallDirectory*/Rtools/bin/",`
`                       "*InstallDirectory*/Rtools/mingw_64/bin", sep = ";")) #for 64 bit version`
`Sys.setenv(BINPREF = "*InstallDirectory*/Rtools/mingw_64/bin")`
`library(devtools)`

`#Manually "force" version to be accepted` 
`assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0",` `version_max = "99.99.99", path = "bin"))), "devtools")`
`find_rtools() # is TRUE now`

**Comment by thomasp85** [comment]
Thanks @Reizor1989

**Comment by robertlennox** [comment]
Wow what a relief- thank you so much!

**Comment by alex-trueman** [comment]
I am running the latest R, RStudio, and all packages. I am also on Windows Pro 10 Build 1803. I get a similar error even after successfully running @Reizor1989 's script:


`Error in .Call("_tweenr_colour_state_interpolator", PACKAGE = "tweenr",  : 
  "_tweenr_colour_state_interpolator" not available for .Call() for package "tweenr"`

**Comment by thomasp85** [comment]
@truemoid does the discussion in this thread help you? https://github.com/r-lib/devtools/issues/1772

**Comment by alex-trueman** [comment]
@thomasp85 yes, I tried these suggestions without success. I reinstalled everything (R, rtools, RStudio) and started again. When I first load `gganimate` (`library(gganimate)`) I receive the error:

    object ‘keep_state’ is not exported by 'namespace:tweenr'

After restarting RStudio that error goes away and when I run your example code I get the original error message.

**Comment by thomasp85** [comment]
Sounds like you have the CRAN version of tweenr - try installing it from GitHub
