### ISSUE TITLE
wiki: Datasaurus Dozen

### ISSUE THREAD

**Issue by tomwestlake121** [thomasp85/gganimate#145]
This example may be too simple to include.

### The Datasaurus Dozen

The Datasaurus Dozen is a playful twist on Anscombe's Quartet.  A group of twelve datasets, with nigh-identical summary statistics, yet when plotted on a graph they prove to be distinctly dissimilar.

The animation below, utilising the `datasauRus`, `ggplot2` and `gganimate` packages, highlights the dangers of relying solely on summary statistics without considering
the whole distribution

### The Code

```
library(datasauRus)
library(ggplot2)
library(gganimate)

ggplot(datasaurus_dozen, aes(x=x, y=y))+
  geom_point()+
  theme_minimal() +
  transition_states(dataset, 3, 1)
```
![datasaurus](https://user-images.githubusercontent.com/28370599/44246283-4276fb80-a1d5-11e8-9a91-881b78f3884b.gif)

### Source

[Reanimating the Datasaurus](https://r-mageddon.netlify.com/post/reanimating-the-datasaurus/)

**Comment by dgrtwo** [comment]
BTW I love this! An amazing example of how gganimate lets you accomplish so much with so little.

**Comment by thomasp85** [comment]
https://github.com/thomasp85/gganimate/wiki/The-Datasaurus-Dozen

**Comment by tomwestlake121** [comment]
Sorry to reopen this mate, but do you mind adding a link to my blogpost? (Have amended my initial submission)

**Comment by thomasp85** [comment]
Done
