### ISSUE TITLE
Colouring static points and animating days

### ISSUE THREAD

**Issue by Valexandre** [thomasp85/gganimate#146]
I have a dataframe with places, lat, lon, dates and a colouring value that should change when the day changes.
Something like
Ville, valuethatshouldmodifycolour, latitude, longitude, day,daylitteral
Bordeaux,2.7,44.84123,-0.580036,20180622, 22/06/2018
Bordeaux,2.3,44.84123,-0.580036,20180624, 24/06/2018
Lille,1,50.4,3.3,20180623, 23/06/2018
Lille,1.2,50.4,3.3,20180625, 25/06/2018
Marseille,3,43.15,5.7,20180622, 22/06/2018
Marseille,2.2,43.15,5.7,20180624, 24/06/2018
...

When I use this code
 `ggplot(df)+
  geom_point(aes(longitude,latitude,colour=valuethatshouldmodifycolour))+
  labs(title = 'Day: {frame_time}')+
  transition_time(day)+
  ease_aes('linear')`

I get points that move...
![nawaktemperatures](https://user-images.githubusercontent.com/12694649/44256550-ca76f880-a209-11e8-8ae2-2c5dd234c970.gif)

What do i have to change to get the points to change colour when the day changes and how do I print the litteraldays instead of the numeric days ?

Thanks !

**Comment by Valexandre** [comment]
I didn't see that the points actually changed colours ! Nice. 
However, the moving bit is still an issue.

**Comment by thomasp85** [comment]
elements are matched based on the group aesthetic - in absence of that it simply matches based on position in the original data. In order to ensure that elements are correctly matched, simply give each point a unique id across the different states and assign that to the group aesthetic

**Comment by Valexandre** [comment]
So a `geom_point(aes(longitude,latitude,colour=valuethatshouldmodifycolour, group=Ville)` should do the trick ?

However, I encounter another issue : my RSession aborts now everytime I run the gganimate part of the ggplot... It has worked once. Is there a known reason for this ?

**Comment by thomasp85** [comment]
It should, yes.

Don't know about the crash - haven't heard it reported before... Maybe reinstall relevant packages (gganimate, tweenr, transformr)
