### ISSUE TITLE
transition_time + geom_line require a minimum number of 

### ISSUE THREAD

**Issue by BillPetti** [thomasp85/gganimate#151]
Maybe some of this will be addressed by `transition_reveal()`, but I was wondering whether there is some minimum number of values for the `time` argument in `transition_time()` that is required when building an animation using `geom_line()`?

This example from issue #97 works fine for me:

```
library(gganimate)
library(tidyverse)
library(tibbletime)
data("FB")

FB %>%
  ggplot(aes(x = date, y = close)) +
  geom_line() +
  transition_time(date) +
  shadow_mark()
```
![reprex_plot](https://user-images.githubusercontent.com/1923057/44420102-0b914480-a54b-11e8-890a-f30819745f19.gif)

But if I limit the number of rows to just the month of January (i.e. the first 21 rows) the plot does not render:

```
FB[c(1:21), ] %>%
  ggplot(aes(x = date, y = close)) +
  geom_line() +
  transition_time(date) +
  shadow_mark()
```
![reprex_plot_limited](https://user-images.githubusercontent.com/1923057/44421326-34ff9f80-a54e-11e8-8b9a-b88a5bf5a5d8.gif)

**Comment by KilianB** [comment]
I just noticed the opposite for transition_states. For large datasets and factors the states are not individually rendered but everything is shown at once and suddenly it disappears again.

**Comment by duttashi** [comment]
Regret to intervene but the minimum reprex posted is not entirely reproducible.  @BillPetti consider adding  call to ` library (gganimate)`. Absence of which throws the error, `Error in transition_time(date) :  could not find function "transition_time"`.

**Comment by thomasp85** [comment]
This is due to each frame only containing a single time point making it impossible to draw a line. Use `transition_reveal()` instead
