### ISSUE TITLE
expression() in axis labels causes animation to fail

### ISSUE THREAD

**Issue by dtickler** [thomasp85/gganimate#152]
Hi Thomas,

For some reason including expression() functions in labels when using gganimate causes the animation to fail to render.

The following example replicates the kind of error I get (the error description changes with more complex plots, but the cause and effect seem to be the same)

```
dummy_data = data_frame(year = 1990:2000, x = 1:11, y = 1:11)

require(gganimate)

# This works fine:

ggplot(dummy_data) +
  geom_point(aes(x, y)) +
  transition_time(year) +
  labs(title = 'Year: {round(frame_time,0)}', x = 'GDP per capita, US$', y = 'CO2, tonnes per capita')

# This fails with "Error: All unnamed arguments must be length 1":

ggplot(dummy_data) +
  geom_point(aes(x, y)) +
  transition_time(year) +
  labs(title = 'Year: {round(frame_time,0)}', x = 'GDP per capita, US$', y = expression(CO[2]*', tonnes per capita'))

# But expression() does not cause problem in non-animated plot

ggplot(dummy_data[dummy_data$year == 2000,]) +
  geom_point(aes(x, y)) +
  # transition_time(year) +
  labs(title = 'Year: 2000', x = 'GDP per capita, US$', y = expression(CO[2]*', tonnes per capita'))

```
Is gganimate reading the expression() function differently from plain ggplot?

Cheers,

Dave

R version info:

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray

Using R Studio Version 1.1.456

**Comment by thomasp85** [comment]
Thanks for reporting this. It is a bug due to oversight on my part and will get fixed

**Comment by dtickler** [comment]
Thanks! gganimate is fantastic - great work!
