### ISSUE TITLE
[Feature request]: Transition treshold

### ISSUE THREAD

**Issue by marcosci** [thomasp85/gganimate#153]
Hey Thomas,

thanks a ton for the gganimate makeover!

Coming from the ecological modeling perspective to gganimate, it would be nice if we could use gganimate without specifying the number of frames to the number of our simulation steps. This is needed because our object of animation (in this example a point) is moving on a wrapped world (a torus) and is leaving the "world" on one site and entering it on the opposite.

If we are now interpolating between the movement steps, we are dragging them for example from the left to the right, instead of just letting them reappear on the right side again.

See here for example (without an ease and therefore quite wiggly):

![](https://nldoc.github.io/nlrx/articles/articles/wolfsheep_world.gif)

To counteract that one could, for example, set a threshold of distances between data points and if we are above this threshold instead of applying the specified transformation it would just perform an out-in animation? This would a huge benefit also for shadow trails because drawing a line for example behind the point would not cross the entire plot area.

Does that make any sense, if not - I am happy to provide more plots showing what I mean.

Cheers

**Comment by jonspring** [comment]
Might one approach be to track edge crossings in the data and make this
assign the point to a new group?

**Comment by thomasp85** [comment]
@jonspring’s approach is the right one. I don’t think this situation is general enough (and has a general solution) to be included as a feature in gganimate
