### ISSUE TITLE
version is incompatible with R 3.5.1

### ISSUE THREAD

**Issue by Ricardo627721141** [thomasp85/gganimate#154]
version is incompatible with R 3.5.1

**Comment by thomasp85** [comment]
I’ll need more information than this. I’m running 3.5.1 with no problems

**Comment by Ricardo627721141** [comment]
Thanks for your reply, I have solved this problem. Actually, it seems to be a common problem of Rtool.

When I was installing your package, it warn me that "Rtools 3.5 found on the path at D:/R/Rtools is not compatible with R 3.5.1", even though I have update R, Rstudio, and Rtool to the latest version. Finally, I found many people also met with this problem and there had been solution on stackoverflow(https://stackoverflow.com/questions/33103203/rtools-is-not-being-detected-from-rstudio). It is just a problem caused by ambiguous path setting of Rtool's installation package.
