### ISSUE TITLE
Animation fails if more than 50 levels are present

### ISSUE THREAD

**Issue by KilianB** [thomasp85/gganimate#156]
When working with more than 50 levels the animation doesn't render correctly. All frames are drawn at the same time. Below you find a snippet to reproduce the error. Before executing make sure that dim1 actually contain 51 levels due to runif

``` r
library(ggplot2)
library(gganimate)

x <- runif(500)
y  <- runif(500)
dim0 <- as.factor(floor(runif(500, min= 0, max = 50)))
dim1 <- as.factor(floor(runif(500, min= 0, max = 51)))
df <- data.frame(x,y)

#This works
ggplot(data = df, aes(x =x,y=y)) +  
  geom_point() + 
  theme_minimal() +
  transition_states(dim0,5,5)

````
![filefb082f4c3160](https://user-images.githubusercontent.com/9025925/44735168-f76dba00-aaeb-11e8-84b8-f00e7124975f.gif)

``` r
#This doesn't
ggplot(data = df, aes(x =x,y=y)) +  
  geom_point() + 
  theme_minimal() +
  transition_states(dim1,5,5)
```

![filefb08fc867db](https://user-images.githubusercontent.com/9025925/44735262-37cd3800-aaec-11e8-9981-cf80d3775b98.gif)

**Comment by thomasp85** [comment]
This seems related to #143

**Comment by KilianB** [comment]
Indeed it is.  Increasing the number of frames manually fixes the issue.

````R
plot <- ggplot(data = df, aes(x =x,y=y)) +  
  geom_point() + 
  theme_minimal() +
  transition_states(dim1,5,5)

animate(plot, nframes = 200)
````

**Comment by thomasp85** [comment]
gganimate now makes better animations when the time resolution is lower than the number of states, but you're still better off increasing either `nframes` or `detail`
