### ISSUE TITLE
when I run an example in gganimate's readme, they always run into error message as following:

### ISSUE THREAD

**Issue by coollioner** [thomasp85/gganimate#160]
the example code is in the readme files,I am sure it is correctly.
ggplot(mtcars, aes(factor(cyl), mpg)) +
  geom_boxplot() +
  transition_states(gear,
                    transition_length = 2,
                    state_length = 1) +
  enter_fade() +
  exit_shrink() +
  ease_aes('sine-in-out')
the error message as following:
Error in .Call("_tweenr_colour_state_interpolator", PACKAGE = "tweenr",  : 
  "_tweenr_colour_state_interpolator" not available for .Call() for package "tweenr"
who can tell me how to deal with it?Thx very much!

**Comment by coollioner** [comment]
and I am install the transformr package directly, I can't install it. the following error message as:
Warning: S3 methods '$.bbox', '$.crs', '$<-.sf', '[.sf', '[.sfc', '[<-.sfc', '[[<-.sf', 'st_agr<-.sf', 'st_crs<-.sf', 'st_crs<-.sfc', 'st_geometry<-.data.frame', 'st_geometry<-.sf', 'Ops.crs', 'Ops.sfc', 'Ops.sfg', 'Ops.sgbp', 'aggregate.sf', 'as.data.frame.sf', 'as.data.frame.sfc', 'as.data.frame.sgbp', 'as.matrix.sfg', 'as.matrix.sgbp', 'c.sfc', 'c.sfg', 'cbind.sf', 'dim.sgbp', 'format.sfc', 'format.sfg', 'head.sfg', 'identify.sf', 'identify.sfc', 'is.na.bbox', 'is.na.crs', 'merge.sf', 'plot.sf', 'plot.sfc_CIRCULARSTRING', 'plot.sfc_GEOMETRY', 'plot.sfc_GEOMETRYCOLLECTION', 'plot.sfc_LINESTRING', 'plot.sfc_MULTILINESTRING', 'plot.sfc_MULTIPOINT', 'plot.sfc_MULTIPOLYGON', 'plot.sfc_POINT', 'plot.sfc_POLYGON', 'plot.sfg', 'print.bbox', 'print.crs', 'print.sf', 'print.sf_layers', 'print.sfc', 'print.sfg', 'print.sgbp', 'rbind.sf', 'rep.sfc', 'st_agr.character', 'st_agr.default', 'st_agr.factor', 'st_agr.sf', 'st_as_binary.sfc', 'st_as_binary.sfg', 'st_as_grob.CIRCULARSTRING', 'st_as_grob.COMPOUN [... truncated]
Error in library.dynam(lib, package, package.lib) : 
  DLL 'sf' not found: maybe not installed for this architecture?
ERROR: lazy loading failed for package 'transformr'
* removing 'D:/R/R-3.5.1/library/transformr'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by coollioner** [comment]
Error in .Call("_tweenr_colour_state_interpolator", PACKAGE = "tweenr",  : 
  "_tweenr_colour_state_interpolator" not available for .Call() for package "tweenr"

**Comment by thomasp85** [comment]
This is a common problem with Windows R v3.5.1 and not really related to gganimate. See https://github.com/r-lib/devtools/issues/1772 for a solution
