### ISSUE TITLE
how to plot point by point.

### ISSUE THREAD

**Issue by kurisusl** [thomasp85/gganimate#161]
I want to plot point by point and keep the point after plotting. just like the gif in this page [https://github.com/thomasp85/tweenr/issues/12](url)
in the new version this code seemed not to work. And I wonder how to achieve it.
What if I had a point background, and I just want to animate a small set of the points?

**Comment by thomasp85** [comment]
You can always have a static layer, if that is what you mean? Just make sure the data for that layer doesn't include any transition variables in the same way as you would add a layer that appears in each facet...

For keeping points after they have appeared, have a look at `shadow_mark()`, or potentially `transition_reveal()`
