### ISSUE TITLE
`geom_line()` appears to be erroring

### ISSUE THREAD

**Issue by ha0ye** [thomasp85/gganimate#165]
Trying out the latest version of the package to use `transition_reveal`, I ran into some issues with old examples. I think this is now specifically an issue with `geom_line`. Compare the following examples:

``` r
library(gganimate)
#> Loading required package: ggplot2
ggplot(airquality, aes(Day, Temp)) +
    geom_line(color = 'red', size = 1) +
    transition_time(Month)
#> Error in !id: invalid argument type
```

Created on 2018-09-04 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

``` r
library(gganimate)
#> Loading required package: ggplot2
ggplot(airquality, aes(Day, Temp)) +
    geom_point(color = 'red', size = 1) +
    transition_time(Month)
```

![](https://i.imgur.com/eCU945s.gif)

Created on 2018-09-04 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
I can't reproduce this - try to upgrade transformr...

**Comment by ha0ye** [comment]
Huh, now working for me, as well. 🤔
¯\_(ツ)_/¯
