### ISSUE TITLE
gganimate examples failing

### ISSUE THREAD

**Issue by statsbylopez** [thomasp85/gganimate#168]
Running the suggested code in the R Documentation for `transition_reveal`: 

```{r}
ggplot(airquality, aes(Day, Temp, group = Month)) +
    geom_line() +
   transition_reveal(Month, Day)
```
Yields the following error: 
`Error in .Call("_tweenr_numeric_along_interpolator", PACKAGE = "tweenr",  : 
  "_tweenr_numeric_along_interpolator" not available for .Call() for package "tweenr"`.

Running the suggested code for `transition_time()`: 

```{r}
p <- ggplot(airquality, aes(Day, Temp)) +
  geom_line(color = 'red', size = 1) +
  transition_time(Month)
```

yields the following error: 

`Error in !id : invalid argument type`

I'm using Windows 3.5, and I successfully have the most recent `ggaminate` and `tweenr` versions (downloaded from Github).  The link [here](https://github.com/thomasp85/gganimate/issues/144#issuecomment-414052078) was particularly helpful in this regard. 

Also, I can get some examples to work anyways. As one, this works just fine:

```{r}
ex.points <- tibble(
  id.number = 1:100,
  x.final = rnorm(100), y.final = rnorm(100))
ggplot() + 
 geom_point(data = ex.points, 
             aes(x.final, y.final)) +  
 transition_time(id.number) + 
 ease_aes('linear')
```

I'm sure you are scrunched for time, but any insight would be most helpful

-Mike

**Comment by statsbylopez** [comment]
As a follow-up, this code also fails: 

```{r}
ggplot() + 
 geom_point(data = ex.points, 
             aes(x.final, y.final)) +  
 transition_reveal(id.number) 
```

`Error in seq.default(range[1], range[2], length.out = nframes) : 
  'from' must be a finite number
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf`

**Comment by thomasp85** [comment]
I cannot reproduce any of your errors in the original issue. The tweenr error suggests you don't really have the latest tweenr version - maybe it didn't get installed correctly? The `Error in !id` looks like you have an old transformr installation

for the last issue, `transition_reveal()` requires two arguments, but you only supply one, resulting in the error (which I admit could be more helpful)
