### ISSUE TITLE
cumulative 

### ISSUE THREAD

**Issue by pparshakov** [thomasp85/gganimate#169]
Is there in the new API a way to use cumulative layers like in the previous version of gganimate?

**Comment by thomasp85** [comment]
Not directly, but the old behaviour can be replicated with either transition_reveal() or shadow_mark(), depending on the effect you are after. See the air temperature example in the wiki

**Comment by ptoche** [comment]
not sure if it's worth opening an issue: I suggest that at the bottom of the README, you mention that there are examples in the wiki. This is going to sound stupid, but it's only after reading this thread (while obviously searching for a way to reproduce ``cumulative``) that I became aware of the wiki (I had not noticed the link to "wiki"!). Simply saying, "Please see the wiki for more examples" would have been enough. With a direct link even better.
