### ISSUE TITLE
Supress printing in the title

### ISSUE THREAD

**Issue by jebyrnes** [thomasp85/gganimate#17]
I have a ggplot I've been building, and as a last step, add frame as a new aesthetic. But now my title incorporates the frame indicator. I actually use this elsewhere in the plot (via geom_text), and so don't want it in the title. It's unclear how to stop this behavior by `gg_animate()`.

**Comment by JasonAizkalns** [comment]
See `?gg_animate` and look at the `title_frame` argument.
