### ISSUE TITLE
transition_reveal

### ISSUE THREAD

**Issue by chalg** [thomasp85/gganimate#170]
I can run the temperature example as expected. When I try to use my own data set, I seem to have a couple of erroneous lines unfortunately. ggplot is ok, problem is in transition_reveal. It is pretty minor but annoying. Great work on this package BTW.

## Full code
```ggplot(ura_aug, aes(x = date, y = close, group = symbol)) +
  geom_line() +
  geom_segment(aes(xend = end, yend = close), linetype = 2, colour = 'grey') + 
  geom_point(size = 2) + 
  geom_text(aes(x = end, label = symbol), hjust = 0) + 
  transition_reveal(month, day) + 
  coord_cartesian(clip = 'off') + 
  labs(title = 'ASX Uranium Juniors', y = 'Closing Price') + 
  theme_minimal() + theme(plot.margin = margin(5.5, 40, 5.5, 5.5)) +
  theme(legend.position = "none")
```
![ura_aug_complete](https://user-images.githubusercontent.com/26208482/45260690-24499780-b431-11e8-9f29-73255143e57b.gif)

## Skeleton of the above
```ggplot(ura_aug, aes(x = date, y = close, group = symbol)) +
  geom_line() +
  transition_reveal(month, day)
```
![ura_aug](https://user-images.githubusercontent.com/26208482/45260371-7b4b6e80-b429-11e8-8ad9-d9f03bb74e60.gif)

Data:
[ura_aug.zip](https://github.com/thomasp85/gganimate/files/2363904/ura_aug.zip)
Environment:
Windows 10
RStudio Version 1.1.456
R version 3.5.1

**Comment by thomasp85** [comment]
This is because `month` in your dataset does not differentiate your data is it does in my example. Try this instead:

```r
data <- read.csv('ura_aug.csv')
ggplot(data) + 
  geom_line(aes(day, close, group = symbol)) + 
  transition_reveal(symbol, day)
```

**Comment by spoonertaylor** [comment]
Hello @thomasp85 , I am facing the same problem and when trying to recreate your fix I am getting the error:

> Error: along data must either be integer, numeric, POSIXct, Date, difftime, orhms
In addition: Warning message:
In min(cl[cl != 0]) : no non-missing arguments to min; returning Inf

Was there an update or anything that would be changing this functionality? Thank you.

**Comment by chalg** [comment]
I can't see your code, but I would try putting the date field in the transition_reveal function to see if it works.
