### ISSUE TITLE
Animation with transparent Background

### ISSUE THREAD

**Issue by nihi1** [thomasp85/gganimate#174]
When i generate an animation from ggplots with transparent background, the gif will have a white bbackground after exporting it using anim_save(). Is there a way, similare to the ggsave(bg = 'transparent') option to maintain the transparent background of each frame when exporting?

**Comment by thomasp85** [comment]
you can set device arguments in the call to `animate()` (e.g. `animate(anim, bg = 'transparent')`, or set defaults for it with `options(gganimate.dev_args = list(bg = 'transparent'))`
