### ISSUE TITLE
Potential bug in parameters of transition_reveal() 

### ISSUE THREAD

**Issue by wenlong-liu** [thomasp85/gganimate#175]
In the documentation of **transition_reveal()**, it says:

> transition_along makes the following variables available for string literal interpretation:

>    *frame_along* gives the position on the along-dimension that the current frame corresponds to.

When I try to use *frame_along* in string, it report errors.  After viewing the source codes for [**transition_reveal()**](https://github.com/thomasp85/gganimate/blob/36dd957e7c12f620f5beeb151823416e7cd60fee/R/transition_reveal.R), it seems that the *frame_time* is the correct label parameter.

---
Here is a minimum reproducible example.

    require(gganimate)

    # produce some fake data.
    data <- data.frame(time = c(1,2,3,4,5,6,7,8,9,10),
                   y = c(1,1.5,0.5,2,5,3,2,6,1,8),
                   x = c(1,2,2,3,2.5,7,4,6,7,8)
                  )
    # generate animation using transition_reveal()
    ggplot(data, aes(x = x, y = y, color = time)) +
      geom_point()+
      geom_path()+
      theme_bw()+
      transition_reveal(time,time)+
      labs(title = "time:{frame_time}")

Thanks,
Wenlong Liu

**Comment by thomasp85** [comment]
Should be fixed - try updating
