### ISSUE TITLE
Wiki: animated maps to track hurricane or typhoons using transition_reveal()

### ISSUE THREAD

**Issue by wenlong-liu** [thomasp85/gganimate#177]
# Animated maps to track hurricane or typhoons using transition_reveal()
*Submitted by [Wenlong Liu](https://github.com/wenlong-liu)* 

Thank you for your excellent work in developing this awesome package.  Recently I generated an animated map to track the path of Typhoon Doksuri happened in Asia.  I hope this post can be served as a wiki example to help generate animated maps.  

## Import packages and data
    require(gganimate)
    require(tidyverse)
    require(lubridate)
    require(ggmap)
    require(maps)
    require(mapdata)

    # import data hosted in my github rep. 
    typhoon_data <- read.csv("https://raw.github.com/wenlong-liu/typhoon_animation/master/Data/typhoon_doksuri.csv")
    
    # data cleaning.
    tracks <-  typhoon_data %>% 
      # reforamt date time using lubridate package. 
      mutate(time = mdy_hm(time)) %>% 
      # rename columns.
      rename(long = lng) 

## Drawing an animated tracking map.

The author drew an animated trakcing map using *gganimate*. In the subtitle of the plot, a real-time clock was added to show the timeline of the tracking path. 

    # draw a base box for maps.
    tracks_box <- make_bbox(lon = tracks$long, lat = tracks$lat, f = 0.5)
    sq_map <- get_map(location = tracks_box, maptype = "satellite", source = "google", zoom = 5)
    
    # plot map.
    ggmap(sq_map) + 
      theme(text = element_text(size = 17))+
      geom_point(data = tracks, mapping = aes(x = long, y = lat, color = pressure)) +
      geom_line(data = tracks, mapping = aes(x = long, y = lat, color = pressure), size = 2) +
      scale_color_continuous(name = "Pressure(hPa)",low = "yellow", high = "red")+
      labs(title = "Tracking of Typhoon Doksuri happened in 2017",
          subtitle = "Time:{frame_time}",
          x = "Long", y = "Lat", 
          caption = "Data Source: jswater.jiangsu.gov.cn")+
      transition_reveal(1,time)+
      NULL

![doksuri_tracking](https://user-images.githubusercontent.com/32007394/45713010-daad2b00-bb5b-11e8-8a5b-335e373541e6.gif)

## Source:
The example was adapted from [this blog post](https://wenlong-liu.github.io/post/generate-animated-tracking-maps-for-hurricanes-and-typhoons/)

**Comment by thomasp85** [comment]
I believe assigning the same variable to both `id` and `along` is an error. You'd probably want something like `transition_reveal(1, time)` as you only have a single line to draw (`1` is just an arbitrary single value)...

**Comment by wenlong-liu** [comment]
@thomasp85 I think you are right.  I have updated the example by changing the parameters and also uploading the new version of animation.  Thanks for pointing out.

**Comment by Ricardo627721141** [comment]
Marvelous! I am just going to search for how to print path of typhoon with gganimate. The new edition seems not to support geom_path.

**Comment by thomasp85** [comment]
Why shouldn’t it support geom_path?

**Comment by wenlong-liu** [comment]
@Ricardo627721141 I tested the *geom_path* and it gives me the same results.  So I think the new edition supports *geom_path*.

**Comment by thomasp85** [comment]
https://github.com/thomasp85/gganimate/wiki/Tracking-of-hurricanes-and-typhoons
