### ISSUE TITLE
Installation issue with R 3.5.1

### ISSUE THREAD

**Issue by cainesap** [thomasp85/gganimate#179]
Hello,
Firstly thank you for the great resource!
Secondly just reporting a quick dependency issue when installing gganimate on Mac OS X with R 3.5.1.
When running `devtools::install_github('thomasp85/gganimate')` I saw the following error message:
```
ERROR: dependency ‘farver’ is not available for package ‘tweenr’
```
So then installed farver separately, which has to be done from source currently. Then re-ran install and all was fine. Just thought this worth reporting in case it's new, and perhaps worth adding a note to the Installation section of the README..
thanks again, Andrew

**Comment by hughthescientist** [comment]
Thanks so much cainesap!  I was hung up for days - tried everything.  That worked.

**Comment by thomasp85** [comment]
I’m pretty sure this was just a temporary hiccup as farver got on CRAN

**Comment by jalamruna** [comment]
> devtools::install_github('thomasp85/gganimate')
Error in curl::curl_fetch_memory(url, handle = h) : 
  Failed to connect to api.github.com port 443: Connection refused
