### ISSUE TITLE
error with loop=FALSE option

### ISSUE THREAD

**Issue by cainesap** [thomasp85/gganimate#18]
Taking the example from the README, which I can reproduce without issue, and adding what I think is the correct library (`library(animate)`) and options calls (`ani.options(loop = FALSE)`):

```
library(gapminder)
library(ggplot2)
library(gganimate)
library(animate)
theme_set(theme_bw())
ani.options(loop = FALSE)
p <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, color = continent, frame = year)) +
  geom_point() +
  scale_x_log10()
gg_animate(p)
```

I encounter the following error:

```
Executing: 
'convert' -loop FALSE -delay 100 Rplot1.png Rplot2.png Rplot3.png
    Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png
    Rplot10.png Rplot11.png Rplot12.png 'filef899fc930d.gif'
convert: invalid argument for option `-loop': FALSE @ error/convert.c/ConvertImageCommand/2024.
an error occurred in the conversion... see Notes in ?im.convert
Error in file(file, "rb") : cannot open the connection
In addition: Warning messages:
1: In normalizePath(movie.name) :
  path[1]="filef899fc930d.gif": No such file or directory
2: In file(file, "rb") :
  cannot open file '/var/folders/p8/8d4g5v_53t3glcsclzx5cc8h0000gn/T//RtmptnzNkU/gganimate/filef899fc930d.gif': No such file or directory
```

[Running R 3.3.1 "Bug in your hair" on Mac OS X 10.11.6]

**Comment by ottlngr** [comment]
Is there a workaround for this issue?

**Comment by ottlngr** [comment]
To solve this and to disable looping, one has to set `loop = 1` in `ani.options()`, so that `-loop 1` is forwarded to ImageMagick. From the ImageMagick manual:

> -loop {number}:Number of times the GIF animation is to cycle though the image sequence before stopping.

So this is actually not an issue with `gganimate` but rather with the `animation` package, which provides `ani.options()`.

**Comment by ottlngr** [comment]
https://github.com/yihui/animation/pull/90

**Comment by pearsonca** [comment]
This issue should be resurrected - all renderers default to `loop=TRUE`.  If I define and use
```
altrenderer <- gifski_renderer(loop=FALSE)
anim_save(...etc..., renderer=altrenderer)
```
then I can get the desired result, but the conversation here all points towards using `ani.options(loop=TRUE)` to manage this.

One simple approach to this would be to have `loop=TRUE` in the signature in `anim_save` and then have the default renderer construction use the value of loop.

At the very least it's a documentation issue.

**Comment by thomasp85** [comment]
This issue is related to the old API and has no bearing on the new version.

**Comment by pearsonca** [comment]
Fair enough; what is the "right" way to do it in the new API?

**Comment by thomasp85** [comment]
Do it in the renderer as you are doing already. Not all types of output can be looped so it does not make sense to have an argument in `animate()`
