### ISSUE TITLE
is farver for gganimate broken right now?

### ISSUE THREAD

**Issue by favstats** [thomasp85/gganimate#180]
Hi, I am having trouble running my gganimate code after I updated it today.

``` r
library(ggplot2)
library(gganimate)
ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot() + 
  transition_states(gear, transition_length = 2, state_length = 1) + 
  enter_fade() + 
  exit_shrink() + 
   ease_aes("sine-in-out")
#> Error in .Call("_farver_convert_c", PACKAGE = "farver", colour, from, : Wrong number of Arguments (5), expected 3 for '_farver_convert_c'
```

Just letting you know :)

**Comment by favstats** [comment]
Never mind, fixed it with several reinstalling attempts :D

**Comment by villeseppala** [comment]
@favstats Can you elaborate what and how you reinstalled? I'm encountering the exactly same error after installing the newest gganimate version and using it. Re-installing it hasn't helped, at least not yet.

**Comment by favstats** [comment]
@rville good question. It's been a while now so I don't remember exactly. I think I uninstalled/deleted all the packages that come with gganimate and reinstalled those. So that's for example farver but also tweenr. Sorry that I can't be of more help.

**Comment by villeseppala** [comment]
@favstats It worked! Thanks for for the quick reply. 

Here's the list of stuff I uninstalled and then reinstalled. Don't know which of the uninstalls were necessary for the process:

remove.packages('tweenr')
remove.packages('gganimate')
remove.packages('farver')
remove.packages('transformr')
remove.packages('gifski')
