### ISSUE TITLE
transitions are slow and not smooth

### ISSUE THREAD

**Issue by tamannahaque** [thomasp85/gganimate#182]

**Comment by thomasp85** [comment]
Is this related to rendering animations in rmarkdown?

**Comment by tamannahaque** [comment]
Hi, yes in both rmarkdown and radix.

**Comment by thomasp85** [comment]
should be fixed now - I was using the default `interval` option from `knitr` to set fps but this defaults to `1` which gives the slow animations...

**Comment by tamannahaque** [comment]
All perfect now, thank you :)
