### ISSUE TITLE
gganimate installation error

### ISSUE THREAD

**Issue by oleber72** [thomasp85/gganimate#183]
I have problem when install gganimate 
> devtools::install_github("thomasp85/gganimate")
Downloading GitHub repo thomasp85/gganimate@master
from URL https://api.github.com/repos/thomasp85/gganimate/zipball/master
Installing gganimate
Installation failed: Illegal characters found in URL

**Comment by npcooley** [comment]
I get the same error when trying to install gganimate

`> library(devtools)`
`> install_github(repo = "thomasp85/gganimate")`
`Downloading GitHub repo thomasp85/gganimate@master
from URL https://api.github.com/repos/thomasp85/gganimate/zipball/master
Installing gganimate
Installation failed: Illegal characters found in URL`

**Comment by thomasp85** [comment]
Should be fixed now
