### ISSUE TITLE
bugs when animating area charts

### ISSUE THREAD

**Issue by bianchenhao** [thomasp85/gganimate#185]
When I animate multiple area charts, some areas were lost.
Static plot is below. (In the code is q)
![1](https://user-images.githubusercontent.com/40454528/46081391-f903ce00-c1ce-11e8-97bc-b7d400055986.png)
Animation is below.
![file76c51446eef](https://user-images.githubusercontent.com/40454528/46081134-521f3200-c1ce-11e8-8349-b7c05465f7dd.gif)
```
library(ggplot2)
library(data.table)
library(gganimate)
plotdata4 <- fread("https://raw.githubusercontent.com/bianchenhao/co2_vis/master/China_carbon_dioxide_emissions_by_sector.csv") 
# data is China carbon dioxide emissions by sector
#    region Year                 variable     value
#1:  China 1990                   Energy 1679608.5
#2:  China 1991                   Energy 1801117.7
#3:  China 1992                   Energy 1922209.8
#4:  China 1993                   Energy 2105100.9
#5:  China 1994                   Energy 2269401.2
# 6:  China 1995                   Energy 2493834.0
p <- ggplot(plotdata4, aes(x = Year, y = value, fill = variable))
q <- p + geom_area() 
q
q + transition_reveal(value, Year)
```

**Comment by thomasp85** [comment]
It appears my fix broke a lot of other code, so I'm re-opening and looking for a better fix

**Comment by thomasp85** [comment]
This issue has been fixed due to other internal changes
