### ISSUE TITLE
How does gganimate order an ordered bar time-series?

### ISSUE THREAD

**Issue by ghost** [thomasp85/gganimate#189]
Hello,

I have a time-series of data, where I'm plotting diagnosis rates for a disease on the y-axis `DIAG_RATE_65_PLUS`, and geographical groups for comparison on the x-axis `NAME` as a simple bar graph. My time variable is `ACH_DATEyearmon`, which the animation is cycling through as seen in the title.

    df %>% ggplot(aes(reorder(NAME, DIAG_RATE_65_PLUS), DIAG_RATE_65_PLUS)) +
      geom_bar(stat = "identity", alpha = 0.66) +
      labs(title='{closest_state}') +
      theme(plot.title = element_text(hjust = 1, size = 22),
            axis.text.x=element_blank()) +
      transition_states(ACH_DATEyearmon, transition_length = 1, state_length = 1) +
      ease_aes('linear')

I've reordered `NAME` so it gets ranked by `DIAG_RATE_65_PLUS`. 

What gganimate produces:

[![gganimate plot][1]][1]

I now have two questions:

1) How exactly does gganimate reorder the data? There is some overall general reordering, but each month has no frame where the groups are perfectly ordered by `DIAG_RATE_65_PLUS` from smallest to biggest. Ideally, I would like the final month "Aug 2018" to be ordered perfectly. All of the previous months can have their x-axis based on the ordered `NAME` for "Aug 2018`.

2) Is there an option in gganimate where the groups "shift" to their correct rank for each month in the bar chart?

l can make a reproducible example if needed.

  [1]: https://i.stack.imgur.com/GzcaT.gif

**Comment by thomasp85** [comment]
A reprex would be nice, thanks🙂

**Comment by VictorAres** [comment]
df <- structure(list(NAME = c("WES", "WES", "WES", "WES", "WES", "WES", 
"WES", "WES", "WES", "WES", "WES", "WES", "HUM", "HUM", "HUM", 
"HUM", "HUM", "HUM", "HUM", "HUM", "HUM", "HUM", "HUM", "HUM", 
"GRE", "GRE", "GRE", "GRE", "GRE", "GRE", "GRE", "GRE", "GRE", 
"GRE", "GRE", "GRE", "CHE", "CHE", "CHE", "CHE", "CHE", "CHE", 
"CHE", "CHE", "CHE", "CHE", "CHE", "CHE", "SOU", "SOU", "SOU", 
"SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", 
"STA", "STA", "STA", "STA", "STA", "STA", "STA", "STA", "STA", 
"STA", "STA", "STA", "SHR", "SHR", "SHR", "SHR", "SHR", "SHR", 
"SHR", "SHR", "SHR", "SHR", "SHR", "SHR", "DER", "DER", "DER", 
"DER", "DER", "DER", "DER", "DER", "DER", "DER", "DER", "DER", 
"LIN", "LIN", "LIN", "LIN", "LIN", "LIN", "LIN", "LIN", "LIN", 
"LIN", "LIN", "LIN", "NOT", "NOT", "NOT", "NOT", "NOT", "NOT", 
"NOT", "NOT", "NOT", "NOT", "NOT", "NOT", "LEI", "LEI", "LEI", 
"LEI", "LEI", "LEI", "LEI", "LEI", "LEI", "LEI", "LEI", "LEI", 
"THE", "THE", "THE", "THE", "THE", "THE", "THE", "THE", "THE", 
"THE", "THE", "THE", "BIR", "BIR", "BIR", "BIR", "BIR", "BIR", 
"BIR", "BIR", "BIR", "BIR", "BIR", "BIR", "COV", "COV", "COV", 
"COV", "COV", "COV", "COV", "COV", "COV", "COV", "COV", "COV", 
"HER", "HER", "HER", "HER", "HER", "HER", "HER", "HER", "HER", 
"HER", "HER", "HER", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", 
"NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "CAM", "CAM", "CAM", 
"CAM", "CAM", "CAM", "CAM", "CAM", "CAM", "CAM", "CAM", "CAM", 
"NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", 
"NOR", "NOR", "NOR", "SUF", "SUF", "SUF", "SUF", "SUF", "SUF", 
"SUF", "SUF", "SUF", "SUF", "SUF", "SUF", "MIL", "MIL", "MIL", 
"MIL", "MIL", "MIL", "MIL", "MIL", "MIL", "MIL", "MIL", "MIL", 
"HER", "HER", "HER", "HER", "HER", "HER", "HER", "HER", "HER", 
"HER", "HER", "HER", "MID", "MID", "MID", "MID", "MID", "MID", 
"MID", "MID", "MID", "MID", "MID", "MID", "NOR", "NOR", "NOR", 
"NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", 
"NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", 
"NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", 
"NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "SOU", "SOU", "SOU", 
"SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", 
"SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", "SOU", 
"SOU", "SOU", "SOU", "KEN", "KEN", "KEN", "KEN", "KEN", "KEN", 
"KEN", "KEN", "KEN", "KEN", "KEN", "KEN", "SUS", "SUS", "SUS", 
"SUS", "SUS", "SUS", "SUS", "SUS", "SUS", "SUS", "SUS", "SUS", 
"FRI", "FRI", "FRI", "FRI", "FRI", "FRI", "FRI", "FRI", "FRI", 
"FRI", "FRI", "FRI", "SUR", "SUR", "SUR", "SUR", "SUR", "SUR", 
"SUR", "SUR", "SUR", "SUR", "SUR", "SUR", "COR", "COR", "COR", 
"COR", "COR", "COR", "COR", "COR", "COR", "COR", "COR", "COR", 
"DEV", "DEV", "DEV", "DEV", "DEV", "DEV", "DEV", "DEV", "DEV", 
"DEV", "DEV", "DEV", "SOM", "SOM", "SOM", "SOM", "SOM", "SOM", 
"SOM", "SOM", "SOM", "SOM", "SOM", "SOM", "BRI", "BRI", "BRI", 
"BRI", "BRI", "BRI", "BRI", "BRI", "BRI", "BRI", "BRI", "BRI", 
"BAT", "BAT", "BAT", "BAT", "BAT", "BAT", "BAT", "BAT", "BAT", 
"BAT", "BAT", "BAT", "DOR", "DOR", "DOR", "DOR", "DOR", "DOR", 
"DOR", "DOR", "DOR", "DOR", "DOR", "DOR", "HAM", "HAM", "HAM", 
"HAM", "HAM", "HAM", "HAM", "HAM", "HAM", "HAM", "HAM", "HAM", 
"GLO", "GLO", "GLO", "GLO", "GLO", "GLO", "GLO", "GLO", "GLO", 
"GLO", "GLO", "GLO", "BUC", "BUC", "BUC", "BUC", "BUC", "BUC", 
"BUC", "BUC", "BUC", "BUC", "BUC", "BUC", "DUR", "DUR", "DUR", 
"DUR", "DUR", "DUR", "DUR", "DUR", "DUR", "DUR", "DUR", "DUR", 
"NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", "NOR", 
"NOR", "NOR", "NOR", "WES", "WES", "WES", "WES", "WES", "WES", 
"WES", "WES", "WES", "WES", "WES", "WES", "LAN", "LAN", "LAN", 
"LAN", "LAN", "LAN", "LAN", "LAN", "LAN", "LAN", "LAN", "LAN"
), ACH_DATEyearmon = structure(c(2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2017.66666666667, 
2017.75, 2017.83333333333, 2017.91666666667, 2018, 2018.08333333333, 
2018.16666666667, 2018.25, 2018.33333333333, 2018.41666666667, 
2018.5, 2018.58333333333, 2017.66666666667, 2017.75, 2017.83333333333, 
2017.91666666667, 2018, 2018.08333333333, 2018.16666666667, 2018.25, 
2018.33333333333, 2018.41666666667, 2018.5, 2018.58333333333, 
2017.66666666667, 2017.75, 2017.83333333333, 2017.91666666667, 
2018, 2018.08333333333, 2018.16666666667, 2018.25, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333), class = "yearmon"), 
    DIAG_RATE_65_PLUS = c(73.6, 73.7, 74.2, 73.8, 73.3, 73.3, 
    72.8, 72.5, 72.5, 72.8, 72.9, 73, 65.4, 65.8, 66.9, 66.3, 
    66.1, 66.1, 65.7, 65.4, 65.7, 66.1, 66.3, 66.3, 77.3, 77.4, 
    77.6, 77.3, 76.7, 76.6, 76.4, 76.4, 76.3, 76.7, 77.2, 76.9, 
    71.3, 71.5, 71.4, 71, 70.3, 69.9, 69.6, 69.4, 69.4, 69.4, 
    69.7, 69.7, 78.1, 78.1, 78, 77.4, 77.1, 77, 76.6, 76, 76.3, 
    76.6, 76.9, 76.8, 71, 71.5, 72.2, 71.2, 70.9, 70.6, 70.1, 
    70, 70.1, 70.1, 70.4, 70.7, 68.5, 69.1, 68.9, 68, 67.4, 67.7, 
    68.1, 68.3, 68.3, 68.5, 70.4, 69.1, 73.4, 73.4, 74, 73.4, 
    71.5, 72.4, 71.6, 71.3, 71.1, 71.3, 71.5, 71.5, 63.3, 63.9, 
    64.2, 63.9, 63.5, 62.6, 62.9, 62.9, 62.8, 63.3, 63.7, 64.1, 
    77, 77.5, 77.8, 77.3, 76.9, 76.5, 76.4, 76.1, 76.2, 76.2, 
    76.1, 75.9, 73.4, 73.8, 74.1, 73.6, 73.9, 74, 73.7, 73.3, 
    73, 73, 73.3, 73.3, 68, 68.3, 68.5, 68.1, 67.6, 67.3, 67.1, 
    66.4, 66.1, 65.6, 65.4, 65.8, 66.6, 67, 67.9, 67.5, 66.8, 
    66.8, 66.2, 66.1, 66.3, 66.3, 66.2, 66.4, 60.5, 60.5, 60.9, 
    60.4, 60.4, 59.9, 59.5, 59.5, 59.4, 59.5, 59.3, 59.7, 61.1, 
    60.9, 60.7, 60.1, 59.3, 58.6, 58.9, 58, 59, 58.1, 57.9, 58.1, 
    68.7, 68.9, 68.9, 68.4, 67.9, 67.5, 67.1, 66.7, 66.9, 67, 
    66.8, 67.3, 65.8, 65.8, 65.5, 65.1, 64.8, 64.6, 64.3, 64, 
    63.9, 64.6, 64.5, 65, 62.1, 62.1, 62.5, 62.2, 61.8, 61.6, 
    62, 61.5, 61.9, 62.1, 62.3, 62.8, 62.1, 62.1, 62, 62, 62, 
    62.2, 61.9, 62, 62.5, 63.2, 63.7, 63.9, 62.6, 62.5, 63, 63.1, 
    62.7, 62.4, 61.8, 61.3, 61.3, 61.9, 62, 61.7, 66.8, 66.9, 
    67.1, 66.8, 66.5, 66.4, 66.1, 65.6, 66.1, 67.4, 67.9, 67.6, 
    63.2, 64.1, 64.7, 64.2, 63.6, 63.4, 63.5, 63.7, 64.1, 64.4, 
    65.8, 65.2, 70.9, 73, 72.5, 72, 71.9, 71.3, 70.9, 70.7, 70.8, 
    71.1, 71, 71, 76.9, 76.8, 76.8, 76.7, 76.3, 76.3, 76.2, 76, 
    76.1, 76.6, 76.7, 77.1, 69.8, 69.4, 69.3, 68.8, 68.1, 67.6, 
    67.2, 66.9, 67, 67.6, 67.7, 67.8, 69.5, 69.2, 68.8, 68.7, 
    68.6, 68.9, 69.2, 69.2, 69.4, 70, 69.7, 69.7, 69, 69.4, 69.5, 
    69.5, 69.5, 69.4, 69.4, 69.4, 69.4, 69.5, 69.6, 69.7, 62.2, 
    62.4, 63.1, 61.8, 61.7, 61.4, 61, 61.1, 60.7, 60.7, 60.6, 
    61, 65.7, 66, 66.3, 66.5, 66.5, 66.5, 66.2, 66.6, 66.4, 66.9, 
    66.9, 67.3, 67.9, 68.6, 68.7, 68.6, 68.1, 67.5, 67.1, 66.9, 
    67, 67.7, 67.1, 67.2, 64.1, 64.7, 64.4, 64.5, 64.2, 64.5, 
    64.4, 64.6, 64.4, 64.6, 64.5, 64.8, 55.4, 55.1, 55, 54.8, 
    54.3, 53.4, 52.4, 52.4, 52.1, 51.2, 51, 51.9, 60.7, 60.6, 
    60.9, 60.4, 60.2, 59.8, 59.5, 59.2, 59.2, 59.2, 59.4, 59.1, 
    61.7, 61.5, 62.4, 62.3, 62.5, 62.3, 61.9, 62, 61.9, 62.5, 
    61.8, 61.9, 67.9, 68.4, 68.6, 68.1, 67.8, 68, 67.6, 68.2, 
    67.4, 68.5, 67.7, 68.3, 64.4, 64.7, 64.6, 64.1, 63.9, 63.8, 
    63.5, 63.1, 63.4, 64, 64.5, 64.5, 61.9, 61.3, 61.6, 62, 61.7, 
    61.6, 61.4, 61.2, 60.9, 61, 60.9, 61.1, 65.2, 65.7, 65.8, 
    65.4, 64.9, 64.9, 64.9, 64.8, 65, 65.2, 65.4, 65.3, 68.3, 
    68.4, 67.6, 67.9, 67.5, 67.4, 67, 67.5, 65, 66.9, 67.3, 66.3, 
    66.4, 66.5, 66.7, 66.2, 66.1, 65.9, 65.5, 65.5, 65.5, 65.8, 
    66.2, 66.3, 78.2, 78.7, 79.3, 78.9, 78.3, 77.7, 77.6, 77.1, 
    77, 77.1, 77.6, 77.5, 72.3, 72.5, 73.3, 72.3, 72.1, 71.7, 
    71.7, 71.4, 71.3, 71.6, 71.8, 72.1, 64.4, 64.5, 65.4, 65.1, 
    65.2, 64.3, 63.9, 63.6, 63.8, 64.1, 64.4, 64.4, 73.9, 73.7, 
    74.1, 73.7, 73, 72.8, 72.5, 72.4, 72.6, 72.9, 72.5, 72.4)), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -528L))

**Comment by ghost** [comment]
```
df <-structure(list(NAME = c("BATH", "BATH", "BATH", "BATH", "BIRM", 
"BIRM", "BIRM", "BIRM", "BRIS", "BRIS", "BRIS", "BRIS", "BUCK", 
"BUCK", "BUCK", "BUCK", "CAMB", "CAMB", "CAMB", "CAMB", "CHES", 
"CHES", "CHES", "CHES", "CORN", "CORN", "CORN", "CORN", "COVE", 
"COVE", "COVE", "COVE", "DERB", "DERB", "DERB", "DERB", "DEVO", 
"DEVO", "DEVO", "DEVO", "DORS", "DORS", "DORS", "DORS", "DURH", 
"DURH", "DURH", "DURH", "FRIM", "FRIM", "FRIM", "FRIM", "GLOU", 
"GLOU", "GLOU", "GLOU"), ACH_DATEyearmon = structure(c(2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333, 2018.33333333333, 
2018.41666666667, 2018.5, 2018.58333333333), class = "yearmon"), 
    DIAG_RATE_65_PLUS = c(63.4, 64, 64.5, 64.5, 66.3, 66.3, 66.2, 
    66.4, 67.4, 68.5, 67.7, 68.3, 65.5, 65.8, 66.2, 66.3, 63.9, 
    64.6, 64.5, 65, 69.4, 69.4, 69.7, 69.7, 52.1, 51.2, 51, 51.9, 
    59.4, 59.5, 59.3, 59.7, 71.1, 71.3, 71.5, 71.5, 59.2, 59.2, 
    59.4, 59.1, 60.9, 61, 60.9, 61.1, 77, 77.1, 77.6, 77.5, 67, 
    67.7, 67.1, 67.2, 65, 66.9, 67.3, 66.3)), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -56L))
````

**Comment by ghost** [comment]
An answer has been provided on stack:

https://stackoverflow.com/questions/52623722/how-does-gganimate-order-an-ordered-bar-time-series

**Comment by ghost** [comment]
Actually, having looked at their code further, I still have some issues, if you could kindly have a look at my thread on stack, I'd really appreciate it (mainly with regards to my second and third comment to eipi10).

**Comment by thomasp85** [comment]
I am unsure about your actual issue? what is missing from the excellent answers already given on SO?

**Comment by ghost** [comment]
Sorry, my stack question was getting quite messy. Building on Jon Spring's answer:

I changed `min_rank` is his mutate to `row_number` as this caused some glitches with bars which had equal values. In addition, I removed one his `geom_text` layers which placed text above the bars as I didn't require it.

```
df2 <- df %>%
  group_by(ACH_DATEyearmon) %>%
  mutate(ordering = row_number(DIAG_RATE_65_PLUS) * 1.0) %>%
  ungroup()

p <- df2 %>%
  ggplot(aes(ordering, group = NAME)) +

  geom_tile(aes(y = DIAG_RATE_65_PLUS/2, 
                height = DIAG_RATE_65_PLUS,
                width = 0.9), alpha = 0.9, fill = "gray60") +
  # text in x-axis (requires clip = "off" in coord_cartesian)
  geom_text(aes(y = 0, label = NAME), hjust = #) +
  coord_flip(clip = "off", expand = FALSE) +

  labs(title='{closest_state}', x = "") +
  theme(plot.title = element_text(hjust = 1, size = 22),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_blank(),
        plot.margin = margin(0, 0, 0, 3, "cm")) + 


  transition_states(ACH_DATEyearmon, 
                    transition_length = 2, state_length = 1) +
  ease_aes('cubic-in-out')

animate(p, nframes = 300, fps = 20, width = 400, height = 300)
```

using the df I posted above, I wanted to be able to flip the graph, so I changed: 

- `coord_cartesian` to `coord_flip` which still had available `clip` and `expand` arguments required for the `geom_text`
- Changing `axis.text.x = element_blank()` and `axis.ticks.x=element_blank()` to their y equivalents for the flipped y-axis labels and ticks to appear at the bottom.
- Remove `vjust` argument from `geom_text` as this was only applicable on the standard co-ords, and otherwise the labels would now become misaligned with the geom_tiles.
- Intuitively seeing as `vjust` was previously used I could use `hjust` to adjust placement of geom_text:
- Add `plot.margin` argument to `theme` function to account for additional hjust values.

I've uploaded 4 versions of hjust below.

no `hjust` arg
![no hjust arg](https://i.imgur.com/W8qHUo7.gif)

`hjust=0`
![hjust=0](https://i.imgur.com/2hivSot.gif)

`hjust=1`
![hjust=1](https://i.imgur.com/ByECuEn.gif)

`hjust=2`
![hjust=2](https://i.imgur.com/iNScCI8.gif)

 Ideally, I need the axis text to be right-aligned like when `hjust = 1`, with the space between the text and geom_tiles as seem in `hjust = 2`, as they're too close to the geom_tiles in `hjust=1`. This is my biggest issue.

**UPDATE**

Adding `nudge_y` argument to `geom_text` has offered a stopgap solution. Note `hjust` still needs to = 1 for right-alignment. I used `nudge_y = -10`.

![Imgur](https://i.imgur.com/V6Xh6LJ.gif)

This has increased the space between the axis text and the bars, but through increasing the plot background. Ideally I meed the separation to remain white, the same as the non-plot background.

**Comment by ghost** [comment]
I have another issue with eipi10's answer, but it's not as salient as my first query.

His idea of using `geom_barh` works well when I only want the bars to be ordered once, based on a single time point throughout the entire animation, however `geom_vline` seems to be incompatible (which in my real plot, represents a threshold for the diagnostic rate).

````
df$ACH_DATEyearmon %<>% as.character() %>% as_factor()
df1 <- df %>% 
  arrange(DIAG_RATE_65_PLUS) %>% 
  mutate(NAME = factor(NAME, levels=unique(NAME[ACH_DATEyearmon=="2018.58333333333"])))

baz<- df1 %>% 
  ggplot(aes(y=NAME, x=DIAG_RATE_65_PLUS)) +
  geom_barh(stat = "identity", alpha = 0.66) +
  labs(title='{closest_state}') +
  theme(plot.title = element_text(hjust = 1, size = 22)) +
  # geom_vline(xintercept=(2/3)*100, linetype = "dotdash") + #geom_vline is incompatible.. but geom_hline works, but it's not useful for the plot
  transition_states(ACH_DATEyearmon, transition_length = 1, state_length = 50) +
  view_follow(fixed_x=TRUE) +
  ease_aes('linear')
baz
````

![Imgur](https://i.imgur.com/S1n3KWV.gif)

However if I insert the code for the `geom_vline` layer into the plot:

````
baz<- df1 %>% 
  ggplot(aes(y=NAME, x=DIAG_RATE_65_PLUS)) +
  geom_barh(stat = "identity", alpha = 0.66) +
  labs(title='{closest_state}') +
  theme(plot.title = element_text(hjust = 1, size = 22)) +
  geom_vline(xintercept=(2/3)*100, linetype = "dotdash") + #geom_vline is incompatible.. but geom_hline works, but it's not useful for the plot
  transition_states(ACH_DATEyearmon, transition_length = 1, state_length = 50) +
  view_follow(fixed_x=TRUE) +
  ease_aes('linear')
baz
````

I get the error:

````Error in if (zero_range(from) || zero_range(to)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
2: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
`````

Which interpreting is beyond my programming knowledge.

Unusually, using `geom_hline` works:

````  
geom_hline(yintercept=(2/3)*100, linetype = "dotdash") +
 ````

But for my plot, it's not helpful as it puts a line somewhere perpendicular to the y-axis.

If I ran the above code without the animation layers, then `geom_vline` works, so I think this might be a compatibility issue.

![Imgur](https://i.imgur.com/V4e3CqR.png)

**Comment by takk1n** [comment]
Hello,

I am currently trying to do such graph and I am stucked on the transition states funkction.  After inserting the code above I get an error that "could not find function "transition_states"". Could you please help me to write this function? I have years, proffesions and number of occupied spots.

I would really appreciate that.

Ingrida

**Comment by thomasp85** [comment]
@takk1n I'm pretty sure you haven't installed the latest version of gganimate

**Comment by thomasp85** [comment]
@VictorAres for your first case, you can remove the grey plot background by setting a fixed x-limit in the `coord_flip` call... `nudge_*` is not a stopgap but the proper solution...

Let me look into the vline issue

**Comment by thomasp85** [comment]
The vline issue has been fixed
