### ISSUE TITLE
pdf_animate

### ISSUE THREAD

**Issue by dpphat** [thomasp85/gganimate#195]
This looks amazing. Thanks so much for contributing it. If you don't mind my asking, can you point to how you were able to do it? I would like to see if I can munge something to get Shiny-type interactions in PDF. Thanks so much for all your contributions.
Dan Puddephatt

**Comment by thomasp85** [comment]
Animation in pdf is pretty bare bone and interactions are a no go, unfortunately. Pretty sure there is no way to get htmlwidgets to work in pdf

**Comment by dpphat** [comment]
Dang.
Thanks so much for your feedback, Thomas. Much appreciated.
