### ISSUE TITLE
Quosure/missing argument related problem with some transition_states and geoms

### ISSUE THREAD

**Issue by craddm** [thomasp85/gganimate#203]
I've been receiving the area `Error in is_quosure(e2): argument "e2" is missing, with no default` when trying to use transition_states with several geoms.

Handily, when trying to set up a reprex, I have exactly the same problem with the airquality example from the README.md 

``` r
library(ggplot2)
library(gganimate)
    
ggplot(airquality, aes(Day, Temp)) + 
    geom_line(size = 2, colour = 'steelblue') + 
    transition_states(Month, 4, 1) + 
    shadow_mark(size = 1, colour = 'grey')
#> Error in is_quosure(e2): argument "e2" is missing, with no default
```

<sup>Created on 2018-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

> - Session info -------------------------------------------------------------------------
>  setting  value                       
>  version  R version 3.5.1 (2018-07-02)
>  os       Windows >= 8 x64            
>  system   x86_64, mingw32             
>  ui       RStudio                     
>  language (EN)                        
>  collate  English_United Kingdom.1252 
>  ctype    English_United Kingdom.1252 
>  tz       Europe/London               
>  date     2018-10-26                  
> 
> - Packages -----------------------------------------------------------------------------
>  package     * version    date       lib source                              
>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                      
>  backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.0)                      
>  base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                      
>  bindr         0.1.1      2018-03-13 [1] CRAN (R 3.5.0)                      
>  bindrcpp      0.2.2      2018-03-29 [1] CRAN (R 3.5.0)                      
>  callr         3.0.0      2018-08-24 [1] CRAN (R 3.5.1)                      
>  cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.1)                      
>  clipr         0.4.1      2018-06-23 [1] CRAN (R 3.5.0)                      
>  colorspace    1.3-2      2016-12-14 [1] CRAN (R 3.5.0)                      
>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                      
>  debugme       1.1.0      2017-10-22 [1] CRAN (R 3.5.0)                      
>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                      
>  devtools      2.0.0      2018-10-19 [1] CRAN (R 3.5.1)                      
>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                      
>  dplyr         0.7.7      2018-10-16 [1] CRAN (R 3.5.1)                      
>  evaluate      0.12       2018-10-09 [1] CRAN (R 3.5.1)                      
>  farver        1.0        2018-09-17 [1] CRAN (R 3.5.1)                      
>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.1)                      
>  gganimate   * 0.9.9.9999 2018-10-26 [1] Github (thomasp85/gganimate@cc23618)
>  ggplot2     * 3.1.0      2018-10-25 [1] CRAN (R 3.5.1)                      
>  gifski        0.8.6      2018-09-28 [1] CRAN (R 3.5.1)                      
>  glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.0)                      
>  gtable        0.2.0      2016-02-26 [1] CRAN (R 3.5.0)                      
>  hms           0.4.2      2018-03-10 [1] CRAN (R 3.5.0)                      
>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                      
>  knitr         1.20       2018-02-20 [1] CRAN (R 3.5.0)                      
>  lazyeval      0.2.1      2017-10-29 [1] CRAN (R 3.5.0)                      
>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)                      
>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                      
>  munsell       0.5.0      2018-06-12 [1] CRAN (R 3.5.0)                      
>  pillar        1.3.0      2018-07-14 [1] CRAN (R 3.5.1)                      
>  pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.1)                      
>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                      
>  pkgload       1.0.1      2018-10-11 [1] CRAN (R 3.5.1)                      
>  plyr          1.8.4      2016-06-08 [1] CRAN (R 3.5.0)                      
>  png           0.1-7      2013-12-03 [1] CRAN (R 3.5.0)                      
>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                      
>  processx      3.2.0      2018-08-16 [1] CRAN (R 3.5.1)                      
>  progress      1.2.0      2018-06-14 [1] CRAN (R 3.5.0)                      
>  ps            1.2.0      2018-10-16 [1] CRAN (R 3.5.1)                      
>  purrr         0.2.5      2018-05-29 [1] CRAN (R 3.5.0)                      
>  R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.1)                      
>  Rcpp          0.12.19    2018-10-01 [1] CRAN (R 3.5.1)                      
>  remotes       2.0.1      2018-10-19 [1] CRAN (R 3.5.1)                      
>  reprex        0.2.1      2018-09-16 [1] CRAN (R 3.5.1)                      
>  rlang         0.3.0.1    2018-10-25 [1] CRAN (R 3.5.1)                      
>  rmarkdown     1.10       2018-06-11 [1] CRAN (R 3.5.0)                      
>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                      
>  rstudioapi    0.8        2018-10-02 [1] CRAN (R 3.5.1)                      
>  scales        1.0.0      2018-08-09 [1] CRAN (R 3.5.1)                      
>  sessioninfo   1.1.0      2018-09-25 [1] CRAN (R 3.5.1)                      
>  stringi       1.2.4      2018-07-20 [1] CRAN (R 3.5.1)                      
>  testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.1)                      
>  tibble        1.4.2      2018-01-22 [1] CRAN (R 3.5.0)                      
>  tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                      
>  tweenr        1.0.0      2018-09-27 [1] CRAN (R 3.5.1)                      
>  usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.1)                      
>  whisker       0.3-2      2013-04-28 [1] CRAN (R 3.5.0)                      
>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                      
>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)

**Comment by thomasp85** [comment]
I cannot reproduce this. Does it persist after updating all packages (`update.packages()`)

**Comment by jonocarroll** [comment]
Reinstalling `transformr` fixes this for me.
