### ISSUE TITLE
make gifski suggested rather than imports 

### ISSUE THREAD

**Issue by chapmandu2** [thomasp85/gganimate#205]
Is it possible to make the gifski package optional? Since it relies on the rust gifski package the install for this can be really hard depending on your environment.  For a start the install of rust itself is non standard, you can't use apt-get install rust (on linux).  The rust install, and installation of rust packages also doesn't play very nicely when you are behind a firewall.  I've spent half a day so far trying to get gifski installed from behind a firewall with certificate inspection and it's melting my mind.

**Comment by thomasp85** [comment]
yes, I have considered making all rendering engines optional and have a default renderer that simply looks for whatever is available...

**Comment by chapmandu2** [comment]
Got there in the end anyway, went home and used my home machine to make a docker image, then pulled the docker image onto my work laptop... Now the animation fun starts!

**Comment by thomasp85** [comment]
That sounds like a slightly less optimal installation procedure 😀
