### ISSUE TITLE
geom_polygon error - invalid 'times' argument

### ISSUE THREAD

**Issue by clintmckenna** [thomasp85/gganimate#206]
Hi, I am trying to animate a polygon displayed on x/y coordinates as a function of time (t). 

I get the following error:
Error in rep(seq_len(nrow(polygon)), splits + 1) : invalid 'times' argument

any thoughts? Thanks!

```r
>head(tempMouse)
  subject    x    y t
1       1 1007 -899 1
2       1 1007 -898 2
3       1 1007 -897 3
4       1 1005 -896 4
5       1 1005 -896 5
6       1 1004 -896 6
>
> tail(tempMouse)
     subject    x    y    t
5849       1 1046 -692 5849
5850       1 1046 -692 5850
5851       1 1046 -692 5851
5852       1 1046 -692 5852
5853       1 1046 -692 5853
5854       1 1046 -692 5854

> 
> ggplot(tempMouse, aes(x = x, y = y)) + 
>   geom_polygon(color = 'black', fill = NA) +
>   transition_time(t) +
>   ease_aes('linear') +
>   theme_bw()
>
>Error in rep(seq_len(nrow(polygon)), splits + 1) : 
> invalid 'times' argument
```

**Comment by thomasp85** [comment]
Can I get you to provide a reproducible example? I do not have access to your data, and showing head and tail does not allow me to replicate your code...

**Comment by thomasp85** [comment]
Closing as no reproducible example provided. Please reopen with a reprex if the problem persists

**Comment by xingyezn** [comment]
[test.zip](https://github.com/thomasp85/gganimate/files/3293342/test.zip)
I meet the same question, too.
Here are my data.
code:
![test](https://user-images.githubusercontent.com/37822579/59554066-7a56f700-8fd0-11e9-94f1-217659b08ff4.PNG)

library(xlsx)
library(gganimate)
library(rust)
library(gifski)
library(ggplot2)
max_time = 375
df = read.xlsx('test.xls',1,encoding = "UTF-8")[1:max_time,]
col_name = c('time','x','y','z')
names(df) = col_name
anim2 = ggplot(df,aes(time,x))+geom_line(linetype = 1) + transition_time(time) + scale_x_log10()+ theme_bw()
animate(anim2,fps = 5,  renderer = gifski_renderer(),nframes = 100)
Error in rep(seq_len(nrow(polygon)), splits + 1) : invalid 'times' argument
