### ISSUE TITLE
shadow_mark() leaves an odd shadow

### ISSUE THREAD

**Issue by McCartneyAC** [thomasp85/gganimate#208]
Here's the example at work: https://twitter.com/wouldeye125/status/1059969935387041792

In short, when using geom_line() with shadow_mark() and shadow_wake(), the two endpoints of the line are connected with a linear shadow that does not exist in the data. This only exists for the most recent shadow, then disappears. An odd bug--I'm not sure what to make of it. 

If you want to reproduce the example, let me know and I can produce the data. The code was:

```
dat %>% 
  group_by(variable) %>% 
  mutate(mark = row_number()) %>% 
  ungroup() %>% 
  filter(variable != "k") %>% 
  ggplot(aes(x = mark, y = value, color = variable)) + 
  geom_line(size = 1.5, alpha = 0.8) +
  labs(
    x = "Cluster Size" , 
    y = "Shrinkage Factor", 
    title = "Shrinkage factor for estimates by cluster size and ICC",
    subtitle = "{closest_state} "
  ) + 
  guides(color = FALSE) + 
  transition_states(variable, 
                    transition_length = 1,
                    state_length = 0.1) +
  ease_aes('linear') + 
  shadow_mark(color = "gray")
```

**Comment by thomasp85** [comment]
Thanks - that is indeed a bug and ill try to squash it

**Comment by thomasp85** [comment]
Can I get you to try to reproduce the bug and report back. I can't reproduce on current version of gganimate. If it still exist I'd like you to provide a reprex

**Comment by McCartneyAC** [comment]
couldn't reproduce the error after downloading the most recent version of the package! Thank you once again for everything!
