### ISSUE TITLE
transition_states() behaving different after update between geom_boxplot and geom_point

### ISSUE THREAD

**Issue by brentthorne** [thomasp85/gganimate#210]
Hello,

While I was working on water chemistry data I created an animation which used `transition_states()` to give a boxplot representing the measurements taken during each field sampling season. It worked well as all I had to do to was add a column with a shared single factor and the boxplot would not move on the x axis during the animation. 

**EDIT**  *I have now noticed that this is not an issue when using `geom_point` on this plot with the same `aes` values. I have updated the reproducible example to show this as it can also be seen in my original plots*

_**Here is what it looked like before I updated gganimate:**_ 

![file1e893eb01832](https://user-images.githubusercontent.com/15312739/48209359-ed193900-e342-11e8-987b-318b91ccf085.gif)

Since updating to the most recent gganimate (v 0.9.9.9999) I now get a different result where the boxplot moves along the x axis as if it is going from group to group.

_**What it looks like now with no changes to the code**_

![broken](https://user-images.githubusercontent.com/15312739/48214437-ee039800-e34d-11e8-80bf-0f5091582bbe.gif)

# Reproducible Example

Here is a reproducible example with a much smaller data set but replicates my issue:

```r
library(tidyverse)
library(gganimate)

# reproducible example
mytibble <- tibble(ID = factor(rep_len(LETTERS[1:5],15)),
                   Sample_Period = factor(rep(1:3, times=1, each=5)),
                   Stat_1 = runif(n = 15, min = 1, max = 10),
                   Stat_2 = runif(n = 15, min = 10, max = 20),
                   Stat_3 = runif(n = 15, min = 2, max = 14))

# tidy for ggplot
mytibble_tidy <- mytibble %>% 
  gather("Stat_ID","Value",Stat_1:Stat_3) %>% 
  mutate(boxplot_xval = factor("A")) %>% 
  arrange(Sample_Period)

# static boxplot
p <- ggplot(data = mytibble_tidy, aes(x = boxplot_xval, y = Value)) +
  geom_boxplot() +
  geom_point(data = mytibble_tidy[mytibble_tidy$ID == "A",], aes(x = boxplot_xval, y = Value, colour = ID))+
  facet_wrap(~Stat_ID, scales = "free_y") +
  NULL

# gganimate
p_animate <- p +
  transition_states(states = Sample_Period, transition_length = 2, state_length = 1) +
  enter_grow() +
  exit_shrink() +
  ease_aes('sine-in-out')+
  labs(x = "Sample Period: {closest_state}") +
  NULL

animate(p_animate, width = 500, height = 300)
```

_**Which produces this:**_

![broken](https://user-images.githubusercontent.com/15312739/48215249-d9c09a80-e34f-11e8-9cd3-e33bc75657c2.gif)

 
I am still trying to find time to learn more about gganimate as I love the potential for sharing my work in new and engaging ways like this, so if this is an obvious fix my apologies for that.

Thanks!

**Comment by thomasp85** [comment]
Fixed in b93687d
