### ISSUE TITLE
Save mp4 animation file

### ISSUE THREAD

**Issue by neuwirthe** [thomasp85/gganimate#211]
With output option 

`self_contained: false
`
one can get the gif file with the animation.

I could not find a way to save the animation as mp4, neither with
`ffmpeg_renderer() `nor with `av_renderer()`

Can it be done?

**Comment by thomasp85** [comment]
Not currently. I’ll have to look into whether it is possible at all. @yihui the current approach to embedding video is to have a `knitr_print` method that byte-encode it and writes it into the output. Is there a Preferred way to handle a situation such as the above?

**Comment by neuwirthe** [comment]
The old version of gganimate hat a `file=` parameter which did exactly what I need.

**Comment by thomasp85** [comment]
You can always write a file using either `animate()` directly or `anim_save()`

**Comment by neuwirthe** [comment]
Sorry, I had somehow missed this.
