### ISSUE TITLE
animate in Rmarkdown not honoring fig,width

### ISSUE THREAD

**Issue by neuwirthe** [thomasp85/gganimate#212]
`animate` used in an Rmd file in RStudio does not seem to honor the fid.width chunk parameter.   
The following two animations should habe different width, but they don't.    
Please add the missing triple backquotes at the end of the chunks.

```

```{r}
p1 <- ggplot(airquality, aes(Day, Temp, group = Month)) +
  geom_line() +
  transition_reveal(Month, Day)
animate(p)
 ```

```{r, fig.with=2}
```{r, fig.with=2}
p2 <- ggplot(airquality, aes(Day, Temp, group = Month)) +
  geom_line() +
  transition_reveal(Month, Day)
animate(p2)
```

**Comment by thomasp85** [comment]
`animate` does not because it assumes that you want to take control. On the other hand, if you simply print the object, as you would a regular plot, the chunk options should get picked up:


    ```{r, fig.with=2}
    p2 <- ggplot(airquality, aes(Day, Temp, group = Month)) +
      geom_line() +
      transition_reveal(Month, Day)
    p2
    ```

**Comment by neuwirthe** [comment]
OK, gifski_renderer has width and height, but the video renderers (av_renderer and ffmpeg_renderer) don't. Can the video size be controlled?

**Comment by thomasp85** [comment]
Is this still related to setting chunk options?

In general, you define the output size using `width` and `height` in `animate()` - some renderers has the option of resizing the final output but all will default to using the device size...

**Comment by neuwirthe** [comment]
No, this time I was referring to the parameters in the call for the renderer.
Currently, I see no way of controlling the size of mp4 files produced by the renderer.

**Comment by thomasp85** [comment]
you don't control it in the renderer - you control it in the `animate()` call. The purpose of the renderers is simply to get a list of image frames and combine them - at that point the dimensions have already been set

**Comment by neuwirthe** [comment]
My misunderstanding was cause by the fact that `gifski_renderer` explicitly has `width` and `height` parameters, but the other renderers don't. These parameters are less explicitly mentioned for the "surrounding" `animate`. If I understand correctly, the "inner" parameters in `gifski_renderer`are not necessary since thee values can be set in the "outer" call to `animate`.

**Comment by thomasp85** [comment]
The parameters in the gifski tenderer exists because gifski allows resizing of the final output — if not set, no resizing will happen and the size will match the dimensions of the graphic device
