### ISSUE TITLE
support for geom_sf() seems broken

### ISSUE THREAD

**Issue by clauswilke** [thomasp85/gganimate#213]
I tried to make an animation using `geom_sf()` and I couldn't find any transition type that worked. The [example on the wiki is broken for me,](https://github.com/thomasp85/gganimate/wiki/Moving-Hawaii-and-Alaksa) and the following simple example also doesn't work. There was some amount of refactoring of `geom_sf()` from ggplot2 3.0.0 to 3.1.0, so maybe that's the problem. I didn't test with 3.0.0.

``` r
library(ggplot2)
library(gganimate)
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)

# static works
ggplot(nc) + geom_sf() + stat_sf_coordinates()
```

![](https://i.imgur.com/sRrREQz.png)

``` r

# animated works without geom_sf()
ggplot(nc) + stat_sf_coordinates() +
  transition_time(as.numeric(FIPS))
```
![example](https://user-images.githubusercontent.com/4210929/48582880-5a9d0a80-e8eb-11e8-9a2b-196826b4e58e.gif)

``` r
# doesn't work
ggplot(nc) + geom_sf() + stat_sf_coordinates() + 
  transition_time(as.numeric(FIPS))
#> Error in (function (from, to, enter, exit, min_n, closed = TRUE) : unused arguments (new_id = dots[[3]][[1]], id = "id")
```

<sup>Created on 2018-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
Have you updated `transformr` ?

**Comment by clauswilke** [comment]
That fixed it, thanks!
