### ISSUE TITLE
problems installing gganimate in Rstudio for Mac

### ISSUE THREAD

**Issue by enricadds** [thomasp85/gganimate#215]
Dear community,

I am a beginner in R, I can handle dplyr and ggplot but now I want to run gganimate. However I get the following error when trying installing it with devtools:

> Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/8t/gjtsc4ks0glbnzjywhsjp9sw0000gn/T//Rtmp1F0XIv/file2185bff20df/gganimate_0.9.9.9999.tar.gz' had non-zero exit status

could you please help me?

I have installed the R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

and using it with Rstudio.

enrica

**Comment by franziloew** [comment]
I have the same error when I run 

`devtools::install_github('thomasp85/gganimate')`

my full output:

![image](https://user-images.githubusercontent.com/26768699/49070741-affee300-f22c-11e8-8e49-29ba62c26eb4.png)


and my output of `R.version`:

![image](https://user-images.githubusercontent.com/26768699/49070768-bc833b80-f22c-11e8-93b3-5ae6365cd7c6.png)

**Comment by thomasp85** [comment]
This is a well known issue and not really related to gganimate. try updating both R and Rstudio

**Comment by franziloew** [comment]
perfect, thank you. that worked
