### ISSUE TITLE
wiki example is no longer reproducible

### ISSUE THREAD

**Issue by dariyasydykova** [thomasp85/gganimate#217]
Hello,

I was using the example given in https://github.com/thomasp85/gganimate/wiki/Animation-Composition for an animation. 

Currently, if you run the code given in that example, this is the animation it produces:
![wiki_example](https://user-images.githubusercontent.com/4268318/48713279-7e0ad280-ebd5-11e8-9999-209ce9bfd16a.gif)

There seem to be two issues with this animation and it's code. (1) The bars, points, and the error bars do not move in sync. (2) When you run `new_gif[50]`, it produces this image:
![delta_image](https://user-images.githubusercontent.com/4268318/48714381-3e91b580-ebd8-11e8-85e5-b5e69926f680.png).
It doesn't seem to be an issue in the animation I generated above. When I used this code to generate my own animation, I got a ghosting effect from the delta frames. By "ghosting effect" I mean that the movement of a line would leave a trace. The way I resolved this issue was by using `file_renderer()`. This is how it would look for the wiki example code
`a_gif <- animate(a, device = "png", width = 240, height = 240, renderer = file_renderer("./gganim", prefix = "a", overwrite = TRUE))
b_gif <- animate(b, device = "png", width = 240, height = 240, renderer = file_renderer("./gganim", prefix = "b", overwrite = TRUE))
`

Could you update the code in the wiki example? I will look into the first issue and try to resolve it.

**Comment by ptoche** [comment]
I don't have this problem. Can you check if the problem persists and if it doesn't close the issue? I'm using gganimate **version 0.9.9.9999** (assuming that's a real number).

**Comment by dariyasydykova** [comment]
I am also using gganimate version 0.9.9.9999. I reran the code in the example, and I still get the same animation shown above.

**Comment by ptoche** [comment]
My guess is that the issue is related to ``imagemagick``, rather than ``gganimate``. 

My version is not quite the latest. Which version do you have?  Maybe install again from: https://www.imagemagick.org/script/download.php

This is what I have. Type the following in the terminal. 

    $ convert -version
    Version: ImageMagick 7.0.7-8 Q16 x86_64 2017-10-24 http://www.imagemagick.org
    Copyright: © 1999-2017 ImageMagick Studio LLC
    License: http://www.imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules
    Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib

**Comment by thomasp85** [comment]
That shouldn't matter - `gganimate` doesn't use ImageMagick, so unless you have installed `magick` from source (and is using `magicking_renderer()`) the version on your system does not have any effect...

**Comment by thomasp85** [comment]
FWIW, this is related to an overall problem with how to handle position adjustments... I mad a fix for stacked area charts, which ended up breaking anything else so it had to be rolled back - this is likely the cause for the different output...

**Comment by dariyasydykova** [comment]
I don't remember how I installed `magick`, but most likely it was done with `install.packages("magick")`.

**Comment by thomasp85** [comment]
@dariyasydykova I cannot reproduce right now so my guess is that you happened to install gganimate at the time of my faulty position_stack fix... It has nothing to do with `magick` and updating gganimate should resolve the issue
