### ISSUE TITLE
Issue with emojifont 

### ISSUE THREAD

**Issue by SaskiaFreytag** [thomasp85/gganimate#219]
Is it correct that the emojifont isn't supported by gganimate?

Because in the underneath example the static plot can render the emojifont but the
animated plot cannot. The following error message appears:

_no font could be found for family "EmojiOne"no font could be found for family "EmojiOne"_

```{r}
library(gganimate)
library(emojifont)
library(okcupiddata)

profiles <- profiles %>% mutate(emoji= case_when(
  sex=="f" ~"\U0001f468",
  sex=="m" ~"\U0001f469"
))

load.emojifont("EmojiOne.ttf")
quartz()
ani_plot <- ggplot(profiles, aes(x = emoji)) + geom_bar(aes(fill=smokes)) +
  theme(text=element_text(family = "EmojiOne", size=80))
ani_plot
ani_plot + transition_manual(status) + labs(title="{current_frame}")
```

**Comment by thomasp85** [comment]
can you plot the static version successfully to the `png()` device

**Comment by SaskiaFreytag** [comment]
Hmm it keeps aborting RStudio when I try this.

**Comment by thomasp85** [comment]
I think this might be a problem between Rstudio and emojifont..? Can't get the static plot to work in the RStudio device as well...

Try to see if you can get it to work outside of rstudio

**Comment by SaskiaFreytag** [comment]
Sorry I did something stupid when I tried the first time around. It does work in both RStudio and outside of RStudio. 
![hallo](https://user-images.githubusercontent.com/9170680/49770017-a9955e80-fd36-11e8-991f-6189158718ae.png)

**Comment by thomasp85** [comment]
The problem seems to be that showtext/emojifont does not get installed in a way that allow grid to query the dimensions of the text... @pmur002, do you know why this is?

the error is:
```r
#> Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
#>  polygon edge not found
```

when calling `convertHeight()` on a textgrob using EmojiOne font...

**Comment by thomasp85** [comment]
digging more into it it may be more of a showtext issue... @yixuan can you see why drawing with grid from inside gganimate is causing trouble? grid is not picking up the EmojiOne font for some reason (though it works when plotting a single plot with ggplot2)

The relevant plotting code is here: https://github.com/thomasp85/gganimate/blob/378955811d806bcb6e41ebbf5d2a93adb606476f/R/scene.R#L121-L141

**Comment by pmur002** [comment]
Just some thoughts to throw into the mix (could not get the example code at the top to run - missing package requirement?) ...

(I think) 'showtext' works by modifying the graphics device itself (to replace the text-drawing functions). This (rather invasive) technique means that anything that is playing with graphics devices (e.g., switching between them, opening and closing multiple devices) is vulnerable to things not working (or worse).

'emojifont' acknowledges this sort of problem with respect to R Studio- see [](https://cran.rstudio.com/web/packages/emojifont/vignettes/emojifont.html#limitation), which plays some games with graphics devices.

So if 'gganimate' is doing something like .. open device, draw, close device ... then that could be something that causes problems in combination with 'showtext' (or any derivative of it).  It may be the case, for example, that begin.showtext() needs to be called for each device as it is opened.

Just some thoughts.

**Comment by yixuan** [comment]
I agree with Paul on the explanation above. What I had in mind when I wrote showtext was a single graphics device, so there might be some bugs dealing with multiple devices.

When I have some time in the holiday I can take a look at the issue, though I am not sure whether it is fixable in general situations.

**Comment by thomasp85** [comment]
Thanks, both... I'll leave this open, even though I don't think there is much to do from the gganimate side of things. I'm not going to add showtext as a dependency so if it should get fixed it will probably be in how showtext inserts itself into the drawing pipeline...

**Comment by yixuan** [comment]
I was experimenting a little bit, but couldn't run the example at the top to produce the picture in the 5th comment. Could someone give me a minimal example to reproduce the error message?

**Comment by SaskiaFreytag** [comment]
I forgot `library(dplyr)`. I hope this helps.

**Comment by yixuan** [comment]
Now I have some preliminary results: I feel there is something wrong with the EmojiOne font packed in the `emojifont` package. When I ran the following code,
```r
library(gganimate)
library(emojifont)
library(okcupiddata)
library(dplyr)

profiles = profiles %>% mutate(emoji = case_when(
    sex=="f" ~"\U0001f468",
    sex=="m" ~"\U0001f469"
))

load.emojifont("EmojiOne.ttf")

static_plot = ggplot(profiles, aes(x = emoji)) + geom_bar(aes(fill = smokes)) +
    theme(text = element_text(family = "EmojiOne", size = 20))

x11()
print(static_plot)
```
I got a picture with no text:

![1](https://user-images.githubusercontent.com/216398/49965675-dd65b500-feeb-11e8-9c4c-a33a43aebd41.png)

However, if I change to OpenSansEmoji, everything is fine:
```r
load.emojifont("OpenSansEmoji.ttf")

static_plot = ggplot(profiles, aes(x = emoji)) + geom_bar(aes(fill = smokes)) +
    theme(text = element_text(family = "OpenSansEmoji", size = 20))

x11()
print(static_plot)
```

![2](https://user-images.githubusercontent.com/216398/49965698-e9ea0d80-feeb-11e8-9196-432053823479.png)

The `gganimate` code also works for me:
```r
ani_plot = static_plot + transition_manual(status) + labs(title = "{current_frame}")
animate(ani_plot, renderer = file_renderer())
```
![gganim_plot0001](https://user-images.githubusercontent.com/216398/49965789-2d447c00-feec-11e8-86d0-c4adfb2dfb25.png)
![gganim_plot0002](https://user-images.githubusercontent.com/216398/49965793-30d80300-feec-11e8-8a4c-19341851f62e.png)

In any way, I would suggest restricting the Emoji fonts to axis labels only:

```r
static_plot = ggplot(profiles, aes(x = emoji)) + geom_bar(aes(fill = smokes)) +
    theme_grey(base_family = "sans") +
    theme(axis.text.x = element_text(family = "EmojiOne", size = 30))
ani_plot = static_plot + transition_manual(status) + labs(title = "{current_frame}")
animate(ani_plot, renderer = file_renderer())
```

Can you try the code again?

**Comment by SaskiaFreytag** [comment]
Weird I still get the ploygon grid error message when I try your code.

**Comment by thomasp85** [comment]
Closing this - if you want emojis in animations then using `'ragg_png'` as the device is the way to go
