### ISSUE TITLE
`keep` option in `transition_filter`

### ISSUE THREAD

**Issue by annaquaglieri16** [thomasp85/gganimate#220]
Hi Thomas, 

I was trying to understand what is the difference between `keep = TRUE` or `keep = FALSE` in section `Let's investigate the keep argument`  in here https://github.com/ropenscilabs/learngganimate/blob/master/transition_filter.md#lets-investigate-the-keep-argument. 

This example should work

```{r}
mydf <- mtcars
p1=ggplot(mydf, aes(x = hp, y = mpg)) +
geom_point()

g <- p1 + transition_filter(transition_length = 10, 
                            filter_length = 0.2, 
                            wrap = TRUE, 
                            keep = TRUE,
                            qsec < 14,qsec > 16,qsec > 20) + 
  labs(title = "closest expression : {closest_expression}, \n transitioning : {transitioning}, \n closest_filter : {closest_filter}")

animate(g, nframes = 10, fps = 2)
```

When using `keep = TRUE` it looks like we cannot understand what's being filtered and what's stably there. Is there a way to change colour? or do something to preserve what shouldn't be filtered but shows what it is changing?

Thanks!!

**Comment by thomasp85** [comment]
unless you provide an exit functions then `keep` will be nonsensical. If you do provide an exit function that does not result in disappearance of the element, then setting `keep=TRUE` will allow the exited state to continue to be present in the animation. Example:

``` r
library(gganimate)
#> Loading required package: ggplot2
# keep == TRUE
ggplot(iris) + 
  geom_point(aes(Petal.Length, Petal.Width, colour = Species), size = 4) + 
  transition_filter(2, 1, Petal.Width > 1.5, Petal.Length < 4, Species == 'setosa', keep = TRUE) + 
  exit_manual(function(x) dplyr::mutate(x, colour= 'grey', size = 1))
```

![](https://i.imgur.com/mbd9bT8.gif)

``` r
# keep == FALSE
ggplot(iris) + 
  geom_point(aes(Petal.Length, Petal.Width, colour = Species), size = 4) + 
  transition_filter(2, 1, Petal.Width > 1.5, Petal.Length < 4, Species == 'setosa', keep = FALSE) + 
  exit_manual(function(x) dplyr::mutate(x, colour= 'grey', size = 1))
```

![](https://i.imgur.com/RviOicW.gif)

<sup>Created on 2018-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by annaquaglieri16** [comment]
Thank you so much @thomasp85 ! That makes perfect sense and wow, I didn't know you can mutate a ggplot object!

I added this to the transition_filter.md .

**Comment by thomasp85** [comment]
Well, you can't really `mutate` a ggplot object. The enter/exit functions receives the data related to elements entering and exiting the animations so they are purely working with data frames
