### ISSUE TITLE
unable to animate concurrent transition_time events with group variable

### ISSUE THREAD

**Issue by btosimongillings** [thomasp85/gganimate#222]
I am trying to plot traces of individuals moving using the following code. This works fine if the two individuals do not move at the same time. 

`
#create data - two tracks non-overlapping in time
events_no_overlap <- data.frame(stringsAsFactors=FALSE,
                     ID = c(1, 1, 2, 2),
                     Event = c("Start", "End", "Start", "End"),
                     Date = c(1, 5, 6, 10),
                     Lon = c(20.19, -3.94, 10.4, 0.68),
                     Lat = c(68.76, 56.11, 53.9, 52.4)
)
events_no_overlap $ID <- as.factor(events_no_overlap $ID)

#generate plot
gtracks1 <- ggplot(data = events_no_overlap, aes(x = Lon, y = Lat, col = ID, group = ID)) + 
  geom_point(size = 5, alpha = 0.8) +
  transition_time(Date) +
  labs(title = paste("Day:", "{round(frame_time, 0)}")) +
  shadow_wake(wake_length = 0.5)
animate(gtracks1)
`

But if the tracks move concurrently the transition does not work, with just the four individual points appearing in sequence with no tweening, fading etc. I have tried sorting by Date but this has no effect.
`
#create data - two tracks overlapping in time
events_overlap <- data.frame(stringsAsFactors=FALSE,
                                ID = c(1, 1, 2, 2),
                                Event = c("Start", "End", "Start", "End"),
                                Date = c(1, 7, 3, 10),
                                Lon = c(20.19, -3.94, 10.4, 0.68),
                                Lat = c(68.76, 56.11, 53.9, 52.4)
)
events_overlap $ID <- as.factor(events_overlap $ID)

#generate plot
gtracks2 <- ggplot(data = events_overlap, aes(x = Lon, y = Lat, col = ID, group = ID)) + 
  geom_point(size = 5, alpha = 0.8) +
  transition_time(Date) +
  labs(title = paste("Day:", "{round(frame_time, 0)}")) +
  shadow_wake(wake_length = 0.5)
animate(gtracks2)
`

**Comment by ptoche** [comment]
**Reprex for Example 1:**

``` r
    library(reprex)
    library(ggplot2)
    library(gganimate)

    # create data - two tracks non-overlapping in time
    events_no_overlap <- data.frame(stringsAsFactors=FALSE,
        ID = c(1, 1, 2, 2),
        Event = c("Start", "End", "Start", "End"),
        Date = c(1, 5, 6, 10),
        Lon = c(20.19, -3.94, 10.4, 0.68),
        Lat = c(68.76, 56.11, 53.9, 52.4))
    events_no_overlap$ID <- as.factor(events_no_overlap$ID)

    # animation
    gtracks1 <- ggplot(data = events_no_overlap, 
        aes(x = Lon, y = Lat, col = ID, group = ID)) +
        geom_point(size = 5, alpha = 0.8) +
        transition_time(Date) +
        labs(title = paste("Day:", "{round(frame_time, 0)}")) +
        shadow_wake(wake_length = 0.5)
    animate(gtracks1)
```

![](https://i.imgur.com/D13dW81.gif)

Created on 2018-11-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ptoche** [comment]
**Reprex for Example 2:**

``` r
    library(reprex)
    library(ggplot2)
    library(gganimate)

    # create data - two tracks overlapping in time
    events_overlap <- data.frame(stringsAsFactors=FALSE,
        ID = c(1, 1, 2, 2),
        Event = c("Start", "End", "Start", "End"),
        Date = c(1, 7, 3, 10),
        Lon = c(20.19, -3.94, 10.4, 0.68),
        Lat = c(68.76, 56.11, 53.9, 52.4))
    events_overlap $ID <- as.factor(events_overlap $ID)

    # generate plot
    gtracks2 <- ggplot(data = events_overlap, 
        aes(x = Lon, y = Lat, col = ID, group = ID)) +
        geom_point(size = 5, alpha = 0.8) +
        transition_time(Date) +
        labs(title = paste("Day:", "{round(frame_time, 0)}")) +
        shadow_wake(wake_length = 0.5)
    animate(gtracks2)
```

![](https://i.imgur.com/YELlN71.gif)

Created on 2018-11-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
This is because you are inadvertently misusing `transition_time()` here (probably due to still spotty documentation).

`transition_time` is like `transition_state` for a continuous  transition variable. This means that each unique timepoint should have representatives for all the data points that should "carry on" in the animation. In your case there are 4 unique times: 1, 3, 7, and 10. In 1 point 1 is present. Then at 3 only point 2 is present meaning point 1 disappear and point 2 appear. The reverse then happens at 7, and then again at 10... In order to achieve what you want you need `transition_components` instead which allows each graphic element to animate through its own time series:

```r
ggplot(data = events_overlap, 
    aes(x = Lon, y = Lat, col = ID, group = ID)) +
    geom_point(size = 5, alpha = 0.8) +
    transition_components(Date) +
    labs(title = paste("Day:", "{round(frame_time, 0)}")) +
    shadow_wake(wake_length = 0.5)
```
![transition_components](https://user-images.githubusercontent.com/1775316/49732115-cc177100-fc7d-11e8-8d55-e615a8acb329.gif)
