### ISSUE TITLE
Unable to install from ZIP

### ISSUE THREAD

**Issue by dlpate2525** [thomasp85/gganimate#223]
I am trying to download the package for installation via Rstudio and a ZIP file. When I try to call the library "gganimate" after installing the gganimate master package the commands are not working. 

Is there someone who can assist? Connecting directly to github is not an option behind our corporate firewall.

**Comment by thomasp85** [comment]
Can you provide some code samples and the errors you receive? Without that it is quite difficult to help you troubleshoot

**Comment by dlpate2525** [comment]
Sure

After installing the package via the zip file, I try to load the library "gganimate" or "gganimate-master" with an error message. 

> install.packages("/gganimate-master.zip", repos = NULL, type = "win.binary")
> library("gganimate-master")
Error in library("gganimate-master") : 
  there is no package called ‘gganimate-master’
> library("gganimate")
Error in library("gganimate") : there is no package called ‘gganimate’

**Comment by thomasp85** [comment]
how did you come by the zip file? from GitHub? In that case it is not a binary, but a source package that you must unzip and install from source...

**Comment by dlpate2525** [comment]
Could you provide a code sample? The file was a direct download for this github repository and installing from the zip location. 

Ultimately any method that allows me to install from a downloaded file should work...

**Comment by ginolhac** [comment]
once downloaded, unzip the archive and do

`remotes::install_local("/path/to/unzip/gganimate-master/")`

**Comment by dlpate2525** [comment]
@ginolhac perfect that worked for me!

@thomasp85 thanks for responding, you have a great package here
