### ISSUE TITLE
Error in file(what, "rb") : cannot open the connection

### ISSUE THREAD

**Issue by graydenshand** [thomasp85/gganimate#228]
I have been unable to reproduce even the most trivial of examples.

```
library(ggplot2)
library(gganimate)

ggplot(mtcars) + 
  geom_boxplot(aes(factor(cyl), mpg)) + 
  transition_manual(gear)
```

Produces the following Traceback:
```
Error in file(what, "rb") : cannot open the connection
11. file(what, "rb")

10. base64enc::base64encode(x)

9. paste0("<video controls autoplay><source src=\"data:video/", format, ";base64,", base64enc::base64encode(x), "\" type=\"video/mp4\"></video>")

8.  htmltools::HTML(paste0("<video controls autoplay><source src=\"data:video/", format, ";base64,", base64enc::base64encode(x), "\" type=\"video/mp4\"></video>"))

7.  as_html_video(x)

6. htmltools::browsable(as_html_video(x))

5. print(htmltools::browsable(as_html_video(x)))

4.  print.video_file(anim, info = FALSE)

3.  print(anim, info = FALSE)

2. print.gganim(x)

1.  function (x, ...) UseMethod("print")(x)

```

I've tried reinstalling gganimate, R, R-Studio,  imagemagick, etc..

I haven't found this error anywhere else.

**Comment by thomasp85** [comment]
Maybe related to #201 ? Are you on windows10?

Anyway if you install gifski or magick you should be fine until it is fixed

**Comment by graydenshand** [comment]
Hi Thomas,
Thank you for your help, that solution worked - I just had to restart my R session after installing the packages. I'm not sure if this is related to #201. However, I am running macOS - details below. 

R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.6

High hopes for this package!
Thanks for all your work :) 



--EDIT--
I'm curious... If gifski is the primary rendering engine, it might save others this problem if it gets installed with gganimate as a dependency?
