### ISSUE TITLE
gganimate error

### ISSUE THREAD

**Issue by ercan1** [thomasp85/gganimate#229]
Hi all,

When I run the code provided by Thomas, I get the following message in R Studio.

**Error in file(what, "rb") : cannot open the connection                                                                                                                         
In addition: Warning message:
In file(what, "rb") :
  cannot open file 'C:\Users\Ercan\AppData\Local\Temp\Rtmp0crfbS\file1edc3a121630.mp4': No such file or directory**

Is there a way to solve this problem?
thnx

**Comment by ercan1** [comment]
I ran the following code:

devtools::install_github('thomasp85/gganimate')

**Comment by mghozyah** [comment]
I got the same issue, 

```
**Error in file(what, "rb") : cannot open the connection                        
In addition: Warning message:
In file(what, "rb") :
  cannot open file 'C:\Users\GhozyH\AppData\Local\Temp\RtmpSqRbvf\file6605ae94acb.mp4': No such file or directory**
```

**Comment by thomasp85** [comment]
Can I get you to reinstall and try again - it should be fixed now (hopefully)

**Comment by mghozyah** [comment]
thank you, it works.

**Comment by ercan1** [comment]
thnx. it works:) I have another question though. I used your temperature code to animate gapminder data. Somehow I cannot display all dates on the x axis using scale_x_date(limits = NA). It gives me the following error message:

**Error: Invalid input: date_trans works with objects of class Date only**

I am basically trying to display the min and max dates (i.e. years) in the dataset with 3 year intervals so that all the dates can fit the axis.

thnx

Ercan

**Comment by thomasp85** [comment]
Can I get you to open a new issue for this
