### ISSUE TITLE
expanding plot area

### ISSUE THREAD

**Issue by ercan1** [thomasp85/gganimate#230]
Hi,

I am trying to expand the plot area to the right on the x axis in your Temperature code. Theme plot.margin squeezes the plot area from the right hand side. Instead of this, is there a way to expand the plot area to teh right so that the moving texts in my code are not truncated as they spill over the plot area?

thnx much.

**Comment by thomasp85** [comment]
This is more of a ggplot2 question but try expanding the x-scale in `coord_cartesian()`
