### ISSUE TITLE
could not find function "gganimate"

### ISSUE THREAD

**Issue by malouche** [thomasp85/gganimate#231]
Why when my R can't find gganimate? 

> library(gganimate)
> animation::ani.options(ani.width = 750, ani.height = 450)
> gganimate(map, interval = .2)
Error in gganimate(map, interval = 0.2) : 
  could not find function "gganimate"

**Comment by thomasp85** [comment]
See the last point in the readme... The old API has been deprecated and will no longer be supported

**Comment by DanielleQuinn** [comment]
@thomasp85 Could you point me toward where / how I can update my code to the new API?

**Comment by thomasp85** [comment]
There is not a one-to-one mapping between the two APIs, so it is not going to be possible to provide a step-by-step guide. In general, using `transition_manual` will allow you to replicate most of the behaviour you have from the old API... A good place to start learning about the new API is in the wiki on this repository or at https://github.com/ropenscilabs/learngganimate

**Comment by DanielleQuinn** [comment]
Thank you!

**Comment by malouche** [comment]
Thank you!
=======================
Dhafer malouche
Professor of Statistics
Ecole Supérieure de la Statistique et de l’Analyse de l’Information
University of Carthage
Website: dhafermalouche.net<http://dhafermalouche.net>

On Dec 10, 2018, at 8:28 PM, Thomas Lin Pedersen <notifications@github.com<mailto:notifications@github.com>> wrote:


See the last point in the readme... The old API has been deprecated and will no longer be supported
