### ISSUE TITLE
Error in transition_manual(turn) :  could not find function "transition_manual"

### ISSUE THREAD

**Issue by RYucel** [thomasp85/gganimate#232]
I am getting this error while trying to replicating this link example [http://varianceexplained.org/r/knight-chess/](url) installed packages are ggplot2, tidyr, dplyr. How to fix this?

**Comment by ptoche** [comment]
Update to the latest ``gganimate`` and make a ``reprex`` if problems persist.

    library(reprex)
    # full code here including packages, data, etc.

then run ``reprex()`` to copy the code and paste here. Can take a while to render.

**Comment by RYucel** [comment]
![image](https://user-images.githubusercontent.com/24809488/49785885-a4caad80-fd2a-11e8-967a-ff4ac5d5b168.png)

**Comment by thomasp85** [comment]
This is a screenshot... (and does not include the error). running `reprex()` will but some text on your clipboard that you can then paste into a comment...

But based on your error message the problem is likely that you either haven't loaded gganimate (`library(gganimate)`) or haven't updated it to the latest version (`devtools::install_github('thomasp85/gganimate')`)

**Comment by RYucel** [comment]
![rplot01](https://user-images.githubusercontent.com/24809488/49786284-ed369b00-fd2b-11e8-9e54-5e4c8d4ddbfe.png)
(Actually I couldnt save it full resolution via "copy to clipboard" in R plot export menu). But it looks like on export menu, animation works, but in console it shows error and not animate it on output window

**Comment by thomasp85** [comment]
You still shouldn't rely on any manual copy-paste from Rstudio... reprex takes care of all this for you

I cannot help you if you do not provide the error that you get...

**Comment by RYucel** [comment]
``` r
library(reprex)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)

# Random number between 1 and 2
move_x <- sample(2, 1)

# If x is 2, y is 1, and vice versa
move_y <- 3 - move_x
c(move_x, move_y)
#> [1] 1 2

# How about letting either number be negative?
move_x <- sample(2, 1) * sample(c(1, -1), 1)
move_y <- (3 - abs(move_x)) * sample(c(1, -1), 1)
c(move_x, move_y)
#> [1]  1 -2

# Now that we can sample a single move, we can try sampling many moves (say, 20)
move_x <- sample(2, 20, replace = TRUE) * sample(c(1, -1), 20, replace = TRUE)
move_y <- (3 - abs(move_x)) * sample(c(1, -1), 20, replace = TRUE)

move_x
#>  [1]  1 -2  1 -1 -2 -2  2  1 -2 -1  1 -2  1  1 -2 -1 -1  2  1 -2
move_y
#>  [1]  2 -1 -2 -2  1  1 -1  2 -1 -2 -2 -1 -2  2 -1 -2  2  1 -2 -1

# The crossing() function from tidyr is wonderful for setting up Monte Carlo simulations.
# It creates a tbl_df with every combination of the inputs (it's similar to the built-in expand.grid).
crossing(trial = 1:3,
         turn = 1:3)
#> # A tibble: 9 x 2
#>   trial  turn
#>   <int> <int>
#> 1     1     1
#> 2     1     2
#> 3     1     3
#> 4     2     1
#> 5     2     2
#> 6     2     3
#> 7     3     1
#> 8     3     2
#> 9     3     3

# In this experiment, we'll simulate 100,000 trials (and, as the riddle specifies, 20 moves),
# and then bring in our vectorized approach to simulating chess moves

# Use n() and replace = TRUE to vectorize the sampling above
crossing(trial = 1:100000,
         turn = 1:20) %>%
  mutate(move_x = sample(2, n(), replace = TRUE) *
           sample(c(1, -1), n(), replace = TRUE),
         move_y = (3 - abs(move_x)) *
           sample(c(1, -1), n(), replace = TRUE))
#> # A tibble: 2,000,000 x 4
#>    trial  turn move_x move_y
#>    <int> <int>  <dbl>  <dbl>
#>  1     1     1     -1     -2
#>  2     1     2     -1     -2
#>  3     1     3      2      1
#>  4     1     4     -1      2
#>  5     1     5     -2     -1
#>  6     1     6      1     -2
#>  7     1     7      1     -2
#>  8     1     8      2      1
#>  9     1     9      2     -1
#> 10     1    10     -2      1
#> # ... with 1,999,990 more rows
## because the knights both start at (0, 0), we can calculate the position based 
## on the cumulative sum of moves the X direction and in the Y direction. 
## We do this by adding a group_by() (since movement happens separately 
## within each trial) and mutate() to the sequence.

turns <- crossing(trial = 1:100000,
                  turn = 1:20) %>%
  mutate(move_x = sample(2, n(), replace = TRUE) *
           sample(c(1, -1), n(), replace = TRUE),
         move_y = (3 - abs(move_x)) *
           sample(c(1, -1), n(), replace = TRUE)) %>%
  group_by(trial) %>%
  mutate(position_x = cumsum(move_x),
         position_y = cumsum(move_y)) %>%
  ungroup()

turns
#> # A tibble: 2,000,000 x 6
#>    trial  turn move_x move_y position_x position_y
#>    <int> <int>  <dbl>  <dbl>      <dbl>      <dbl>
#>  1     1     1     -2     -1         -2         -1
#>  2     1     2     -1      2         -3          1
#>  3     1     3     -2      1         -5          2
#>  4     1     4      2      1         -3          3
#>  5     1     5     -1     -2         -4          1
#>  6     1     6      2      1         -2          2
#>  7     1     7      1      2         -1          4
#>  8     1     8     -2     -1         -3          3
#>  9     1     9      1     -2         -2          1
#> 10     1    10     -2     -1         -4          0
#> # ... with 1,999,990 more rows
# Just like that, we've performed 100,000 trials of 20 sequential chess moves.

# let's answer the riddle's question. How often is the 
# knight back at its home space (0, 0) by the twentieth move?

turns %>%
  filter(turn == 20) %>%
  summarize(mean(position_x == 0 & position_y == 0))
#> # A tibble: 1 x 1
#>   `mean(position_x == 0 & position_y == 0)`
#>                                       <dbl>
#> 1                                   0.00669
# The probability of being back on the home space is about .6%.

# How does this compare to other turns?
library(ggplot2)
theme_set(theme_light())

by_turn <- turns %>%
  group_by(turn) %>%
  summarize(home = mean(position_x == 0 & position_y == 0))

by_turn %>%
  ggplot(aes(turn, home)) +
  geom_line() +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(y = "% home")
```

![](https://i.imgur.com/g17ttRC.png)

``` r

# Where might the chess piece be by turn 20?
# A geom_tile is a nice visualization for this.
turns %>%
  filter(turn == 20) %>%
  count(position_x, position_y, sort = TRUE) %>%
  ggplot(aes(position_x, position_y, fill = n)) +
  geom_tile()
```

![](https://i.imgur.com/2sqMkkG.png)

``` r

# Animate it
# install.packages('devtools')
devtools::install_github('thomasp85/gganimate', force = TRUE)
#> Downloading GitHub repo thomasp85/gganimate@master
#> WARNING: Rtools is required to build R packages, but is not currently installed.
#> 
#> Please download and install Rtools 3.5 from http://cran.r-project.org/bin/windows/Rtools/.
#>   
  
  
   checking for file 'C:\Users\SuperCom\AppData\Local\Temp\Rtmp2nyO5p\remotes24ac1fc5894\thomasp85-gganimate-4486793/DESCRIPTION' ...
  
   checking for file 'C:\Users\SuperCom\AppData\Local\Temp\Rtmp2nyO5p\remotes24ac1fc5894\thomasp85-gganimate-4486793/DESCRIPTION' ... 
  
v  checking for file 'C:\Users\SuperCom\AppData\Local\Temp\Rtmp2nyO5p\remotes24ac1fc5894\thomasp85-gganimate-4486793/DESCRIPTION'
#> 
  
  
  
-  preparing 'gganimate':
#>    checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
v  checking DESCRIPTION meta-information
#> 
  
  
  
-  checking for LF line-endings in source and make files and shell scripts
#> 
  
  
  
-  checking for empty or unneeded directories
#> 
  
  
  
-  building 'gganimate_0.9.9.9999.tar.gz'
#> 
  
   
#> 
#> Installing package into 'C:/Users/SuperCom/Documents/R/win-library/3.5'
#> (as 'lib' is unspecified)
library(ggplot2)
library(gganimate)

turns %>%
  count(turn, position_x, position_y) %>%
  ggplot(aes(position_x, position_y, fill = n)) +
  geom_tile() +
  transition_manual(turn)
#> nframes and fps adjusted to match transition
```

![](https://i.imgur.com/V7TkbUn.gif)

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
So it seems to be working - what is the issue?

**Comment by RYucel** [comment]
![image](https://user-images.githubusercontent.com/24809488/49786766-81edc880-fd2d-11e8-8915-9b65d40c62d8.png)
here is console error I get and output window does not play the animation, shows static version

**Comment by thomasp85** [comment]
but it works when you run the reprex? have you loaded gganimate when you run it yourself?

**Comment by RYucel** [comment]
It works after reprex it (on output export screen). I loaded gganimate library everytime I run it

**Comment by thomasp85** [comment]
So it works in general now, or still only during reprex? If it works now it is probably because you hadn't updated it in the first place...

**Comment by RYucel** [comment]
Only works when code copied to clipboard and reprex it then. Without reprex code, I can not get animation

**Comment by thomasp85** [comment]
Can you copy-paste the exact code you run (no screenshot) from a newly started R session along with the errors and whatever

**Comment by thomasp85** [comment]
I mean, run it and then copy-paste everything from the console

**Comment by RYucel** [comment]
Ok 
```r
> library(reprex)
> library(dplyr)
> library(tidyr)
> library(magick)
> # Random number between 1 and 2
> move_x <- sample(2, 1)
> 
> # If x is 2, y is 1, and vice versa
> move_y <- 3 - move_x
> c(move_x, move_y)
[1] 1 2
> 
> # How about letting either number be negative?
> move_x <- sample(2, 1) * sample(c(1, -1), 1)
> move_y <- (3 - abs(move_x)) * sample(c(1, -1), 1)
> c(move_x, move_y)
[1]  1 -2
> 
> # Now that we can sample a single move, we can try sampling many moves (say, 20)
> move_x <- sample(2, 20, replace = TRUE) * sample(c(1, -1), 20, replace = TRUE)
> move_y <- (3 - abs(move_x)) * sample(c(1, -1), 20, replace = TRUE)
> 
> move_x
 [1] -2  1 -2 -1  1  1 -1  2  2  1  1  2 -1  2  2  1  2  2 -1  1
> move_y
 [1] -1  2  1 -2 -2 -2  2  1  1  2  2 -1 -2  1  1 -2  1  1 -2  2
> 
> # The crossing() function from tidyr is wonderful for setting up Monte Carlo simulations.
> # It creates a tbl_df with every combination of the inputs (it's similar to the built-in expand.grid).
> crossing(trial = 1:3,
+          turn = 1:3)
# A tibble: 9 x 2
  trial  turn
  <int> <int>
1     1     1
2     1     2
3     1     3
4     2     1
5     2     2
6     2     3
7     3     1
8     3     2
9     3     3
> 
> # In this experiment, we'll simulate 100,000 trials (and, as the riddle specifies, 20 moves),
> # and then bring in our vectorized approach to simulating chess moves
> 
> # Use n() and replace = TRUE to vectorize the sampling above
> crossing(trial = 1:100000,
+          turn = 1:20) %>%
+   mutate(move_x = sample(2, n(), replace = TRUE) *
+            sample(c(1, -1), n(), replace = TRUE),
+          move_y = (3 - abs(move_x)) *
+            sample(c(1, -1), n(), replace = TRUE))
# A tibble: 2,000,000 x 4
   trial  turn move_x move_y
   <int> <int>  <dbl>  <dbl>
 1     1     1     -1     -2
 2     1     2     -2      1
 3     1     3     -2      1
 4     1     4      1      2
 5     1     5     -2     -1
 6     1     6      2     -1
 7     1     7      2     -1
 8     1     8     -1      2
 9     1     9      1      2
10     1    10      1     -2
# ... with 1,999,990 more rows
> ## because the knights both start at (0, 0), we can calculate the position based 
> ## on the cumulative sum of moves the X direction and in the Y direction. 
> ## We do this by adding a group_by() (since movement happens separately 
> ## within each trial) and mutate() to the sequence.
> 
> turns <- crossing(trial = 1:100000,
+                   turn = 1:20) %>%
+   mutate(move_x = sample(2, n(), replace = TRUE) *
+            sample(c(1, -1), n(), replace = TRUE),
+          move_y = (3 - abs(move_x)) *
+            sample(c(1, -1), n(), replace = TRUE)) %>%
+   group_by(trial) %>%
+   mutate(position_x = cumsum(move_x),
+          position_y = cumsum(move_y)) %>%
+   ungroup()
> 
> turns
# A tibble: 2,000,000 x 6
   trial  turn move_x move_y position_x position_y
   <int> <int>  <dbl>  <dbl>      <dbl>      <dbl>
 1     1     1     -2      1         -2          1
 2     1     2     -1      2         -3          3
 3     1     3      2      1         -1          4
 4     1     4      1      2          0          6
 5     1     5     -2     -1         -2          5
 6     1     6      2     -1          0          4
 7     1     7     -1      2         -1          6
 8     1     8      1     -2          0          4
 9     1     9     -1     -2         -1          2
10     1    10     -1     -2         -2          0
# ... with 1,999,990 more rows
> # Just like that, we've performed 100,000 trials of 20 sequential chess moves.
> 
> # let's answer the riddle's question. How often is the 
> # knight back at its home space (0, 0) by the twentieth move?
> 
> turns %>%
+   filter(turn == 20) %>%
+   summarize(mean(position_x == 0 & position_y == 0))
# A tibble: 1 x 1
  `mean(position_x == 0 & position_y == 0)`
                                      <dbl>
1                                   0.00648
> # The probability of being back on the home space is about .6%.
> 
> # How does this compare to other turns?
> library(ggplot2)
> theme_set(theme_light())
> 
> by_turn <- turns %>%
+   group_by(turn) %>%
+   summarize(home = mean(position_x == 0 & position_y == 0))
> 
> by_turn %>%
+   ggplot(aes(turn, home)) +
+   geom_line() +
+   scale_y_continuous(labels = scales::percent_format()) +
+   labs(y = "% home")
> 
> # Where might the chess piece be by turn 20?
> # A geom_tile is a nice visualization for this.
> turns %>%
+   filter(turn == 20) %>%
+   count(position_x, position_y, sort = TRUE) %>%
+   ggplot(aes(position_x, position_y, fill = n)) +
+   geom_tile()
> 
> # Animate it
> # install.packages('devtools')
> devtools::install_github('thomasp85/gganimate', force = TRUE)
Downloading GitHub repo thomasp85/gganimate@master
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.5 from http://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\SuperCom\AppData\Local\Temp\RtmpczLC5E\remotes15d473cc296b\thomasp85-gganimate-4486793/DESCRIPTION' ...
-  preparing 'gganimate':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'gganimate_0.9.9.9999.tar.gz'
   
Installing package into ‘C:/Users/SuperCom/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'gganimate' ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'gganimate'
    finding HTML links ... done
    anim_save                               html  
    animate                                 html  
    ease_aes                                html  
    enter_exit                              html  
    frame_vars                              html  
    gganimate-ggproto                       html  
    gganimate-package                       html  
    gganimate                               html  
    gif_file                                html  
    last_animation                          html  
    layer_type                              html  
    renderers                               html  
    save_animation                          html  
    shadow_mark                             html  
    shadow_null                             html  
    shadow_trail                            html  
    shadow_wake                             html  
    split_animation                         html  
    sprite_file                             html  
    transition_components                   html  
    transition_events                       html  
    transition_filter                       html  
    transition_layers                       html  
    transition_manual                       html  
    transition_null                         html  
    transition_reveal                       html  
    transition_states                       html  
    transition_time                         html  
    tween_before_stat                       html  
    video_file                              html  
    view_follow                             html  
    view_static                             html  
    view_step                               html  
    view_zoom                               html  
*** copying figures
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (gganimate)
In R CMD INSTALL
> library(ggplot2)
> library(gganimate)
> 
> turns %>%
+   count(turn, position_x, position_y) %>%
+   ggplot(aes(position_x, position_y, fill = n)) +
+   geom_tile() +
+   transition_manual(turn)
Error in transition_manual(turn) : 
  could not find function "transition_manual"
> 
```

**Comment by thomasp85** [comment]
what do you get if you call `ls(envir = as.environment('package:gganimate'))`

**Comment by RYucel** [comment]
`[1] "gganimate"      "gganimate_save"`

**Comment by thomasp85** [comment]
so it appears that you have the old version of gganimate installed on your local system...

try to run `devtools::install_github('thomasp85/gganimate')` from a clean R session and paste the output

**Comment by stevevaius77** [comment]
No change
`R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> ## Chess puzzle Sonsuz satranç tahtasinin ortasinda 
> ## 20 hamle yapan bir at en sonunda baslangiç noktasina dönme ihtimali
> library(reprex)
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> library(tidyr)
> library(magick)
Linking to ImageMagick 6.9.9.14
Enabled features: cairo, freetype, fftw, ghostscript, lcms, pango, rsvg, webp
Disabled features: fontconfig, x11
> devtools::install_github('thomasp85/gganimate')
Skipping install of 'gganimate' from a github remote, the SHA1 (44867932) has not changed since last install.
  Use `force = TRUE` to force installation
> # Random number between 1 and 2
> move_x <- sample(2, 1)
> 
> # If x is 2, y is 1, and vice versa
> move_y <- 3 - move_x
> c(move_x, move_y)
[1] 1 2
> 
> # How about letting either number be negative?
> move_x <- sample(2, 1) * sample(c(1, -1), 1)
> move_y <- (3 - abs(move_x)) * sample(c(1, -1), 1)
> c(move_x, move_y)
[1] 1 2
> 
> # Now that we can sample a single move, we can try sampling many moves (say, 20)
> move_x <- sample(2, 20, replace = TRUE) * sample(c(1, -1), 20, replace = TRUE)
> move_y <- (3 - abs(move_x)) * sample(c(1, -1), 20, replace = TRUE)
> 
> move_x
 [1]  1 -1  1 -1 -2  1  2  1 -1  2 -1 -2 -1 -1  1  2 -1  1  1  2
> move_y
 [1]  2 -2 -2 -2  1 -2 -1 -2  2 -1  2  1 -2 -2 -2  1  2  2  2 -1
> 
> # The crossing() function from tidyr is wonderful for setting up Monte Carlo simulations.
> # It creates a tbl_df with every combination of the inputs (it's similar to the built-in expand.grid).
> crossing(trial = 1:3,
+          turn = 1:3)
# A tibble: 9 x 2
  trial  turn
  <int> <int>
1     1     1
2     1     2
3     1     3
4     2     1
5     2     2
6     2     3
7     3     1
8     3     2
9     3     3
> 
> # In this experiment, we'll simulate 100,000 trials (and, as the riddle specifies, 20 moves),
> # and then bring in our vectorized approach to simulating chess moves
> 
> # Use n() and replace = TRUE to vectorize the sampling above
> crossing(trial = 1:100000,
+          turn = 1:20) %>%
+   mutate(move_x = sample(2, n(), replace = TRUE) *
+            sample(c(1, -1), n(), replace = TRUE),
+          move_y = (3 - abs(move_x)) *
+            sample(c(1, -1), n(), replace = TRUE))
# A tibble: 2,000,000 x 4
   trial  turn move_x move_y
   <int> <int>  <dbl>  <dbl>
 1     1     1      1      2
 2     1     2      2      1
 3     1     3     -2     -1
 4     1     4     -2     -1
 5     1     5      2     -1
 6     1     6      1     -2
 7     1     7     -2     -1
 8     1     8      2     -1
 9     1     9     -1      2
10     1    10      2     -1
# ... with 1,999,990 more rows
> ## because the knights both start at (0, 0), we can calculate the position based 
> ## on the cumulative sum of moves the X direction and in the Y direction. 
> ## We do this by adding a group_by() (since movement happens separately 
> ## within each trial) and mutate() to the sequence.
> 
> turns <- crossing(trial = 1:100000,
+                   turn = 1:20) %>%
+   mutate(move_x = sample(2, n(), replace = TRUE) *
+            sample(c(1, -1), n(), replace = TRUE),
+          move_y = (3 - abs(move_x)) *
+            sample(c(1, -1), n(), replace = TRUE)) %>%
+   group_by(trial) %>%
+   mutate(position_x = cumsum(move_x),
+          position_y = cumsum(move_y)) %>%
+   ungroup()
> 
> turns
# A tibble: 2,000,000 x 6
   trial  turn move_x move_y position_x position_y
   <int> <int>  <dbl>  <dbl>      <dbl>      <dbl>
 1     1     1      2     -1          2         -1
 2     1     2      1     -2          3         -3
 3     1     3      1      2          4         -1
 4     1     4      2      1          6          0
 5     1     5      1      2          7          2
 6     1     6     -1     -2          6          0
 7     1     7     -2     -1          4         -1
 8     1     8      1      2          5          1
 9     1     9      2      1          7          2
10     1    10     -2      1          5          3
# ... with 1,999,990 more rows
> # Just like that, we've performed 100,000 trials of 20 sequential chess moves.
> 
> # let's answer the riddle's question. How often is the 
> # knight back at its home space (0, 0) by the twentieth move?
> 
> turns %>%
+   filter(turn == 20) %>%
+   summarize(mean(position_x == 0 & position_y == 0))
# A tibble: 1 x 1
  `mean(position_x == 0 & position_y == 0)`
                                      <dbl>
1                                   0.00588
> # The probability of being back on the home space is about .6%.
> 
> # How does this compare to other turns?
> library(ggplot2)
> theme_set(theme_light())
> 
> by_turn <- turns %>%
+   group_by(turn) %>%
+   summarize(home = mean(position_x == 0 & position_y == 0))
> 
> by_turn %>%
+   ggplot(aes(turn, home)) +
+   geom_line() +
+   scale_y_continuous(labels = scales::percent_format()) +
+   labs(y = "% home")
> 
> # Where might the chess piece be by turn 20?
> # A geom_tile is a nice visualization for this.
> turns %>%
+   filter(turn == 20) %>%
+   count(position_x, position_y, sort = TRUE) %>%
+   ggplot(aes(position_x, position_y, fill = n)) +
+   geom_tile()
> 
> # Animate it
> turns %>%
+   count(turn, position_x, position_y) %>%
+   ggplot(aes(position_x, position_y, fill = n)) +
+   geom_tile() +
+   transition_manual(turn)
Error in transition_manual(turn) : 
  could not find function "transition_manual"
> `

**Comment by thomasp85** [comment]
don't run everything again... just `devtools::install_github('thomasp85/gganimate')` and paste the output of this

**Comment by RYucel** [comment]
Here it is 
`> devtools::install_github('thomasp85/gganimate')
Downloading GitHub repo thomasp85/gganimate@master
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.5 from http://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\SuperCom\AppData\Local\Temp\Rtmp0mkRmm\remotes2cac302d2720\thomasp85-gganimate-e40b884/DESCRIPTION' ...
-  preparing 'gganimate':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'gganimate_0.9.9.9999.tar.gz'
   
Installing package into ‘C:/Users/SuperCom/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'gganimate' ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'gganimate'
    finding HTML links ... done
    anim_save                               html  
    animate                                 html  
    ease_aes                                html  
    enter_exit                              html  
    frame_vars                              html  
    gganimate-ggproto                       html  
    gganimate-package                       html  
    gganimate                               html  
    gif_file                                html  
    last_animation                          html  
    layer_type                              html  
    renderers                               html  
    save_animation                          html  
    shadow_mark                             html  
    shadow_null                             html  
    shadow_trail                            html  
    shadow_wake                             html  
    split_animation                         html  
    sprite_file                             html  
    transition_components                   html  
    transition_events                       html  
    transition_filter                       html  
    transition_layers                       html  
    transition_manual                       html  
    transition_null                         html  
    transition_reveal                       html  
    transition_states                       html  
    transition_time                         html  
    tween_before_stat                       html  
    video_file                              html  
    view_follow                             html  
    view_static                             html  
    view_step                               html  
    view_zoom                               html  
*** copying figures
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (gganimate)
In R CMD INSTALL`

**Comment by thomasp85** [comment]
what is the output of running `.libPaths()`?

**Comment by RYucel** [comment]
`[1] "C:/Users/SuperCom/Documents/R/win-library/3.5"
[2] "C:/Program Files/R/R-3.5.1/library" `

**Comment by thomasp85** [comment]
try to run:

```r
packageVersion('gganimate')
.libPaths(.libPaths[1])
packageVersion('gganimate')
```

and paste the output

**Comment by RYucel** [comment]
`[1] "C:/Users/SuperCom/Documents/R/win-library/3.5"
[2] "C:/Program Files/R/R-3.5.1/library"           
> packageVersion('gganimate')
[1] ‘0.9.9.9999’
> .libPaths(.libPaths[1])
Error in .libPaths[1] : object of type 'closure' is not subsettable
> packageVersion('gganimate')
[1] ‘0.9.9.9999’`

**Comment by thomasp85** [comment]
and if you run:

```r
library(gganimate)
ls(envir = as.environment('package:gganimate'))
```

you still get the same output?

**Comment by RYucel** [comment]
Yes! it worked! Thank you very much!

**Comment by thomasp85** [comment]
Great - no idea what was going on with your system...? 🙂
