### ISSUE TITLE
animate pause last frame for a few seconds and reloop

### ISSUE THREAD

**Issue by ercan1** [thomasp85/gganimate#235]
Hi,

Is it possible to pause for a few seconds after the last frame is played and start the loop again so that the viewers can have a few minutes to see the last frame before the loop starts again?
best

Ercan

**Comment by thomasp85** [comment]
Use the `end_pause` argument in `animate()`

**Comment by ercan1** [comment]
thnx

**Comment by IdoBar** [comment]
Hi,
I'm trying to use end_pause() argument, but instead of freezing at the last frame, it shows some sort of hybrid between the last and first frame.
Any idea what might be causing that?
These are my `gganimate` specific commands:
```
p <- p+ transition_states(Date, transition_length = 4, state_length = 1) +
  enter_grow() +  ease_aes('linear') + exit_shrink() 
  
  # ease_aes('cubic-in-out') 

animate(p, fps = 25, duration = 20, width = 800, height = 600, end_pause = 100)
```

Thanks, Ido

**Comment by thomasp85** [comment]
You need to set `wrap = FALSE` in `transition_states()`

**Comment by IdoBar** [comment]
Thanks!
