### ISSUE TITLE
feature request: put more than one animations together

### ISSUE THREAD

**Issue by verajosemanuel** [thomasp85/gganimate#238]
Sometimes I need to show several animations from different data into a greater one.
Would be very useful to have the option of putting together the animations I need whitout depending on other external software, just plain R

maybe this is possible but I can't figure how to do it.....

**Comment by thomasp85** [comment]
You can do that already by using the `file_renderer()`, and then feed them into `gifski` or whatever in the order you want...

**Comment by PankajChohan9820** [comment]
Hey thomas can use gganimate for visualization of npy 1000 frames of nxm ?

**Comment by AndyBunn** [comment]
Could you show an example of how to use `file_renderer()` in this context? E.g., where does `file_renderer()` come into play?

```
p1 <- ggplot(iris, aes(x = Petal.Width, y = Petal.Length)) + geom_point()
p2 <- p1 + transition_states(Species,
                    transition_length = 2,
                    state_length = 1)
# combine plots into a list and then animate -- doesn't work but possible with `file_renderer()`?
pList <- list(p1,p2)
animate(pList)

```
