### ISSUE TITLE
old API?

### ISSUE THREAD

**Issue by jtene001** [thomasp85/gganimate#243]
I was able to install gganimate, but when I try to run it, I get the following error:

Error: It appears that you are trying to use the old API, which has been deprecated.
Please update your code to the new API or install the old version of gganimate
from https://github.com/thomasp85/gganimate/releases/tag/v0.1.1

How do I install the new API? 
I was not able to install the old version of gganimate. First, I tried the following command:

devtools::install_github('thomasp85/gganimate/releases/tag/v0.1.1')

This gave me the error:

Skipping install of 'gganimate' from a github remote, the SHA1 (2e368f3e) has not changed since last install.
  Use `force = TRUE` to force installation

Then I tried:

devtools::install_github('thomasp85/gganimate/releases/tag/v0.1.1', force = TRUE)

This gave me the error:

Downloading GitHub repo thomasp85/gganimate@master
Error: Does not appear to be an R package (no DESCRIPTION)

**Comment by jtene001** [comment]
Never mind. I apparently was trying to follow an example written for the old version of the package.
Sorry.

**Comment by LinaMDiaz** [comment]
help mel!  I do not know how can update or install the old version :(

Error: It appears that you are trying to use the old API, which has been deprecated.
Please update your code to the new API or install the old version of gganimate
from https://github.com/thomasp85/gganimate/releases/tag/v0.1.1

**Comment by thomasp85** [comment]
Download one of the files linked in the release. Uncompress and install from source in R. Do note that no form of support is given for this version any longer (help or bug fixes) and you should consider updating your code to the newest API

**Comment by wind2599** [comment]
"Download one of the files linked in the release. Uncompress and install from source in R. Do note that no form of support is given for this version any longer (help or bug fixes) and you should consider updating your code to the newest API"
the question is how to update to the newest API?

**Comment by ghost** [comment]
Why was this APIs backwards compatibility broken?
