### ISSUE TITLE
include additional variable other than states level variable or frame in title expression

### ISSUE THREAD

**Issue by gsimchoni** [thomasp85/gganimate#252]
I have asked this on [SO](https://stackoverflow.com/questions/53864892/gganimate-include-additional-variable-other-than-states-level-variable-or-frame?noredirect=1#comment94578943_53864892) and I have an approximate answer, but not very "robust", see below.

I'd like to insert *another* column value of my data into a `gganimate` animation title.

Example, here the states level variable is `x` and I'd like to add to title variable `y`:

    df <- tibble(x = 1:10, y = c('a', 'a', 'b', 'd', 'c', letters[1:5]))
    df

    A tibble: 10 x 2
           x y    
       <int> <chr>
     1     1 a    
     2     2 a    
     3     3 b    
     4     4 d    
     5     5 c    
     6     6 a    
     7     7 b    
     8     8 c    
     9     9 d    
    10    10 e 

This works as expected:

    ggplot(df, aes(x, x)) +
      geom_point() +
      labs(title = '{closest_state}') +
      transition_states(x,
                        transition_length = 0.1,
                        state_length = 0.1)

[![enter image description here][1]][1]

This fails:

    ggplot(df, aes(x, x)) +
      geom_point() +
      labs(title = '{closest_state}, another_var: {y}') +
      transition_states(x,
                        transition_length = 0.1,
                        state_length = 0.1)

> Error in eval(parse(text = text, keep.source = FALSE), envir) :   
> object 'y' not found

Also tried this, but `y` will not change:

    ggplot(df, aes(x, x)) +
      geom_point() +
      labs(title = str_c('{closest_state}, another_var: ', df$y)) +
      transition_states(x,
                        transition_length = 0.1,
                        state_length = 0.1)

[![enter image description here][2]][2]

Another option is to map `y` as the states level variable and use the `frame` variable instead of `x`, but in my application `y` is either a not-necessarily-unique character variable like above, or it is a numeric variable but again not-necessarily-unique and not-necessarily-ordered. In which case `gganimate` (or `ggplot`?) will order it as it sees fit, making the final result weird not ordered by `x`:

    ggplot(df, aes(x, x)) +
      geom_point() +
      labs(title = '{frame}, another_var: {closest_state}') +
      transition_states(y,
                        transition_length = 0.1,
                        state_length = 0.1)

[![enter image description here][3]][3]

So how to simply add the changing value of the un-ordered, not numeric, `y` variable?

UPDATE: this was suggested in SO, seems like the best way, but it is a bit of a trick, and we *have to* include the `x` variable in the title:

```
df <- mutate(df, title_var = factor(paste(x, y, sep="-"), levels = paste(x, y, sep="-")))

ggplot(df, aes(x, x)) +
  geom_point() +
  labs(title = '{closest_state}') +
  transition_states(title_var,
                    transition_length = 0.1,
                    state_length = 0.1)
```

![gganimate_another_var04](https://user-images.githubusercontent.com/9554580/50277413-05559b00-044d-11e9-9f43-0c2d27d40a2b.gif)

[1]: https://i.stack.imgur.com/g9u1l.gif
[2]: https://i.stack.imgur.com/tTs8E.gif
[3]: https://i.stack.imgur.com/9NYjW.gif

**Comment by gsimchoni** [comment]
UPDATE: regarding that last "dirty" method which works, this can get you the `y` variable only:

    labs(title = '{gsub(pattern = "[0-9]+-", replacement = "", closest_state)}')

Again, a more methodical solution would have been nice.

**Comment by thomasp85** [comment]
For your specific application I think I would do something like this:

```r
ggplot(df, aes(x, x)) +
  geom_point() +
  labs(title = '{df$y[as.integer(closest_state)]}') +
  transition_states(x,
                    transition_length = 0.1,
                    state_length = 0.1)
```

![y_var](https://user-images.githubusercontent.com/1775316/50591112-2d51ef00-0e8e-11e9-84e6-99650729d3db.gif)

There are multiple reasons why random columns from the input data cannot be accessed so it is unlikely to get any better than this...
