### ISSUE TITLE
polygon map transition does not work

### ISSUE THREAD

**Issue by ercan1** [thomasp85/gganimate#256]
Hi all,

I have the following code, which fails to make the required time transitions, although I was able to plot a static map with correct values if I do not run the animate function. I also noticed that the left join of the map (TUR_for) and the data (data1) which is denoted as final_map produces 3.1 million data points beacuse of the map polygon lat and long data.

library(ggplot2)
library(purrr)
library(dplyr)
library(tidyr)
library(tibble)
library(sp)
library(readr)
library(RColorBrewer)
library(mapproj)
library(gganimate)
library(lubridate)
library(tweenr)
library(transformr)
library(units)
library(ggmap)

TUR <- readRDS("C:/Users/Ercan/Desktop/TUR_adm1.rds")

TUR_for <- fortify(TUR) 

data1 <- BDDK_Cities %>%
  select("Year", "City", "id", "other_npl_ratio")

TUR_for$id <- as.numeric(TUR_for$id)
data1$id <- as.numeric(data1$id)

final_map <- left_join(TUR_for, data1, by = "id")
 head(final_map)

 plot1 <- ggplot(final_map) +
  geom_polygon( aes(x = long, y = lat, group = group, fill =other_npl_ratio),
                color = "grey") +
  coord_map() +
  theme_void() +
  labs(title = "Konut",
       caption = "Kaynak: Türkiye İstatistik Kurumu") +
  scale_fill_distiller(name = "Konut Pay",
                       palette = "Spectral", limits = c(0,10)) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) +
   transition_time(Year) +
   ease_aes('cubic-in-out')
 animate(plot1, nframes = 200, fps = 2)

**Comment by thomasp85** [comment]
If I am to help you I'll need a reproducible example along with any error or problems you encounter - preferably made with the repress package.

I do not have access to your data and can thus not diagnose your problem...
