### ISSUE TITLE
Error: The animation object does not specify a save_animation method

### ISSUE THREAD

**Issue by fgsuned** [thomasp85/gganimate#257]
When I try to execute the enclosed R script, I always obtain the referenced error message: How can I fix it?
Regards,
FGS.
[circulitos.txt](https://github.com/thomasp85/gganimate/files/2723352/circulitos.txt)

**Comment by csaybar** [comment]
Hi @fgsuned 
I was able to reproduce your code,  it is work without any error.

``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Debian GNU/Linux 9 (stretch)
#> 
#> Matrix products: default
#> BLAS: /usr/lib/libblas/libblas.so.3.7.0
#> LAPACK: /usr/lib/lapack/liblapack.so.3.7.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] gganimate_0.9.9.9999   reprex_0.2.1.9000
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1   magrittr_1.5     tools_3.5.1      htmltools_0.3.6 
#>  [5] yaml_2.2.0       Rcpp_1.0.0       stringi_1.2.4    rmarkdown_1.11.3
#>  [9] highr_0.7        knitr_1.21       stringr_1.3.1    xfun_0.4        
#> [13] digest_0.6.18    evaluate_0.12 
```

<sup>Created on 2019-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by rcannood** [comment]
I had the same error message when I ran something like this:
```R
g <-
  ggplot(log_nodes) +
  geom_point(aes(x, y), points) +
  transition_manual(iteration)
anim_save(filename = "movie.gif")
```
because i forgot to plot the animation first. 
```R
> anim_save(filename = "movie.gif")
Error: The animation object does not specify a save_animation method
```

If you have a similar problem, the solution is to specify or print your animation:
```R
> anim_save(filename = "movie.gif", animation = g) # works
> print(g) # print first
> anim_save(filename = "movie.gif") # now also works
```

However, @fgsuned, your plot is definitely being printed before calling `anim_save()`, so I don't see what the issue could be. Running the script you provided also works for me.

**Comment by fgsuned** [comment]
Hi;
I was able to solve the problem modifiying the last sentence. Finally, I rewrote slightly the initial code with the enclosed script, and it worked properly.
Regards.
FGS.
[circulitos.txt](https://github.com/thomasp85/gganimate/files/2836178/circulitos.txt)

**Comment by rcannood** [comment]
FYI @fgsuned

Instead of 
```R
str_replace_all(paste("gif/circulitosP3-", toString(n_points), "p.gif"), fixed(" "), "")
```
You can also use 
```R
paste("gif/circulitosP3-", n_points, "p.gif", sep = "")
``` 
or even
```R
paste0("gif/circulitosP3-", n_points, "p.gif")
```

**Comment by JoFAM** [comment]
For reference: I've been battling this error for a while, until I figured out that I had to install the package `gifski` as well. After installing that one and restarting R so the defaults for `gganimate` were set correctly, everything worked just fine.

**Comment by vinnyricciardi** [comment]
> For reference: I've been battling this error for a while, until I figured out that I had to install the package `gifski` as well. After installing that one and restarting R so the defaults for `gganimate` were set correctly, everything worked just fine.

This worked for me on a Windows - is this OS specific?

**Comment by JoFAM** [comment]
@vinnyricciardi afaik this is for all OS the same. `gisfki` is a suggested package and is hence not automatically installed if you install `gganimate`. It's easy to overlook, hence my message.

**Comment by LockStoch** [comment]
> For reference: I've been battling this error for a while, until I figured out that I had to install the package `gifski` as well. After installing that one and restarting R so the defaults for `gganimate` were set correctly, everything worked just fine.

Thank you. Restarting R was the step I'd missed in my case.

**Comment by p-stehlik** [comment]
Thanks for this everyone - was doing my head in!!
