### ISSUE TITLE
Saving animation to mp4

### ISSUE THREAD

**Issue by SgtCheddar** [thomasp85/gganimate#259]
Hi, I have issues trying to save animations as '.mp4'. Here's an example:

`> p <- ggplot(airquality, aes(Day, Temp)) + geom_line(size = 2, colour = 'steelblue') + transition_states(Month, 4, 1) + shadow_mark(size = 1, colour = 'grey')`
`> a <- animate(p, renderer = ffmpeg_renderer())`
But then I have this message:
`Error in system2("ffmpeg", "-version", stdout = TRUE) : 
'"ffmpeg"' not found`

And finally I'd like to run:
`> anim_save("animation.mp4", a)`

Am I missing something ?

**Comment by rrmn** [comment]
ffmpeg is an external library. Therefore, you need to have ffmpeg installed **on your OS** to be able to use `ffmpeg_renderer()`.  (See also what the error message says: "Error in **system2** (...)")

**Solution:**
Check out [this step-by-step tutorial to install ffmpeg on Windows, macOS, and Ubuntu](https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg).
