### ISSUE TITLE
Stripping background for animation causes problems with theme

### ISSUE THREAD

**Issue by noamross** [thomasp85/gganimate#26]
When I add some theme options, like so:
```
library(ggplot2)
libra
library(gapminder)
p <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, color = continent, frame = year)) +
    geom_point() +
    scale_x_log10() + theme(text=element_text(size=25))
gganimate(p, "output.gif", height=5, width=5)
```

I get something like this: 
![output](https://cloud.githubusercontent.com/assets/571752/21083533/8d6d0cea-bfc0-11e6-975b-f697ed8827e9.gif)

I think this is because of the way the background is stripped out to server as a background while creating GIFs.  

Overall I'm unsure whether background should be stripped this way.  There are several situations I can envisage where one would want to have the background update (for instance, if you are zooming in and out of data). I may revert on my branch and see how it goes.  The other possibility is just stripping the legends along with the background, but can legends change by frame?

**Comment by mikeleeco** [comment]
I'm coming into this issue as well - @noamross, were you able to figure out a workaround?

**Comment by dgrtwo** [comment]
This is really my fault for doing the cowplot change, which had more complications than I expected. I'm going to revert it shortly.

**Comment by mikeleeco** [comment]
Thanks for the update David! :)
