### ISSUE TITLE
The example doesn't work now...

### ISSUE THREAD

**Issue by yukai-yang** [thomasp85/gganimate#260]
Awesome package! But when I install the package from CRAN and then run the example that you have shown here:
`
ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot() + 
  transition_states(
    gear,
    transition_length = 2,
    state_length = 1
  ) +
  enter_fade() + 
  exit_shrink() +
  ease_aes('sine-in-out')
`

An error popped up as follows:

> Error: The gifski package is required to use gifski_renderer

I think that this is bug perhaps due to some updates from some other dependent package... Perhaps you need to solve it?

**Comment by rrmn** [comment]
Try to update your packages + restart. Specifically, try to `install.packages("gifski")`. 

Works for me flawlessly on both Windows + macOS (latest versions) with both updated and fresh installs.

**Comment by thomasp85** [comment]
I've have had some change of mind with how default renderers should work and have settled on gif ski being default, but not required (you can change the default yourself if you don't want to install gifski)

**Comment by yukai-yang** [comment]
It works perfectly now! Many thanks! Great job!

**Comment by wildjara** [comment]
Thank you, It works very well !!
