### ISSUE TITLE
New Readme example: gganimate + ggmap

### ISSUE THREAD

**Issue by rrmn** [thomasp85/gganimate#261]
Hi Thomas,

I have encountered many questions on SO ([and also here](https://github.com/thomasp85/gganimate/issues/256)) where people were struggling to animate some sort of spatial data. Subjectively, the most common use case was `ggmap` (which also makes sense, as it is quite close).

Maybe it would be reasonable to **add another example to the Readme** that showcases a **spatial visualisation**? An additional benefit would be that it is closer to a real world scenario than, let's say, mtcars and a bit more flashy.

Maybe something along the lines of:

``` r
library(ggplot2)
library(gganimate)
library(ggmap)
library(maps)
library(gapminder)

# Define lon/lat boundary box of China
bbox <- c(70, 0, 140, 60)
# Get map
map <- get_stamenmap(c(bbox[1], bbox[2], bbox[3], bbox[4]), zoom = 4)
# Get shapefile
borders <- borders("world")$data[, 1:5]
# Merge shapefile with Gapminder data 
df <- merge(gapminder, borders, by.x = "country", by.y = "region", all.x = TRUE)
# Order data
df <- df[with(df, order(group, year, order)), ]

# Build plot
g <- ggmap(map) +
    geom_polygon(data = subset(df, country == "China"), 
                 aes(x = long, y = lat, group = group, fill = pop), 
                 alpha = 0.5, color = "black") +
    scale_fill_gradientn(colours = c("green", "yellow", "red")) +
    coord_map(projection = "mercator",
              xlim = c(bbox[1], bbox[3]), ylim = c(bbox[2], bbox[4])) +
    # Here come the gganimate specific bits
    labs(title = "Population of China in {frame_time}") + 
    transition_time(year)
```

What do you think?   
Tried to keep all the fluff out (stuff like `scales::comma` or some data wrangling that is needed if you go beyond a one country use case) and make it as self-contained as possible.

![file30a05e7498e4](https://user-images.githubusercontent.com/14080347/50665630-b6157b80-0fb1-11e9-9bd5-b934b2249564.gif)

**Comment by thomasp85** [comment]
I think this sort of example is better suited for the wiki pages or somewhere else... the readme should be lightweight and is not really a main selling point anymore as gganimate has it's own site
