### ISSUE TITLE
Transitioning on generated stats and object permanence

### ISSUE THREAD

**Issue by clauswilke** [thomasp85/gganimate#262]
I think I've discovered another issue with transitioning on generated stats. When trying to use `group` to manipulate object permanence, the transitions get disrupted.

``` r
library(ggplot2)
library(gganimate)
library(ungeviz)  # devtools::install_github("clauswilke/ungeviz")

# this works
ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() +
  stat_smooth_draws(times = 20) + 
  theme_bw() +
  transition_states(stat(.draw), 1, 2)
```
![test](https://user-images.githubusercontent.com/4210929/50677814-3791fb80-0ffc-11e9-8ab1-987e7347e6dc.gif)

So far so good. Now, when I try to make lines fade in and out rather than transform, I end up with no animation.
``` r
# this doesn't
ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() +
  stat_smooth_draws(times = 20, aes(group = stat(.draw))) + 
  theme_bw() +
  transition_states(stat(.draw), 1, 2) +
  enter_fade() + exit_fade()
#> nframes and fps adjusted to match transition
```
![test2](https://user-images.githubusercontent.com/4210929/50677840-53959d00-0ffc-11e9-8917-412b9da8ec1d.gif)

However, things work fine if I do the same with an external data frame rather than a stat.
``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-24. For overview type 'help("mgcv-package")'.
fit <- gam(mpg ~ s(hp), data = mtcars, method = "REML")
newdata <- data.frame(hp = seq(min(mtcars$hp), max(mtcars$hp), length.out = 100))
sample_df <- sample_outcomes(fit, newdata, 10, unconditional = TRUE)

ggplot(mtcars, aes(hp, mpg)) +
  geom_point(color = "grey30", size = 0.5) +
  geom_line(data = sample_df, aes(group = .draw), color = "blue") +
  theme_bw() +
  transition_states(.draw, 1, 2) +
  enter_fade() + exit_fade()
```
![test3](https://user-images.githubusercontent.com/4210929/50677902-9192c100-0ffc-11e9-8854-47203bdfe46a.gif)

**Comment by clauswilke** [comment]
Transitions work now but there is no fade. Is this another bug or am I missing something?

``` r
library(ggplot2)
library(gganimate)
library(ungeviz)

ggplot(mtcars, aes(disp, mpg)) +
  geom_point() +
  stat_smooth_draws(size = 0.5, aes(group = stat(.draw))) +
  theme_bw() +
  transition_states(stat(.draw), 1, 2) +
  enter_fade() + exit_fade()
```
![test](https://user-images.githubusercontent.com/4210929/50683293-dd039a00-1011-11e9-99cf-cde444cdb737.gif)

**Comment by thomasp85** [comment]
That is a separate issue with how geom_smooth encodes its data... the alpha value is only used for the ribbon, not the line.

I'll special-case geom_smooth to make it work as expected... in the meantime you can use enter_grow()/exit_shrink() for a similar effect...

**Comment by thomasp85** [comment]
Fixed in bd551c1

**Comment by clauswilke** [comment]
Nice. Alternatively, these also work:
``` r
+ exit_recolour(colour = "#FFFFFF00") + enter_recolour(colour = "#FFFFFF00")
```

**Comment by thomasp85** [comment]
yup, except it will block out the grid lines (barely perceptible, but still)

**Comment by thomasp85** [comment]
oh, wait — you added an alpha to the colour... yeah that'll work
