### ISSUE TITLE
Strange dataset dependent grouping effect

### ISSUE THREAD

**Issue by clauswilke** [thomasp85/gganimate#266]
This works:
``` r
library(ggplot2)
library(ungeviz)    # devtools::install_github("wilkelab/ungeviz")
library(gganimate)

ggplot(iris, aes(Sepal.Length, Sepal.Width, colour = Species)) +
  geom_point() +
  stat_smooth_draws(
    times = 10,
    formula = y ~ x,
    aes(group = interaction(stat(.draw), colour)),
    size = 1.5
  ) +
  theme_bw() + theme(legend.position = "bottom") + 
  transition_states(stat(.draw), 1, 2) +
  enter_fade() + exit_fade()
```
![iris](https://user-images.githubusercontent.com/4210929/50743664-23781500-121b-11e9-80e6-6f8a10f94a07.gif)

This doesn't (lines are now connected):
``` r
ggplot(mtcars, aes(disp, mpg, colour = factor(cyl))) +
  geom_point() +
  stat_smooth_draws(
    times = 10,
    formula = y ~ x,
    aes(group = interaction(stat(.draw), colour)),
    size = 1.5
  ) +
  theme_bw() + theme(legend.position = "bottom") + 
  transition_states(stat(.draw), 1, 2) +
  enter_fade() + exit_fade()
```
![mtcars](https://user-images.githubusercontent.com/4210929/50743668-31c63100-121b-11e9-841d-7ae8fd229e5d.gif)

Notice that the only difference is the data set. I have tried `as.character(cyl)` instead of `factor(cyl)` to see if the problem is the numeric variable turned into a factor, and it makes no difference.

**Comment by thomasp85** [comment]
At least you can't complain the fixes aren't coming fairly quickly :-)

**Comment by clauswilke** [comment]
I'm not complaining. Thanks for all your effort on this. `shadow_mark()` looks much better now with `geom_smooth()`!

**Comment by thomasp85** [comment]
Dont worry - just joking 🙃
