### ISSUE TITLE
Unknown layer type

### ISSUE THREAD

**Issue by SarenT** [thomasp85/gganimate#267]
Hi,
I was trying to use gganimate with my density plots but I couldn't get it work. I am getting "Error: Unknown layer type" Is it because I am using geom_density?

Thanks!
SarenT

**Comment by thomasp85** [comment]
I’ll need a reproducible example in order to help

**Comment by SarenT** [comment]
Ok, actually, I tried to simplify my data to reproduce the issue and now I have another problem.

Here I get end data must be integer. data2$end is actually integer.
```

data2 = data.frame()
for(i in 1:10){
	data2sub = data.frame(y = rnorm(n = 1000, mean = log(i), i*10))
	data2sub$time = i
	data2 = rbind(data2, data2sub)
}

data2$timeF = as.factor(data2$time)
data2$end = data2$time + 2
data2$enter_length = 2
data2$exit_length = 2
ggplot(data2, aes(x = y, fill = timeF)) + geom_density() + transition_events(start = time, end = end)
```

**Comment by thomasp85** [comment]
it is not. You are adding a numeric to `data2$time` thus coercing the result to a numeric. Try this instead:

```r
data2 = data.frame()
for(i in 1:10){
	data2sub = data.frame(y = rnorm(n = 1000, mean = log(i), i*10))
	data2sub$time = i
	data2 = rbind(data2, data2sub)
}

data2$timeF = as.factor(data2$time)
data2$end = data2$time + 2L
data2$enter_length = 2L
data2$exit_length = 2L
ggplot(data2, aes(x = y, fill = timeF)) + geom_density() + transition_events(start = time, end = end)
```

The `L` suffix indicate that the number be treated like an integer (numbers default to numeric in R)

**Comment by SarenT** [comment]
Ah, of course `is.integer()` gives TRUE, even though it is numeric.
So now my initial problem is reproducible:

```
data2 = data.frame()
for(i in 1:10){
	data2sub = data.frame(y = rnorm(n = 1000, mean = log(i), i*10))
	data2sub$time = i
	data2 = rbind(data2, data2sub)
}

data2$timeF = as.factor(data2$time)
data2$end = data2$time + 2L
data2$enter_length = 2L
data2$exit_length = 2L
ggplot(data2, aes(x = y, fill = timeF)) + geom_density() + transition_events(start = time, end = end, 
																			enter_length = enter_length, 
																			exit_length = exit_length)
```

**Comment by thomasp85** [comment]
Ah... yes this is because certain geoms are not fully supported by all transitions yet - this will come, but requires some more work on the transformr backend.

I should probably reword the error though, as it is not that informative
