### ISSUE TITLE
Unary operator error with geom_area but not geom_line

### ISSUE THREAD

**Issue by alyssafowers** [thomasp85/gganimate#269]
I'm trying to show an area chart with a vertical line that moves across the X axis. I want the vertical line to be animated, but not the area chart beneath it. When I use geom_area, I get the error "Error in -data$group : invalid argument to unary operator," but the same code works fine with geom_line. The geom_area code works with no problems as a static chart.

Here is the geom_area version, which does not work:

`library(tidyverse)
library(gganimate)

dat1 <- data.frame(week = 1:10, count = base::sample(1:100, 10))
dat2 <- data.frame(weeknum = 1:10, id = 1:10)

a <- ggplot(data = dat2, aes(x = weeknum))+
  geom_vline(aes(xintercept = weeknum, frame = id))+
  geom_area(data = dat1, aes(x=week, y=count))+
  theme_classic() +
  transition_states(states = id, transition_length = 2, state_length = 1) +
  enter_fade() + 
  exit_shrink()

animate(a)`

And the geom_line version, which does work:

`library(tidyverse)
library(gganimate)

dat1 <- data.frame(week = 1:10, count = base::sample(1:100, 10))
dat2 <- data.frame(weeknum = 1:10, id = 1:10)

l <- ggplot(data = dat2, aes(x = weeknum))+
  geom_vline(aes(xintercept = weeknum, frame = id))+
  geom_line(data = dat1, aes(x=week, y=count))+
  theme_classic() +
  transition_states(states = id, transition_length = 2, state_length = 1) +
  enter_fade() + 
  exit_shrink()

animate(l)`

Any help would be appreciated!

**Comment by thomasp85** [comment]
`geom_hline` and `geom_vline` are sorta special in ggplot2 as they are in between geoms and annotations, so I suspect that is the case... I'll look into the error after RStudio::conf

In the meantime, you can use geom_segment and set `x=-Inf, xend=Inf` to make it span the full plot area
