### ISSUE TITLE
airquality example error object 'Day' not found

### ISSUE THREAD

**Issue by verajosemanuel** [thomasp85/gganimate#270]
Suddenly all the animations that were working fine yesterday, stopped working today. just installed gifski library.
Tested with the airquality code from examples page, raised an error. 
R 3.5.1
Windows 10
gganimate version 0.9.9.9999

```
Error in ggproto(NULL, TransitionReveal, params = list(along_quo = along_quo,  : 
  object 'Day' not found
```

```
airq <- airquality
airq$Month <- format(ISOdate(2004,1:12,1),"%B")[airq$Month]


ggplot(airq, aes(Day, Temp, group = Month)) +
  geom_line() +
  geom_segment(aes(xend = 31, yend = Temp), linetype = 2, colour = 'grey') +
  geom_point(size = 2) +
  geom_text(aes(x = 31.1, label = Month), hjust = 0) +
  transition_reveal(Month, Day) +
  coord_cartesian(clip = 'off') +
  labs(title = 'Temperature in New York', y = 'Temperature (°F)') +
  theme_minimal() +
  theme(plot.margin = margin(5.5, 40, 5.5, 5.5)) +
  shadow_wake(wake_length = 2, size = TRUE)
```

**Comment by thomasp85** [comment]
Can I get you to update gganimate and report back of it persists

**Comment by verajosemanuel** [comment]
upgraded to CRAN version 1.0 did not solve the issue.
any other info i can provide you to get an idea of what's happening?

**Comment by thomasp85** [comment]
Oh... it is still using the deprecated `id` API. The `transition_reveal` call should be `transition_reveal(Day)`

Thanks for reporting

**Comment by thomasp85** [comment]
Were did you find this example?

**Comment by verajosemanuel** [comment]
I think i copied from examples page but maybe i'm wrong because i did it time ago.
Thanks to you for such amazing package. I can assure you this is key for my work. I do a lot of charts and reports using it

**Comment by thomasp85** [comment]
It looks like something from one of my gists... I'll go through them and update them...

**Comment by thomasp85** [comment]
It was in the air gist

**Comment by verajosemanuel** [comment]
thanks. I'll change all the previous code to remove the ID mention in transition_reveal calls

**Comment by thomasp85** [comment]
Same is true for `transition_components` if you have used that

**Comment by verajosemanuel** [comment]
I think i've never used transition_components but I'll have a look.
Thanks
