### ISSUE TITLE
Question: using svg device means that gif won’t lose quality when scaled to bigger screens?

### ISSUE THREAD

**Issue by rdataforge** [thomasp85/gganimate#273]
I have issues when using gif to show animations on huge screens due to gif size  (lags and stutter) so I made smaller gifs and re-scale it via browser. This makes pixeled images.
Using svg device will solve this as svg is scalable graphics or am I missing the point?

**Comment by thomasp85** [comment]
That won’t work unfortunately as gifs cannot be based on vector graphic. If you use an svg device it will get rasterised prior to making the gif and you end up with the same problem. In general making a video using the av_renderer is probably the best if you want a good file size/quality tradeoff

**Comment by lbogaardt** [comment]
I've heard about animated SVG's ([wiki](https://en.wikipedia.org/wiki/SVG_animation) and [ccs-tricks](https://css-tricks.com/guide-svg-animations-smil/)). It would be great if _gganimate_ could render to this format!

**Comment by thomasp85** [comment]
That is not possible at all

**Comment by lbogaardt** [comment]
? why not

**Comment by thomasp85** [comment]
Because of what svg animations really are and how ggplot2 and gganimate are implemented. There is no technical route for supporting such a thing beyond a complete rewrite
