### ISSUE TITLE
RStudio CRAN repository doesn't list gganimate as available

### ISSUE THREAD

**Issue by jamesrozier9** [thomasp85/gganimate#275]
Trying to install gganimate into RStudio v. 1.2.1206, but I'm getting the following message:

> Warning in install.packages :
>   package ‘gganimate’ is not available (for R version 3.3.2)
> In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘gganimate’

Is this related to the preview version of RStudio or something else? Thank you.

**Comment by davidski** [comment]
R-oldrel versions on CRAN are for R v3.4, so binary packages are not available for your version of R (v3.3.2). You can try `install.packages("gganimate", type = "source")`, but you'll probably have better luck going to a more current version of R (at least 3.4, if not the current 3.5).
