### ISSUE TITLE
error I can't debug with transition_reveal

### ISSUE THREAD

**Issue by emcbride09** [thomasp85/gganimate#276]
Hey I have been struggling to recreate a similar plot to this with my data set:
https://twitter.com/thomasp85/status/1036915662025895936?lang=en 

I can't reproduce the error with a reprex which is super annoying but the error message is this:

Error in sprintf(paste0("%0", nc, "i"), frame) : 
  invalid format '%0NA'; use format %f, %e, %g or %a for numeric objects

It's an error I haven't dealt with before, thanks for any help

``` r
df <- structure(list(long = c(23.9665031433105, 23.9665031433105, 23.9665031433105, 
23.9665031433105, 23.9665031433105, 23.9665031433105), lat = c(-10.8717775344849, 
-10.8717775344849, -10.8717775344849, -10.8717775344849, -10.8717775344849, 
-10.8717775344849), group = c(3, 3, 3, 3, 3, 3), region = structure(c(2L, 
2L, 2L, 2L, 2L, 2L), .Label = c("Algeria", "Angola", "Benin", 
"Botswana", "Burkina Faso", "Burundi", "Cameroon", "Central African Republic", 
"Chad", "Comoros", "Democratic Republic of the Congo", "Djibouti", 
"Egypt", "Equatorial Guinea", "Eritrea", "Ethiopia", "Gabon", 
"Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Ivory Coast", 
"Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", 
"Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", 
"Niger", "Nigeria", "Republic of Congo", "Rwanda", "Senegal", 
"Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", 
"Sudan", "Swaziland", "Tanzania", "Togo", "Tunisia", "Uganda", 
"Zambia", "Zimbabwe"), class = "factor"), year = c(1970, 1971, 
1972, 1973, 1974, 1975), rate = c(NA_real_, NA_real_, NA_real_, 
NA_real_, NA_real_, NA_real_), pop = c(31787566, 31787566, 31787566, 
31787566, 31787566, 31787566), subregion = c("Middle Africa", 
"Middle Africa", "Middle Africa", "Middle Africa", "Middle Africa", 
"Middle Africa")), row.names = c(NA, 6L), class = "data.frame")

ggplot(df, aes(x = year, y = rate, group = region)) + 
    geom_line() + geom_segment(aes(xend = 2018, yend = rate)) + 
    geom_point() + transition_reveal(year) + ease_aes("linear")
#> Error in ggplot(uis_final_line, aes(x = year, y = rate, group = region)): could not find function "ggplot"
```

<sup>Created on 2019-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by sbtr1** [comment]
Encountered this error too, I think it happens due to missing values. df <- na.omit(df) did the trick for me.

**Comment by emcbride09** [comment]
> Encountered this error too, I think it happens due to missing values. df <- na.omit(df) did the trick for me.

Thanks so much, just got back to this, that worked

**Comment by JoeMommaa** [comment]
> Encountered this error too, I think it happens due to missing values. df <- na.omit(df) did the trick for me.

in which part do I need to insert this one? Sorry, just starting to use R

**Comment by SecondarySkyler** [comment]
> > Encountered this error too, I think it happens due to missing values. df <- na.omit(df) did the trick for me.
> 
> in which part do I need to insert this one? Sorry, just starting to use R

I resolved putting it before ggplot
![image](https://user-images.githubusercontent.com/44577461/130322361-47e69ea4-cc4f-4447-a0d3-c21f0f5871a0.png)
