### ISSUE TITLE
Interpolate label variables in geom_text() or annotate() calls?

### ISSUE THREAD

**Issue by calpan** [thomasp85/gganimate#277]
The string interpolation that happens for labels would be useful to have in text annotations applied using geom_text() or annotate().   The "{closest_state}" labels below should be changing in sync with the plot title.  Is there currently a way to do this?

``` r
library(ggplot2)
library(gganimate)

ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot() + 
  geom_text(x=2, y=25, label='{closest_state}') +
  annotate('text', x=3, y=25, label='{closest_state}') +
  ggtitle('Gear: {closest_state}') +
  # Here comes the gganimate code
  transition_states(
    gear,
    transition_length = 2,
    state_length = 1
  ) +
  enter_fade() + 
  exit_shrink()
```

![](https://i.imgur.com/6rZfQ8V.gif)

Created on 2019-01-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
No - you can't do label interpolation inside geoms... you can, however prepare a separate data.frame with the labels you want and use that inside geom_text
