### ISSUE TITLE
zoo::yearmon not acceptable

### ISSUE THREAD

**Issue by apsteinmetz** [thomasp85/gganimate#278]
transition_time() is not happy with a zoo::yearmon object.
```
library(tidyverse)
library(gganimate)
library(zoo)
#this works
dat <- tibble(dates=as.Date(seq(0,360,by=31),origin="2010-01-01"),
              value=runif(12))
ggplot(dat,aes(dates,value))+geom_point()+
  transition_time(time=dates)

# change dates to yearmon class
#nope
dat$dates <- as.yearmon(dat$dates)
ggplot(dat,aes(dates,value))+geom_point()+
  transition_time(time=dates)
#> Warning in min(cl[cl != 0]): no non-missing arguments to min; returning Inf
#> Error: time data must either be integer, numeric, POSIXct, Date, difftime, orhms
````

**Comment by RickPack** [comment]
tsibble::yearmonth() works

`library(tidyverse)
library(gganimate)
library(zoo)
# this works
dat <- tibble(dates=as.Date(seq(0,360,by=31),origin="2010-01-01"),
              value=runif(12))
ggplot(dat,aes(dates,value))+geom_point()+
  transition_time(time=dates)

# also works
dat$dates <- tsibble::yearmonth(dat$dates)
ggplot(dat,aes(dates,value))+geom_point()+
  transition_time(time=dates)`
