### ISSUE TITLE
Remove layers in animation

### ISSUE THREAD

**Issue by cainesap** [thomasp85/gganimate#281]
Hello,

Thanks for the awesome library.

I'm trying to work out how to reduce a plot piece by piece. The reverse of a cumulative plot if that makes sense. I mean, start with everything, and gradually remove pieces of the plot.

For example, in this plot, I'd like to start with all points, and in each transition remove the points for one factor level: 

```
ggplot(mtcars, aes(x=drat, y=mpg)) +
  geom_point(aes(colour=as.factor(cyl))) +
  transition_manual(cyl, cumulative=T) +
  enter_fade() + exit_fade()
```

Any pointers would be much appreciated,
Andrew

**Comment by thomasp85** [comment]
I can see a couple of ways to achieve this, either using transition_filter, or transition_events. Try to play with these...

An alternative is to use shadow_mark but only showing future points (see the help page for that)

**Comment by cainesap** [comment]
Thank you, yes transition_events works for me!
