### ISSUE TITLE
access numeric value of frame_vars in labels

### ISSUE THREAD

**Issue by apsteinmetz** [thomasp85/gganimate#285]
The metadata is stored as integer or factor but gets converted to a string for labels.  How can I get it back to numeric to do operations on it in the label?
```
p + labs(title=paste("My Frame: {frame}")
p + transition_manual(some_variable)
```

is great.  Now what if I want to show a progress bar of sorts?  I would like to do this:
```
p + labs(title=paste("Progress:", str_rep(".", as.integer("{frame}"))
p + transition_manual(some_variable)

```
but the metadata cannot be coerced back to numeric.  Thanks.

**Comment by thomasp85** [comment]
I would generally advice you to check out the glue documentation for how to work with string literal interpolation. In short, everything in between`{` and `}` can be a regular R expression so in your case you could simply do:

```r
p + labs(title="Progress: {str_rep('.', frame)}")
```

**Comment by apsteinmetz** [comment]
[Success!](https://twitter.com/adababbage/status/1089994136806150144)  Was not familiar with `glue`. Thanks.
