### ISSUE TITLE
Animating each layer with different parameters

### ISSUE THREAD

**Issue by ibaltzakis** [thomasp85/gganimate#289]
Is this possible ? To set different parameters for each layer, for example, time of animation, enter and exit effect and easing type ?

**Comment by thomasp85** [comment]
I'm unsure about what you mean with *time of animation*, but enter and exit can be set individually for each type of layer. easing can only be differentiated based on aesthetic right now

**Comment by ibaltzakis** [comment]
Hi Thomas, thanks for the reply. By time of animation, I mean the length of the animation for each layer, as well as the starting point for animating each layer.

It's great that enter and exit can be set individually, would you be able to share a small example of how to do this for a 2 layer plot ?

**Comment by zoudj** [comment]
Hi Thomas.  If I understand it correctly, I can apply enter_grow() to a geom_bar() layer, and apply enter_fade() to a geom_text() layer separately in a ggplot. There will not be a composite entering effect. Could you give an example of how to set enter_* individually for a specific  layer? I tried, but couldn't figure it out. Many thanks!

**Comment by thomasp85** [comment]
You can name the layers in enter/exit either by geom name or by position... so you could do:

```r
p + enter_grow('bar') + enter_fade('text')
```

**Comment by pamdx** [comment]
hi @thomasp85, sorry for reopening this but whenever I try the above solution, I get the following error (using gganimate 1.0.8 or 1.0.7):

```
Error in get(x, envir = env, mode = "function") : 
  object '<GEOMNAME>' of mode 'function' was not found
```

where `<GEOMNAME>` is, e.g. `"point"` or `"label"` (what I'm trying to achieve here is to fade my `geom_label()` annotations in and out).

Thanks in advance for your help!
