### ISSUE TITLE
Using {frame_time} in the title for year shows non-integers

### ISSUE THREAD

**Issue by jzadra** [thomasp85/gganimate#295]
When I use transition_time(year) and put "year: {year}" in the title, I get titles like "2017.285183", "2017.486" etc, building up through non-integers.

**Comment by jzadra** [comment]
I figured this out.  If the numeric value being used, ie year, is type double, you will get this behavior.  If it is type integer, it works correctly.

If this isn't intended, might be good to treat variables that could be integer as integer.

Example:

``` r

library(gapminder)
library(gganimate)
#> Loading required package: ggplot2
library(tidyverse)

gapminder %>% 
  mutate(year = as.numeric(year)) %>% 
  ggplot(aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')
```

![](https://i.imgur.com/c2hJpoc.gif)

<sup>Created on 2019-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by UNFPAmaldives** [comment]
The solution, I read elsewhere, is to change your year variable to integer, and then, instead of `transition_time`, use `transition_states`, e.g.:
```
labs(title = 'Year: {closest_state}', x = 'GDP per capita', y = 'life expectancy (years)') +
transition_states(year, transition_length = 1, state_length = 1) +
ease_aes('linear')  
```

**Comment by thomasp85** [comment]
No need for that — just put `”Year: {as.integer(frame_time)}”` as your title

**Comment by KucherP** [comment]
But, if I need to show not year (like 2012, 2013 etc), but period (2012-1, 2012-2 etc). How to do that?

**Comment by thomasp85** [comment]
However you’d usually do this with R code. You can basically stick whatever code inside `{}` that returns something coercive to a character

**Comment by Deleetdk** [comment]
Simple solution is to use `"Year: {format(frame_time, '%Y-%m')}"` which gives you stuff like 2012-1, 2012-2.

**Comment by highclef93** [comment]
Hello, I think I have a similar problem, I want to add evolving date and time(minutes) to the title of my ggplot animate,
I'm new to R, I need help please
