### ISSUE TITLE
gg_animate save in subdirectories

### ISSUE THREAD

**Issue by hilaryparker** [thomasp85/gganimate#3]
I'm not sure what the fix is for this, but I found that I can save via gg_animate to the current working directory, but not existing subdirectories. 

``` r
gg_animate(p)
gg_animate(p, "test.gif")  # works!
gg_animate(p, "graphs/test.gif")  # doesn't work
```

I'm able to do this with ggsave, so hopefully one of us will be able to borrow from that sourcecode. Happy to try to figure out what to do! Not in my wheelhouse at all however so I defer to you =)

**Comment by ramnathv** [comment]
Easiest fix to this would be do something like this

``` r
# borrowed from servr:::in_dir
in_dir = function(dir, expr) {
  owd = setwd(dir); on.exit(setwd(owd))
  expr
}

in_dir('graph', gg_animate(p, 'test.gif'))
```

You should be able to plug `in_dir` directly into `gg_animate` so that the file saving functions are run inside the appropriate directory.
