### ISSUE TITLE
Cannot get ggplot to recognize frame aesthetic

### ISSUE THREAD

**Issue by PDTenpas** [thomasp85/gganimate#30]
First time using gganimate and I can't seem to find a solution to this anywhere on the interwebs.

I've successfully installed and loaded gganimate

```
library("devtools")
devtools::install_github("dgrtwo/gganimate")
library("gganimate")
```

Yet whenever I try to define the frame in AES, I cannot get ggplot to recognize it. EX:

```
 ggplot(FinSet, aes(exponent_estimate,frame=WindowID)) +
     geom_density(alpha = 0.1, size=.5,aes(group=Country, colour=Country, fill=Country, frame=WindowID)) + 
     xlim(0, 10) +
     ggtitle("Plot Plot")+
     theme(legend.position="none")
```
> Warning: Ignoring unknown aesthetics: frame

Apologies if this is a simple mistake or the wrong place for this!

**Comment by yeedle** [comment]
I'm getting the same warning when using `frame` with `geom_polygon`.

**Comment by BrunoGrandePhD** [comment]
Related to #13? Try @aleixdorca's suggestion of coercing the frame variable to a factor.

**Comment by ocstringham** [comment]
variable to factor didn't work for me with geom_polygon

**Comment by mgagliol** [comment]
I confirm that turning the mapped variable into a factor does not help

**Comment by mvevans89** [comment]
I've had a similar problem. I found that adding it to original ggplot call solved the problem. Example:
```
p <- ggplot(data = map_data, aes(frame = month.no)) + 
geom_polygon(data = map_data, aes(fill = prediction, x = long, y = lat,  group = group)) 

gganimate(p)
```

**Comment by jebyrnes** [comment]
Having the same problem!

**Comment by dtickler** [comment]
Started a long reply about how I'd found a workaround using aes(frame = xxx) in the main ggplot() call and then frame = NULL for any geometries that I didn't want animated.... And then I realised that my animation was running fine anyway - the "Warning: Ignoring unknown aesthetics: frame" seems to be an red herring (for me at least) and the code is actually working.

FYI this is the code I'm using:

```
p = ggplot() +
  geom_raster(data=animated.map.data2, aes(x = long, y = lat, fill=catch, alpha = catch/20, frame = year)) +
  geom_polygon(data = world.fortify, aes(x=long, y = lat, group = group), fill = "grey80", colour = "grey50") +
  coord_equal() +
  scale_fill_gradientn(name = bquote("T.km"^-2), colours = rev(heat.colors(20)), limits = c(0,20), breaks = c(0,20), labels = c('0','1'), na.value="white") +
  guides(alpha = FALSE) +
  theme_opts

gganimate(p)
```


The geom_raster line produces the animated spatial data; geom_polygon draws a static map overlay. I get the warning message when I run it, but then gganimate(p) works fine.

Just my experience. May be a fluke.
