### ISSUE TITLE
Problem with empty facets

### ISSUE THREAD

**Issue by banbh** [thomasp85/gganimate#306]
`transition_time()` seems to behave strangely when it encounters an empty facet in some frames of the animation. (Note that this issue mirrors [a post on SO](https://stackoverflow.com/questions/55110492) which contains an [excellent answer](https://stackoverflow.com/a/55118541).)

For example, here is a very simple dataset and a plot of it:

```
library(dplyr) # dplyr_0.7.8
library(tidyr) # tidyr_0.8.2 

crossing(p = 1:2, 
         t = seq(0, 1, len = 30),
         s = c(0, .5)) %>%
  mutate(x = t,
         y = t^p) %>%
  filter(t > s) ->
  Z

library(ggplot2) # ggplot2_3.1.0

Z %>%
  ggplot(aes(x,y)) +
  facet_wrap(~s) +
  geom_point()
```
As expected the second facet (s=0.5) only has data for x > 0.5, which (from how the tibble Z is constructed) comes from t > 0.5.

If one were to animate the above data (using t as time) I would expect the second facet to be empty for the first half of the animation, and then show the same as the first facet for the second half. However:

```
library(gganimate) # gganimate_1.0.2
Z %>%
  ggplot(aes(x, y, group = interaction(p,s))) +
  facet_wrap(~s) +
  geom_point() +
  transition_time(t) +
  ggtitle('{frame_time}')
```
The above code generates an animation (using gifski_0.8.6) with two facets where the second facet only shows its points briefly, and furthermore shows them at the wrong time (namely at the start of the animation).

**Comment by thomasp85** [comment]
Fixed in dev

**Comment by banbh** [comment]
I just installed HEAD and I can confirm it's fixed. Thanks!
