### ISSUE TITLE
Error in using animate()

### ISSUE THREAD

**Issue by claudiasolar** [thomasp85/gganimate#309]
I have managed to create the desired animation however when trying to adjust the time it moves through each frame, I ran into problems. I added to my code the line :
`anim <- animate(anim, fps = 10, duration = 15)`

This resulted in the following error:
 **Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘animate’ for signature ‘"gganim"’** 

Can anyone please tell me a better way to increase frames per second or troubleshoot this error?

I have pasted my code below and attached a .xlsx with a few rows of my data.

[df_example.xlsx](https://github.com/thomasp85/gganimate/files/2994465/df_example.xlsx)

```
ts <- read_csv('')

animated_map = function(df, state_level, region, colour_level, selected_title) {
  base_map <- ggplot() +
              borders("world", regions = region, colour = "gray85", fill = "gray80") +
              theme_map() +
              labs(title = selected_title, subtitle = 'Time Stamp: {closest_state}') +
              theme(plot.title = element_text(hjust = 0, size = 14, lineheight = .5),
                    plot.subtitle = element_text(hjust = 0, size = 12, lineheight = 0),
                    legend.position = c(0,.3),
                    legend.title = element_blank(),
                    legend.text = element_text(size = 12))

  if (typeof(colour_level) == 'character') {
    coloured <-  scale_color_manual(values=c('#7a4eb7', '#FF6100'))
  }
  else {
    coloured <-  scale_color_gradient(low="#7a4eb7", high="#FF6100")
  }

  anim <-  base_map +
           geom_point(aes(x = long, y = lat, color = colour_level), data = df, alpha = .5) +
           transition_states(state_level, transition_length = 0, state_length = 0.00000001, wrap = TRUE) +
           coloured

  anim <- animate(anim, fps = 10, duration = 15)
  
  return(anim)
}

animated_map(ts, ts$t_stamp, 'Australia', ts$threshold_3, 'Grid Disturbances')

```

**Comment by will-r-chase** [comment]
I ran the code as you have it and had no problems. I'm using R v 3.5.1 and gganimate v 1.0.2 

Try reinstalling gganimate from CRAN

**Comment by claudiasolar** [comment]
Hi William,

I am also using R v 3.5.1 and gganimate v 1.0.2
I only installed it last week but I have reinstalled it and it seems to be
working now.

Thank you,
Claudia

**Comment by preshitambade** [comment]
I am facing the same issue. Does anyone come up with the solution?
