### ISSUE TITLE
Issue installing gganimate and tweenr. Rtools issue?

### ISSUE THREAD

**Issue by dataders** [thomasp85/gganimate#312]
perhaps the best practice these days is to just install `gganimate` only from CRAN?

doing this manually because `reprex` isn't working for me.

`install.packages("gganimate")`

> Installing package into ‘C:/Users/anders.swanson/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> also installing the dependency ‘tweenr’
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/tweenr_1.0.1.zip'
> Content type 'application/zip' length 866011 bytes (845 KB)
> downloaded 845 KB
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/gganimate_1.0.3.zip'
> Content type 'application/zip' length 1842341 bytes (1.8 MB)
> downloaded 1.8 MB
> package ‘tweenr’ successfully unpacked and MD5 sums checked
> package ‘gganimate’ successfully unpacked and MD5 sums checked
> The downloaded binary packages are in
> 	C:\Users\anders.swanson\AppData\Local\Temp\Rtmp0eLQtl\downloaded_packages

`install.packages("devtools")`
> Installing package into ‘C:/Users/anders.swanson/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/devtools_2.0.2.zip'
> Content type 'application/zip' length 383185 bytes (374 KB)
> downloaded 374 KB
> package ‘devtools’ successfully unpacked and MD5 sums checked
> The downloaded binary packages are in
> 	C:\Users\anders.swanson\AppData\Local\Temp\Rtmp0eLQtl\downloaded_packages

`devtools::install_github('thomasp85/tweenr')`

> Downloading GitHub repo thomasp85/tweenr@master
> √  checking for file 'C:\Users\anders.swanson\AppData\Local\Temp\Rtmp0eLQtl\remotes108027c952b4\thomasp85-tweenr-17401ad/DESCRIPTION' (617ms)
> -  preparing 'tweenr':
> √  checking DESCRIPTION meta-information ... 
> -  cleaning src
> -  checking for LF line-endings in source and make files and shell scripts (356ms)
> -  checking for empty or unneeded directories
> -  building 'tweenr_0.1.5.9999.tar.gz'
>    
> Installing package into ‘C:/Users/anders.swanson/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> * installing *source* package 'tweenr' ...
> ** libs
> 
> *** arch - i386
> C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"C:/Users/anders.swanson/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
> C:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"C:/Users/anders.swanson/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c easing.c -o easing.o
> C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"C:/Users/anders.swanson/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c interpolators.cpp -o interpolators.o
> interpolators.cpp: In function 'Rcpp::DataFrame numeric_element_interpolator(Rcpp::NumericVector, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:567:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::DataFrame colour_element_interpolator(Rcpp::NumericMatrix, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:608:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::DataFrame constant_element_interpolator(Rcpp::CharacterVector, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:658:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List list_element_interpolator(Rcpp::List, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:701:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List numlist_element_interpolator(Rcpp::List, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:752:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::NumericVector numeric_fill_interpolator(Rcpp::NumericVector, Rcpp::CharacterVector)':
> interpolators.cpp:1187:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::NumericMatrix colour_fill_interpolator(Rcpp::NumericMatrix, Rcpp::CharacterVector)':
> interpolators.cpp:1209:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::CharacterVector constant_fill_interpolator(Rcpp::CharacterVector, Rcpp::CharacterVector)':
> interpolators.cpp:1230:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List list_fill_interpolator(Rcpp::List, Rcpp::CharacterVector)':
> interpolators.cpp:1251:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List numlist_fill_interpolator(Rcpp::List, Rcpp::CharacterVector)':
> interpolators.cpp:1276:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'double easePos(double, std::string)':
> interpolators.cpp:280:10: warning: 'p_new' may be used uninitialized in this function [-Wmaybe-uninitialized]
>    return p_new;
>           ^
> C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o tweenr.dll tmp.def RcppExports.o easing.o interpolators.o -LC:/PROGRA~1/R/R-35~1.3/bin/i386 -lR
> installing to C:/Users/anders.swanson/Documents/R/win-library/3.5/tweenr/libs/i386
> 
> *** arch - x64
> C:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"C:/Users/anders.swanson/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
> C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"C:/Users/anders.swanson/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -std=gnu99 -mtune=generic -c easing.c -o easing.o
> C:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"C:/Users/anders.swanson/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c interpolators.cpp -o interpolators.o
> interpolators.cpp: In function 'Rcpp::DataFrame numeric_element_interpolator(Rcpp::NumericVector, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:567:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::DataFrame colour_element_interpolator(Rcpp::NumericMatrix, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:608:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::DataFrame constant_element_interpolator(Rcpp::CharacterVector, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:658:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List list_element_interpolator(Rcpp::List, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:701:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List numlist_element_interpolator(Rcpp::List, Rcpp::CharacterVector, Rcpp::IntegerVector, Rcpp::CharacterVector)':
> interpolators.cpp:752:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 0; j < ease_points.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::NumericVector numeric_fill_interpolator(Rcpp::NumericVector, Rcpp::CharacterVector)':
> interpolators.cpp:1187:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::NumericMatrix colour_fill_interpolator(Rcpp::NumericMatrix, Rcpp::CharacterVector)':
> interpolators.cpp:1209:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::CharacterVector constant_fill_interpolator(Rcpp::CharacterVector, Rcpp::CharacterVector)':
> interpolators.cpp:1230:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List list_fill_interpolator(Rcpp::List, Rcpp::CharacterVector)':
> interpolators.cpp:1251:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'Rcpp::List numlist_fill_interpolator(Rcpp::List, Rcpp::CharacterVector)':
> interpolators.cpp:1276:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        for (j = 1; j < easepos.size(); ++j) {
>                      ^
> interpolators.cpp: In function 'double easePos(double, std::string)':
> interpolators.cpp:280:10: warning: 'p_new' may be used uninitialized in this function [-Wmaybe-uninitialized]
>    return p_new;
>           ^
> C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o tweenr.dll tmp.def RcppExports.o easing.o interpolators.o -LC:/PROGRA~1/R/R-35~1.3/bin/x64 -lR
> installing to C:/Users/anders.swanson/Documents/R/win-library/3.5/tweenr/libs/x64
> ** R
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
>   converting help for package 'tweenr'
>     finding HTML links ... done
>     display_ease                            html  
>     dot-complete_states                     html  
>     dot-get_last_frame                      html  
>     dot-max_id                              html  
>     reexports                               html  
> Rd warning: C:/Users/anders.swanson/AppData/Local/Temp/Rtmp6LMXIZ/R.INSTALLd4033e21dcf/tweenr/man/reexports.Rd:14: file link '%>%' in package 'magrittr' does not exist and so has been treated as a topic
>     tween                                   html  
> Rd warning: C:/Users/anders.swanson/AppData/Local/Temp/Rtmp6LMXIZ/R.INSTALLd4033e21dcf/tweenr/man/tween.Rd:107: file link 'approx' in package 'stats' does not exist and so has been treated as a topic
> Rd warning: C:/Users/anders.swanson/AppData/Local/Temp/Rtmp6LMXIZ/R.INSTALLd4033e21dcf/tweenr/man/tween.Rd:108: file link 'approx' in package 'stats' does not exist and so has been treated as a topic
>     tween_along                             html  
>     tween_appear                            html  
>     tween_at                                html  
>     tween_components                        html  
>     tween_elements                          html  
>     tween_events                            html  
>     tween_fill                              html  
>     tween_state                             html  
>     tween_states                            html  
>     tweenr-package                          html  
> Rd warning: C:/Users/anders.swanson/AppData/Local/Temp/Rtmp6LMXIZ/R.INSTALLd4033e21dcf/tweenr/man/tweenr-package.Rd:24: file link 'approx' in package 'stats' does not exist and so has been treated as a topic
> *** copying figures
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> *** arch - x64
> * DONE (tweenr)
> In R CMD INSTALL

`library(gganimate)`

> Loading required package: ggplot2
> RStudio Community is a great place to get help:
> https://community.rstudio.com/c/tidyverse.
> Error: package or namespace load failed for ‘gganimate’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
>  namespace ‘tweenr’ 0.1.5.9999 is being loaded, but >= 1.0.1 is required

**Comment by thomasp85** [comment]
Have you restarted R? if tweenr was already loaded when you updated the package it will only take effect after a restart

**Comment by dataders** [comment]
ah. didn't know I was supposed to restart after installing w/ devtools. Now it's working -- awesome!!
