### ISSUE TITLE
Error in l$setup_layer(d, plot) : attempt to apply non-function

### ISSUE THREAD

**Issue by thomasgable** [thomasp85/gganimate#313]
I created a pretty simple animation that was working no problem then installed 'ggthemr' package, which caused several other packages including ggplot to update. Right after I updated the packages, I tried to ran the same animation that was working 5 minutes earlier and I get:

Error in l$setup_layer(d, plot) : attempt to apply non-function

If I remove the transition_reveal() then I get the graph to appear (without the animation obviously). I restarted R and my computer but that did not fix the issue. Seems like it had to do with updating the packages and something changing when doing that.  Thoughts on how to fix this issue?

```
ggplot(diet2015,aes(x=Month,y=Percent, group=Pack, color=Pack))+geom_point()+geom_line()+
  facet_wrap(aes(diet2015$Prey))+transition_reveal(as.integer(Month))
```

**Comment by thomasgable** [comment]
There is some issue between ggplot2 v. 3.1.0 and 3.1.1. The error I got was from v. 3.1.1. When I installed the older version (3.1.0) I got the animation to work again without any problems.

**Comment by thomasp85** [comment]
Can I get you to reinstall gganimate and ggplot2 from CRAN and report back if the problem persists (after a restart)

**Comment by Nelson-Gon** [comment]
I have this issue. I tried to create a pretty simple plot that had failed a few months ago:
```
library(gganimate)
library(ggplot2)
library(dplyr)

iris %>%
  ggplot(aes(Sepal.Length, Petal.Length, col = Species)) +
  geom_point() +
  transition_states(Species, transition_length = 2, state_length = 1) +
  ease_aes("cubic-in-out")
````
The error:
**Error in l$setup_layer(d, plot) : attempt to apply non-function**

Versions:
dplyr_0.8.0.1   gganimate_1.0.2 ggplot2_3.1.1

**Comment by thomasgable** [comment]
It is the version of ggplot2 you are using. install ggplot2_3.1.0 and your animation will work. gganimate does not appear to work with the newest version of ggplot2. Hope that helps!

**Comment by Nelson-Gon** [comment]
This is now solved and works fine, at least for me with `ggplot2_3.1.1`

**Comment by max-carey** [comment]
> It is the version of ggplot2 you are using. install ggplot2_3.1.0 and your animation will work. gganimate does not appear to work with the newest version of ggplot2. Hope that helps!

I had the same problem, this worked for me now everything is working fine.

**Comment by wagnernoise** [comment]
> library(gganimate)
> library(ggplot2)
> library(dplyr)
> 
> iris %>%
>   ggplot(aes(Sepal.Length, Petal.Length, col = Species)) +
>   geom_point() +
>   transition_states(Species, transition_length = 2, state_length = 1) +
>   ease_aes("cubic-in-out")

I've tried this exact code and it's not working on R 3.6.1 with ggplot2 3.2.0. Any ideas on how to work around? Thanks!

**Comment by WPierrick** [comment]
Hi, same problem here.
I'm using ggplot2_3.2.1 and gganimate_1.0.3.9000.

**Comment by wagnernoise** [comment]
> Hi, same problem here.
> I'm using ggplot2_3.2.1 and gganimate_1.0.3.9000.

Hi, I got a work around, you have to install/update the packages gif-ski & png. After that, the gganimate should work properly. Cheers!

**Comment by WPierrick** [comment]
It worked! Thank you very much for the help.

**Comment by mpru** [comment]
> > Hi, same problem here.
> > I'm using ggplot2_3.2.1 and gganimate_1.0.3.9000.
> 
> Hi, I got a work around, you have to install/update the packages gif-ski & png. After that, the gganimate should work properly. Cheers!

This just worked for me as well! Thanks
R version 3.6.2 (2019-12-12)
gganimate_1.0.4.9000
ggplot2_3.2.1
