### ISSUE TITLE
geom_circle not working with gganimate

### ISSUE THREAD

**Issue by MattCowgill** [thomasp85/gganimate#314]
`library(tidyverse)
library(ggforce)
library(gganimate)`

This works:

`iris %>%
  ggplot() +
  geom_point(aes(Sepal.Width, Petal.Width)) +
  transition_states(Species)` 

This static plot code works:
`static_plot <- iris %>%
  ggplot() +
  geom_circle(aes(x0 = Sepal.Width, y0 = Petal.Width, r = 0.02))`

`static_plot`

It does not work as a gganimate graph:

`static_plot +
  transition_states(Species)`

Error:
`Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : 
  zero-length inputs cannot be mixed with those of non-zero length`

**Comment by thomasp85** [comment]
this seems to have been fixed
