### ISSUE TITLE
animate and geom_voronoi issue

### ISSUE THREAD

**Issue by davidfombella** [thomasp85/gganimate#315]
Thanks in advance  (gganimate installed from CRAN)

anim_voronoi <-all%>%
  ggplot() +
  annotate_pitch(colour = "white",
                 fill   = "chartreuse4",
                 dimensions =  list(
                   length = 105,
                   width = 68,
                   penalty_box_length = 18,
                   penalty_box_width = 44,
                   six_yard_box_length = 6,
                   six_yard_box_width = 20,
                   penalty_spot_distance = 12,
                   goal_width = 8,
                   origin_x = 0,
                   origin_y = 0
                 )) +
  theme_pitch() +
  geom_point(aes(x=x, y=y, fill=factor(team_name), size=factor(team_name)), 
             col="black", 
             shape=21)+ 
  **geom_voronoi(aes(x=x, y=y,fill=team_name),alpha = 0.3)+**
  transition_time(sample) +
  labs(title = "Tracking Data from STATS - David Fombella @bigdatasport")+
  theme(plot.background = element_rect(fill = "chartreuse4"),
        plot.title = element_text(color="white", size=20, face="bold.italic"),
        title = element_text(colour = "white"),
        legend.position = "none") +
  scale_size_manual(values=c(6,4,6)) +
  scale_fill_manual(values=c("#2b8cbe", "yellow", "#dd3497"), 
                    aesthetics = "fill")

animate(anim_voronoi,  width = 1024, height = 768,    nframes=nrow(btt), fps = 10)

OUTPUT
**Error in `$<-.data.frame`(`*tmp*`, "group", value = "") : 
  replacement has 1 row, data has 0
In addition: Warning message:
Computation failed in `stat_voronoi()`:
"data" must not contain duplicate (x,y) points.**

**Comment by davidfombella** [comment]
hi @thomasp85  can you help a bit :-)

**Comment by thomasp85** [comment]
Please provide a reproducible example. Also, I have a concussion so I won’t be super responsive
