### ISSUE TITLE
Can't animate ggforce::geom_circle()

### ISSUE THREAD

**Issue by steenharsted** [thomasp85/gganimate#327]
Hi,
Thank you for your great packages gganimate and ggforce.

I am having difficulties animating ggforce::geom_circle()

This issue is slightly different than "geom_circle not working with gganimate #314", as I don't get an error message. Just an animation that doesn't animate the geom_circle() objects.

The rest of the plot seems to animate as it should:

code:

```
library(tidyverse)
library(gganimate)
library(ggforce)

person <- tribble(
  ~object,    ~x,    ~y,   ~group, ~size,
  "head",      100,   180,      1,    10, 
  "neck",      100,   160,      1,    3, 
  "pelvis",    100,   100,      1,    3, 
  "lhip",       90,    90,      2,    3, 
  "rhip",      110,    90,      3,    3,
  "lknee",      80,    45,      2,    3,
  "rknee",     120,    45,      3,    3, 
  "lfoot",      50,     0,      2,    3, 
  "rfoot",      150,    0,      3,    3,
  "lshoulder",   85,  155,      4,    3, 
  "rshoulder",  115,  155,      5,    3, 
  "lhand",      75,   100,      4,    3, 
  "rhand",      125,  100,      5,    3)


frame <-  c(1, 10, 20, 30, 40, 50, 60, 70, 80, 90)

data_for_plot <- 
  crossing(
    frame,
    person) %>%
  mutate(
    x = x + frame,
    y = y + sin(frame)*5)
 
plot_data <- ggplot(data_for_plot, aes(x0=x, y0=y, r=size/2, group=group, fill=factor(group), color=factor(group))) +
  geom_circle() +
  geom_path(aes(x,y)) +
  coord_equal() + 
  labs(x="cm", y="cm") + 
  theme_classic() +
  theme(legend.position = "none")

plot_data+
  transition_states(frame)
```
![ggforce_gif](https://user-images.githubusercontent.com/40394828/59217004-45583800-8bbd-11e9-9efb-af815ea3ec07.gif)

**Comment by steenharsted** [comment]
I just updated ggforce to version 0.3.0 and tried to rerun the code in this issue. The result is better, but still not working 100%

I can read from the newsletter to the latest update of ggforce that some of the issues with animating ggforce geoms are caused by ggforce and not gganimate. I, therefore, wonder if I should post this issue on ggforce instead?

Thanks for all your work. Please let me know if I can help.

![With_updated_ggforce](https://user-images.githubusercontent.com/40394828/62820778-89d66480-bb69-11e9-9b69-e6fbdf4d3376.gif)

**Comment by thomasp85** [comment]
They are def problems in ggforce. In general, any geom that doesn’t work with gganimate should get fixed at the geom side — I don’t want to special case any geoms in the gganimate code

**Comment by steenharsted** [comment]
Cool - I close the issue here and open one in ggforce.
