### ISSUE TITLE
Dynamic Area of a Polygon in gganimate

### ISSUE THREAD

**Issue by davidfombella** [thomasp85/gganimate#328]
Hi thomas, trying to add Annotation....or text  or title....any dynamic way of plotting the area of 2 convex_hull polygons , I am trying now to add my code using Polygon class and @area as label in geom text.
Numeric Variable for transition is time, so I need to calculate area of polygon for each value of transition variable time.

p <- pitch_plot(68, 105) +
  geom_polygon(data = filter(data_hull, team == 'team A'), aes(x, y), fill = 'red', alpha = 0.4) +
  geom_polygon(data = filter(data_hull, team == 'team B'), aes(x, y), fill = 'blue', alpha = 0.4) +
  geom_point(data = filter(data, str_detect(team, 'team')), aes(x, y, group = player, fill = team), shape = 21, size = 6, stroke = 2) +
  geom_point(data = filter(data, team == 'ball'), aes(x, y), shape = 21, fill = 'dark orange', size = 4) +
  transition_time(**time**) +
  scale_fill_manual(values = c('team A' = 'red', 'team B' = 'blue')) +
  geom_text(data = filter(data, str_detect(team, 'team')), aes(x, y, label = player), color = 'white') +
##### team A
  geom_text(data = filter(data_hull, team == 'team A'), 
            aes(x=+20, y=-36, label = paste("Time",as.character(time)), color = 'red')) +
  **# team B
  geom_text(data = filter(data_hull, team == 'team B')%>% filter(time == time) %>% select(x,y), 
            aes(x=-20, y=-36, label = paste("Area ",round(Polygon(filter(data_hull, team == 'team B')%>% filter(time == time) %>% select(x,y), hole=F)@area)), color = 'blue')) +**
  guides(fill = FALSE)

animate(p,width = 735, nframes=max(data$time), height = 476,fps = 10)

**Comment by thomasp85** [comment]
There is not really any way to have gganimate calculate this for you - for now you'll have to calculate the areas in advance and use that
