### ISSUE TITLE
bquote() in labels causes animation to fail

### ISSUE THREAD

**Issue by Ax3man** [thomasp85/gganimate#332]
Related to #152, using `bquote()` instead of `expression()` yields an unable to open error. I think the solution in https://github.com/thomasp85/gganimate/commit/c5fc244385b532fe03818e3509db9aadedea92ad can be amended by adding an `is.call` check?

Works fine:
```r
ggplot(mtcars, aes(hp, mpg)) + 
  geom_point() + 
  labs(x = bquote('my text and'~v[subscript]))
```

Fails:
```r
ggplot(mtcars, aes(hp, mpg)) + 
  geom_point() +
  labs(x = bquote('my text and'~v[subscript])) + 
  transition_states(cyl)
```

**Comment by rknx** [comment]
wrapping bquote() inside as.expression() worked for me.
