### ISSUE TITLE
Error in rep(seq_len(nrow(polygon)), splits + 1) : invalid 'times' argument

### ISSUE THREAD

**Issue by xingyezn** [thomasp85/gganimate#333]
Can you help me see where the problem is?

code:
library(xlsx)
library(gganimate)
library(rust)
library(gifski)
library(ggplot2)
max_time = 375
df = read.xlsx('test.xlsx',1,encoding = "UTF-8")[1:max_time,]
col_name = c('time','x','y','z')
names(df) = col_name
anim2 = ggplot(df,aes(time,x))+geom_line(linetype = 1) + transition_time(time) + scale_x_log10()+ theme_bw()

animate(anim2,fps = 5,  renderer = gifski_renderer(),nframes = 100)

error:
![te](https://user-images.githubusercontent.com/37822579/59554414-09fea480-8fd5-11e9-9375-741c2bb98d2f.PNG)

data:
[test.xlsx](https://github.com/thomasp85/gganimate/files/3293370/test.xlsx)

**Comment by badluckmath** [comment]
Im having the same problem

**Comment by andreamirandagz** [comment]
I was also having this problem and then I read more carefully the help on transition_time(), turns out you should include a group in the aesthetics. Try using geom_line(aes(group=time), linetype=1).

**Comment by lionelvoirol** [comment]
I solved this by using `gganimate::transition_reveal(date)` as presented [here](https://www.r-graph-gallery.com/287-smooth-animation-with-tweenr.html)

**Comment by xingyezn** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已经收到，我会尽快回复你。
