### ISSUE TITLE
view_follow() doesn't respect facet_wrap(scales="free")

### ISSUE THREAD

**Issue by daniel-wells** [thomasp85/gganimate#334]
Is there any way to use facet_wrap(scales="free") and have the scales/axes recalculated for each frame? Currently using view_follow() all facet scales are the same even with scales="free".

```{r}
library(ggplot2)
library(gganimate)
library(gapminder)

ggplot(gapminder, aes(log(gdpPercap), lifeExp)) +
    geom_point() +
    facet_wrap(~continent, scales="free_y") +
    transition_time(year) +
    view_follow()
```

**Comment by thomasp85** [comment]
That is unfortunately not currently possible due to limitations in ggplot2

**Comment by jonspring** [comment]
I presume a similar semi-manual approach as used here for
ggforce::facet_zoom animation could work:
https://stackoverflow.com/a/53938398/6851825
