### ISSUE TITLE
view_follow() + coord_flip() creates issues in axes titles/text

### ISSUE THREAD

**Issue by chrmongeau** [thomasp85/gganimate#336]
Using `coord_flip()` + `view_follow()` (but also `view_step()`) creates transitions with the the titles of X axis above/below and Y axis in the left/right (and make axes numbers appear/disappear).

Example working fine without `coord_flip()`:

```r
library(ggplot2)
library(gganimate)
ggplot(iris, aes(x = Petal.Length, y = Sepal.Width)) +
  geom_segment(aes(xend = Petal.Length, y = 0, yend = Sepal.Width)) +
  geom_point() +
  transition_states(Species) +
  view_follow()
```

Here are the first two frames:

![image](https://user-images.githubusercontent.com/10231857/60610158-8100af00-9dc3-11e9-979d-1a345d3c66c4.png)

![image](https://user-images.githubusercontent.com/10231857/60610176-8c53da80-9dc3-11e9-80f9-1bd1a84e1fd4.png)

Now adding `coord_flip()`:

```r
library(ggplot2)
library(gganimate)
ggplot(iris, aes(x = Petal.Length, y = Sepal.Width)) +
  geom_segment(aes(xend = Petal.Length, y = 0, yend = Sepal.Width)) +
  geom_point() +
  coord_flip() +
  transition_states(Species) +
  view_follow()
```

Again, the first two frames (notice how the titles of axes change position, and numbers appear/disappear):

![image](https://user-images.githubusercontent.com/10231857/60610300-cae99500-9dc3-11e9-868f-915503093184.png)

![image](https://user-images.githubusercontent.com/10231857/60610349-f66c7f80-9dc3-11e9-8cf4-bd0f000b92c5.png)

**Comment by chrmongeau** [comment]
Well, animated gifs are supported, so here is the whole thing from the second example:

![coord_flip](https://user-images.githubusercontent.com/10231857/60610747-d38e9b00-9dc4-11e9-8537-e339ea827f9d.gif)

**Comment by pjsaran** [comment]
I am having the same issue. The text in the axis are flickering. Any workarounds?

**Comment by Grelot** [comment]
Have the same issue too

**Comment by woodwards** [comment]
Same issue.

**Comment by jxu** [comment]
`coord_flip()` does some weird things https://github.com/tidyverse/ggplot2/blob/master/R/coord-flip.r 

It should be possible to get around using `coord_flip()` by manually swapping `aes` and possibly using primitives like `geom_rect` instead of `geom_bar` or `geom_barh` suggested here https://stackoverflow.com/a/55791059
