### ISSUE TITLE
Installation of Gifski and png in Debian 10?

### ISSUE THREAD

**Issue by heoa** [thomasp85/gganimate#337]
I installed gifski with ```cargo install gifski``` and then in Cran but I am unable to install png package for the renderer needed

> The gifski_renderer() is used unless otherwise specified in animate() or in options('gganimate.renderer'). This renderer requires both the gifski and png packages to be installed.

so errors like 

> > install.packages("libpng")
> Installing package into ‘/home/hhh/R/x86_64-pc-linux-gnu-library/3.6’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘libpng’ is not available (for R version 3.6.1 RC)

and 

> gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG     `libpng-config --cflags` -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.6.0.20190628=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
> /bin/bash: libpng-config: command not found
> read.c:3:10: fatal error: png.h: No such file or directory
>  #include <png.h>
>           ^~~~~~~
> compilation terminated.
> make: *** [/usr/lib/R/etc/Makeconf:167: read.o] Error 1
> ERROR: compilation failed for package ‘png’
> * removing ‘/home/hhh/R/x86_64-pc-linux-gnu-library/3.6/png’
> Warning in install.packages :
>   installation of package ‘png’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/tmp/Rtmpyi6LEl/downloaded_packages'

How can I install the PNG package for Debian 10?

**Comment by thomasp85** [comment]
just run `install.packages('png')`

png is the R package - libpng is a system library
