### ISSUE TITLE
av_renderer and ffmeg_renderer on MacOS create strange mp4 files

### ISSUE THREAD

**Issue by neuwirthe** [thomasp85/gganimate#340]
av_renderer and ffmpeg_renderer on MacOS create webm files not supported by Quicktime Player.
Is there an option to set in the renders such that a standard mp4 file is produced which can be rendered by Quicktime Player?

**Comment by neuwirthe** [comment]
av_renderer and ffmpeg_renderer on MacOS create webm files not supported by Quicktime Player.
Is there an option to set in the renders such that a standard mp4 file is produced which can be rendered by Quicktime Player?

**Comment by neuwirthe** [comment]
After searching a little bit more, [https://ropensci.org/technotes/2018/10/06/av-release/](https://ropensci.org/technotes/2018/10/06/av-release/) came to rescue

It is necessary to give the file name to the call of the renderer function and not use anim_save with a filename.

Here is an example that works:

```{r}
in_df <- tibble(x=c(0:10,0:10),y=seq(0:21),state=rep(0:1,each=11))
in_df %>% ggplot(aes(x=x,y=y)) + geom_point() +
  transition_states(state) -> point_anim
animate(point_anim,renderer=av_renderer("points_anim.mp4"))
```

**Comment by mmmarte29** [comment]
It worked perfectly. Thanks for sharing your solution.
