### ISSUE TITLE
color transition for discrete color scales

### ISSUE THREAD

**Issue by neuwirthe** [thomasp85/gganimate#341]
This produces two charts with the same colors of the point

```{r}
library(tidyverse)
library(gganimate)
```

```{r}
my_df <- tibble(
  x=rep(1:10,2),
  y=1:20,
  state_disc=rep(c("a","b"),each=10),
  state_cont=rep(1:2,each=10)
)
```

```{r}
my_df %>% 
  ggplot(aes(x=x,y=y,color=state_cont)) +
  geom_point(size=5) +
  scale_color_gradient(low="#F8766D",high="#00BFC4") +
  transition_states(states=state_cont)
```

![2019-07-28_11-38-12](https://user-images.githubusercontent.com/157619/62004940-3527f800-b12c-11e9-8959-9de2aae9653a.png)

```{r}
my_df %>% 
  ggplot(aes(x=x,y=y,color=state_disc)) +
  geom_point(size=5)
```

![2019-07-28_11-39-04](https://user-images.githubusercontent.com/157619/62004946-512b9980-b12c-11e9-9d3e-95eef94ec1aa.png)

The first one can be animated nicely:

```{r}
my_df %>% 
  ggplot(aes(x=x,y=y,color=state_cont)) +
  geom_point(size=5) +
  scale_color_gradient(low="#F8766D",high="#00BFC4") +
  transition_states(states=state_cont) -> cont_anim
cont_anim
```

![cont_anim](https://user-images.githubusercontent.com/157619/62004986-dd3dc100-b12c-11e9-9955-cb04b639963b.gif)

The second one, with a discrete color scale, cannot be animated smoothly:

```{r}
my_df %>% 
  ggplot(aes(x=x,y=y,color=state_disc)) +
  geom_point(size=5) +
  transition_states(states=state_disc) -> disc_anim
disc_anim
```

![disc_anim](https://user-images.githubusercontent.com/157619/62005017-4faea100-b12d-11e9-9d92-00d9f2ed8edb.gif)

It would be very convenient if gganimate could create a smooth animation and interpolate the color values in the discrete case also.

**Comment by jonspring** [comment]
Try this:

my_df %>%
  ggplot(aes(x=x,y=y,color=state_disc, group = x)) +
  geom_point(size=5) +
  transition_states(states=state_disc)

I believe the difference is that gganimate's heuristics for assigning
groups (ie which points in one state connect to which points in another
state) work a little differently in your two examples. If you make the
grouping explicit it should work.

**Comment by neuwirthe** [comment]
This solved my problem!
