### ISSUE TITLE
frame_time title animation doesn't show

### ISSUE THREAD

**Issue by TamannaB** [thomasp85/gganimate#344]
labs(title = paste("Year:{frame_time}" doesn't show animated title on top. I tried with current_frame and frame_time. 

My code:
west <- ggplot()+
  borders("world", colour = "gray85", fill = "gray80") +
  coord_sf(xlim = c(-170.15, -15.0), ylim = c(-90.0, 90), expand = TRUE)+
  theme(panel.ontop = TRUE,   
            panel.grid = element_blank(), 
            line = element_blank(), 
            rect = element_blank(), 
            text = element_blank(), 
            plot.background = element_rect(fill = "white"))

west

#Adding data to the map layer
map <- west +
  geom_point(aes(x = lon, y = lat, size = Acreage),
             data = acre,
             colour = "dodgerblue4", alpha = .4, show.legend = TRUE) +
  scale_size_continuous(range = c(1, 7),
                        breaks = c(10000,20000, 30000, 40000, 50000))
  
  
map  

#Adding animation by year to map  
animap<- map +
   labs(title = paste("Year:{frame_time}"))+
   transition_time(Year)+
   ease_aes('linear')

**Comment by thomasp85** [comment]
You are setting text to be `element_blank()` meaning that it won’t get plotted
