### ISSUE TITLE
Error when {misspecified state} is not very informative

### ISSUE THREAD

**Issue by RMHogervorst** [thomasp85/gganimate#345]
REPREX:
```
ggplot(iris, aes(x= Sepal.Length, color = Species))+
     geom_density()+
     scale_x_continuous(limits = c(-10,10))+
     transition_states(Species)+
     labs(title = "This is species:{clostest_state}")
```
It took a while to find out what was going wrong here with this error:
`Error in png::readPNG(frames[1], native = TRUE) :                                                                  
  unable to open /tmp/Rtmp2E0MgV/10a66d3b5c6e/gganim_plot0001.png
In addition: There were 50 or more warnings (use warnings() to see the first 50)`
When I use the `warnings()` function you do get to see what is going wrong: `object 'clostest_state' not found` I mistyped...  
It would be nice if that error is thrown earlier or checked before the rendering starts?

**Comment by thomasp85** [comment]
In the next version glue errors will be silently ignored and the glue string will be used directly as label, i.e. the title in the above example will be "This is species:{clostest_state}" for all strings
