### ISSUE TITLE
Strange behavior of geom_polygon when using gganimate

### ISSUE THREAD

**Issue by toddrjones** [thomasp85/gganimate#355]
I first note that I have asked this same question on StackOverflow. Please let me know if double posting like this is not allowed. https://stackoverflow.com/questions/58568431/strange-behavior-of-ggplots-geom-polygon-when-using-gganimate

I have a very strange problem. What I am trying to do is to have a static map (of Texas), where each geography (county) is filled/colored according to the value of a variable. On top of this, I want to have dots appear and change color, etc. These use different datasets. I have been able to accomplish this second goal. The first, though, is exhibiting unexpected behavior. When I plot it statically (without using gganimate), it colors the counties correctly. However, when I use gganimate, the colors are incorrect (note the legend is the same in both cases).

Say that I have these data:

```
library(tidyverse)
library(gganimate)
devtools::install_github("UrbanInstitute/urbnmapr")
library(urbanmapr)

#1. counties dataset for the shading of the background
data(counties)
#keep only Texas counties
counties <- filter(counties, state_fips==48)

#2. dots dataset for dots over time
dots <- data.frame(group = c(rep(1,3), rep(2,3)), 
                    lat = c(rep(32, 3), rep(33, 3)),
                    long = c(rep(-100, 3), rep(-99,3)), 
                    year = c(1:3, 1:3))
```

I then plot them (the static version that does not use gganimate):

```
ggplot() +
    geom_polygon(data = counties, aes(long, lat, group = county_fips, fill = as.numeric(county_fips))) +
    scale_fill_gradient(low = "navy", high = "lightskyblue3")   +   
    geom_point(data = dots, aes(long, lat, group=interaction(long, lat), color=year), 
               size=6, show.legend = FALSE) + 
    theme_bw() +
    scale_color_gradientn(colours = c("red", "yellow", "darkgreen")) +
    coord_map() +
    labs(subtitle = paste('Year: {frame_time}')) +  
    theme(plot.subtitle = element_text(hjust = 0.8, vjust=-10, size=30)) +  
    theme(panel.background = element_rect(fill = 'white')) +
    theme(panel.grid = element_blank(),axis.title = element_blank(),
          axis.text = element_blank(),axis.ticks = element_blank(),
          panel.border = element_blank())+
    theme(legend.position = c(0.15, .15)) +
    theme(legend.key.size = unit(2,"line"),legend.title=element_text(size=16), 
          legend.text=element_text(size=14))    +
    labs(fill = "abc")
```

The result of the static plot is correct. However, when I run the following code, which introduces gganimate, the coloring of the counties is incorrect:

```
map <- ggplot() +
    geom_polygon(data = counties, aes(long, lat, group = county_fips, fill = as.numeric(county_fips))) +
    scale_fill_gradient(low = "navy", high = "lightskyblue3")   +
    geom_point(data = dots, aes(long, lat, group=interaction(long, lat), color=year), 
               size=6, show.legend = FALSE) + 
    theme_bw() +
    scale_color_gradientn(colours = c("red", "yellow", "darkgreen")) +
    coord_map() +
    labs(subtitle = paste('Year: {frame_time}')) +  
    theme(plot.subtitle = element_text(hjust = 0.8, vjust=-10, size=30)) +  
    theme(panel.background = element_rect(fill = 'white')) +
    theme(panel.grid = element_blank(),axis.title = element_blank(),
          axis.text = element_blank(),axis.ticks = element_blank(),
          panel.border = element_blank())+
    theme(legend.position = c(0.15, .15)) +
    theme(legend.key.size = unit(2,"line"),legend.title=element_text(size=16), 
          legend.text=element_text(size=14))    +
    labs(fill = "abc") +    
    transition_time(year) +
    shadow_mark(size=6)     

anim_save("output/test.gif", map, end_pause=6, width = 800, height = 800, duration=8)
```
Note that this code is exactly the same with the exception of adding the transition_time and shadow_mark lines (and using anim_save).

What can I do to correct the coloring of the counties when using gganimate?

**Comment by toddrjones** [comment]
Static version: 

![Screen Shot 2019-10-26 at 1 48 57 AM](https://user-images.githubusercontent.com/52247393/67624241-1ce37a00-f7fc-11e9-9fe8-0b1ccde8cd77.png)

gganimate version:

![test](https://user-images.githubusercontent.com/52247393/67624244-22d95b00-f7fc-11e9-8e10-e94a4f8a8e1f.gif)

Also note that it kind of looks like the coloring is inverted in the latter. However, I have done this with other data and the colors in the dynamic plot have even less resemblance to the ones in the static plot.

**Comment by thomasp85** [comment]
This seems to have been resolved at some point
