### ISSUE TITLE
geom_rect()  with xmin and xmax dependent on {frame_time}

### ISSUE THREAD

**Issue by SimonCoulombe** [thomasp85/gganimate#356]
Hey,

I have animated a plot showing the evolution of fertility rate by age and cohort.  I am pretty happy with the result:

![file3f3e455ec9bb](https://user-images.githubusercontent.com/23444900/68046743-f79ab400-fcb2-11e9-8e44-3a4b5f8f188f.gif)

I would  also like to add a background rectangle in pink for the WWII period, like  you typically see for recessions on GDP graphs:
 
![image](https://user-images.githubusercontent.com/23444900/68046821-303a8d80-fcb3-11e9-94e3-7d9b33fd9b48.png)

For example, women born  in 1922 would have ages 17-23 "pinked out", while women born in 1915 would have ages 24-30 "pinked out.".

I was hoping adding the final line of code (geom_rect) below would work:   
```

clean_qc  %>% 
  filter(annee_de_naissance>= 1915, annee_de_naissance  <= 1984) %>%
  ggplot(aes(x=age, y = taux_fecondite)) +  
  geom_line() +
  cowplot::theme_minimal_grid() + 
  ggthemes::scale_color_colorblind() +
  scale_x_continuous(expand = c(0,0), 
                     breaks = scales::pretty_breaks())+ 
  scale_y_continuous(expand = c(0,0),
                     breaks = scales::pretty_breaks())+ 
  theme(axis.text.y = element_text(size=12)) + # texte de l'axe des x
  theme(strip.text.x = element_text(size = 12 )) +  # texte des facets titles
  theme(strip.text.y = element_text(size = 12 ))  +  # texte des facets titles
  
  labs(title = "Fertility rate of women in Quebec",
       subtitle = 'Birth year of women: {frame_time}', 
       x = 'Age', 
       y = 'Fertility rate (per 1000 women)',
       caption= "Source: Statistics Canada") +
  transition_time(annee_de_naissance) +
  ease_aes('linear') + 
geom_rect(aes(xmin= 1939- {frame_time}, xmax=1945- {frame_time}, ymin=-Inf, ymax=+Inf), fill='pink', alpha=0.2)
```

.. but I get  this error: 

`Error in FUN(X[[i]], ...) : object 'frame_time' not found`

Pretty naive approach, but I'm not sure what to try

**Comment by thomasp85** [comment]
yeah, frame variables can only be inserted into levels

you would need to create data for the rectangles in each `annee_de_naissance` manually
