### ISSUE TITLE
gganimate animations are laggy and slow

### ISSUE THREAD

**Issue by whiteheadedduck** [thomasp85/gganimate#359]
I have been trying to learn how to use gganimate to animate plots. I was following the vignette (at https://gganimate.com/articles/gganimate.html#enter-and-exit) and when I tried to replicate the codes given there, I don't get the same results (as given on the page). When I run the code given below, I get the .gif given here. Compare it to the one on the page.

```
anim <- ggplot(iris, aes(x = Petal.Width, y = Petal.Length)) + 
  geom_point(aes(colour = Species), size = 2) + 
  transition_states(Species,
                    transition_length = 2,
                    state_length = 1)

anim + 
  enter_fade() + 
  exit_shrink()
```
GIF: https://media.giphy.com/media/KzKXtbWUUbisIc36n2/giphy.gif (saved using `anim_save(filename="mygif.gif"`)

As you see, the .gif is laggy as hell. When I try to modify it using height, width, res etc. using the code below, I get the next .gif.

animate(anim, res=250, height = 1080, width = 1980)
GIF: https://media.giphy.com/media/l51eJwWo0rj1OpzubE/giphy.gif (saved using `anim_save(filename="mygif2.gif"`)

Still laggy and not smooth. Compare it to the one on the vignette page. 

I have the latest versions of ggplot2, gganimate, tweenr, transformr. What should I do? How can I get silky smooth gifs? Please help.

**Comment by pdrhlik** [comment]
Hi @KaanOzgencil,

Unfortunately, both of your gifs are unavailable so I couldn't test how they look. I tried creating them on my own with the code you provided. And they are indeed laggy.

The main problem is with the animation frame rate. The default number of frames `nframes` is 100 and the default number of frames per second `fps` is 10. 10 fps is very low for a smooth animation. You need to increase this number. Try 25 or 50 and adjust the `nframes` accordingly. You may also want to try setting the `device` parameter to something else than `png`. See the example code below.

```
anim <- ggplot(iris, aes(x = Petal.Width, y = Petal.Length)) + 
  geom_point(aes(colour = Species), size = 2) + 
  transition_states(Species,
                    transition_length = 2,
                    state_length = 1)

animate(anim + enter_fade() + exit_shrink(), fps = 50, nframes = 250, device = "svg")

# Save animation to mysvg.gif
anim_save(filename = "mysvg.gif")
```

This is the result.
![mysvg](https://user-images.githubusercontent.com/14300398/69626960-f9edf500-1049-11ea-88be-4554cc0c53a9.gif)

There still seems to be a tiny glitch just before the points fade away but the result is smooth overall.
