### ISSUE TITLE
Error of loading "gganimate"

### ISSUE THREAD

**Issue by yuxiyan666** [thomasp85/gganimate#362]
Hi,
I'm trying to use "gganimate" package and version of R and RStudio are the newest. When I load devtools::install_github('thomasp85/gganimate'), there was an error like below:
==============================================
Error: package or namespace load failed for ‘gganimate’:
 .onLoad failed in loadNamespace() for 'gganimate', details:
  call: NULL
  error: The png package is required to use gifski_renderer
Error: loading failed
Execution halted
==============================================

I don't know what is the problem and I don't know how should I download or set up gifski_renderer.

Could you please help me with it?

Thanks,
Ivy

**Comment by yuxiyan666** [comment]
Well, I think I got it, just downloaded "png" package.

**Comment by harnagpal** [comment]
Hi  yuxiyan666 , I am also facing same problem. Which "png" package you downloaded!
I also have gisfki installed but I get below message
Warning message:
package ‘gifski’ was built under R version 3.6.2

**Comment by yuxiyan666** [comment]
Hello,
Last time I just downloaded “png” package, use “install” function. And for your case, you need to verify your version first.
