### ISSUE TITLE
Lack of `gifski` is not handled

### ISSUE THREAD

**Issue by romatik** [thomasp85/gganimate#363]
I see in `NEWS`, that there is this bullet in v1.0.4:

- Better fallback strategy for lack of gifski.

However, it seems that current fallback strategy is to not do anything at all. Neither warning nor error is generated if there is no `gifski` availabile and it's really not intuitive what needs to be done.

**Context**

I've came across one user trying to use the package and he claimed that there was no output. I've tried replicating it on both Mac and Ubuntu and behaviour was:

1. `gganimate` call creates all the frames it needs.
2. All intermediary `png` files are dumped into _working_ directory.
3. No output in RStudio preview window is generated. No error or warning.

I thought that there might be a bug, so tried `git bisect`, rolled back to `v1.0.2` and immediately got the error: ``The `gifski_renderer()` is selected by default but requires the gifski
package to be installed. Either install gifski or use another renderer.``
Personally, I would say that this is correct behaviour since it is clear what I need to do.

**Comment by gvelasq** [comment]
I experienced the same issue and agree with the suggestion.

It could be useful to have a `renderer_sitrep()` function similar to [`usethis::git_sitrep()`](https://usethis.r-lib.org/reference/git_sitrep.html) that returns a situation report on the installation status of the various renderers.

**Comment by JoFAM** [comment]
Same issue, agree with the suggestion and would like to add one. I couldn't get the example code of the getting started vignette working due to lack of `gifski`. Took me an hour before I realized it's not an imported but a suggested package. Got my students properly confused as well.

So my proposal: Indicate in the README and the Getting started vignette that `gifski` should be installed before trying the examples.

**Comment by thomasp85** [comment]
The current setup is obviously suboptimal. It was made in response to a CRAN takedown notice, and was rather rushed. The next release will include a (hopefully better) setup that will fix all this

**Comment by JoFAM** [comment]
@thomasp85 much indebted and thank you for your valuable work.
