### ISSUE TITLE
progress bar issue

### ISSUE THREAD

**Issue by roblanf** [thomasp85/gganimate#364]
Not sure if this is just something funny in my RStudio setup or what, but the progress bars from gganimate don't flush the line between updates, so I get something that looks like this:

Apologies if this is nothing to do with gganimate!! And thanks for a totally awesome package. Life-changing for looking at MCMC output.

![Screenshot 2019-12-10 16 29 32](https://user-images.githubusercontent.com/895251/70498457-8defae80-1b6a-11ea-88b6-d522dc50e023.jpg)

**Comment by JamesHWade** [comment]
Does this happen for all gganimate rendering or just some?

**Comment by roblanf** [comment]
All that I've seen (happy to test on anything you suggest though). I guess it's an issue with whatever progress bar package is being used, or with my RStudio (though it happens for me on multiple machines).

**Comment by JamesHWade** [comment]
Hmm... I'm not able to replicate, but I'll poke around a bit to see if I can come up with anything.

**Comment by johncmerfeld** [comment]
I'm seeing the same thing.
Wouldn't the solution be to add a `/n` at [this line](https://github.com/thomasp85/gganimate/blob/a75b7ed55b1c572821fbc5ad60efa92e1dc0b387/R/animate.R#L285)?

**Comment by jxu** [comment]
I have same issue on Windows, not on Ubuntu (iirc)

version
```
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again   
```

**Comment by jxu** [comment]
The progress bar is generated by progress_bar from package "progress".

So this issue is really https://github.com/r-lib/progress/issues/96

**Comment by jxu** [comment]
Updating RStudio worked for me btw
