### ISSUE TITLE
gganimate's .travis.yml file is trying to load ffmpeg from a location that no longer houses it

### ISSUE THREAD

**Issue by MattCowgill** [thomasp85/gganimate#365]
gganimate's `.travis.yml` file includes the following lines:

```
      - sourceline: 'ppa:jonathonf/ffmpeg-4'
      - sourceline: 'ppa:jonathonf/ffmpeg-3'
```

However, these PPAs appear to no longer be publicly available. See here: https://launchpad.net/~jonathonf

As a result, gganimate is failing on travis (I know because I have a fork).

**Comment by MattCowgill** [comment]
cool, happy to contribute

**Comment by thomasp85** [comment]
thanks:-)
