### ISSUE TITLE
Add library dependency or error message for package to combine images into videos

### ISSUE THREAD

**Issue by jhelvy** [thomasp85/gganimate#372]
I was teaching my students how to use **gganimate** in class yesterday, and every single student ended up with hundreds of png files (the frames of the animation) instead of a gif file. The exact same code ran perfectly on my computer, and created pngs on every one else's. Everyone did a fresh **gganimate** install, restarted R again, but same problem. Checked R versions, same problem.

After googling, I found [Thomas's answer](https://stackoverflow.com/questions/58991580/gganimate-returns-png-files-but-no-animated-object), which solved the problem.

Since **gganimate** won't be able to create a video without them, shouldn't the **gifski** or **png** libraries be included as dependencies? If you don't want to include those dependencies, it would be really helpful to get an error message that says "you need to install another package to combine images into videos" instead of allowing the code to run and produce a bunch of png files.

**Comment by thomasp85** [comment]
This should be live now in the latest version. It will check for the existence of either gifski, av, or magick at startup and give a startup message if none is found
