### ISSUE TITLE
Render issue - documentation doesn't seem correct.

### ISSUE THREAD

**Issue by jciconsult** [thomasp85/gganimate#375]
I understood from your documentation that the gifski_renderer was part of the default installation.
I have been using gganimate to produce gif files.  The results were quite large (4mb) for my project.  I wanted to stop the GIF from running in a loop so I used renderer = gifski_renderer(loop = FALSE)).  This required me to add the gifski package to my R environment.  What is the actual renderer used?  When I specified gifski_renderer, the result was a much smaller GIF.  I am confused.
1) what is the default renderer in the base package?
2) for web-type gifs, what is the best renderer?
3) is there anyway to stop the gif rewinding in the standard anim_save?

**Comment by thomasp85** [comment]
The default renderer depends on what is installed on your system... It will prefer gifski if found, but otherwise try magick and then av

This decision was made to reduce the dependencies of gganimate

I'll make the docs clearer on this
