### ISSUE TITLE
Using reorder_within in conjunction with gganimate

### ISSUE THREAD

**Issue by kbzsl** [thomasp85/gganimate#386]
Is it possible to use the `reorder_within` function (from `tidytext` package) in conjunction with `gganimate`?

I was trying to recreate the "racing barcharts". Instead a rank or rownumber (seen in shared solution),
I tried to use the `reorder_within` and the `scale_x_reordered` functions. The plot using the `facet_wrap` is ok, but I didn’t find a solution to "convert" this (facet_wrap) plot to an animation.
All the items belonging to different frames are included, not only those items which belongs to a particular frame.
![ex](https://user-images.githubusercontent.com/15076626/79662868-ff90d680-81b4-11ea-8629-9a32d1de0a2e.gif)

**Comment by thomasp85** [comment]
That is not possible no - currently scales stay fixed in gganimate.

You can see an example of creating a racing bar chart with gganimate here: https://evamaerey.github.io/little_flipbooks_library/racing_bars/racing_barcharts.html
