### ISSUE TITLE
Rounding not working with animation of geom_text and geom_label

### ISSUE THREAD

**Issue by chemdork123** [thomasp85/gganimate#387]
I'm posting this issue after [seeing this post on SO](https://stackoverflow.com/questions/61178924/r-how-can-i-make-an-offset-label-not-show-decimal-places-during-an-animation/61332160#61332160).  I was [able to find a workaround](https://stackoverflow.com/a/61332160/9664796), but I still think it might be a bug or at least want to know _why_ this happens.

When plotting with `geom_text`, `geom_label` (or those from `ggrepel`), rounding "works" when you create the plot, but not after animating.  Best described by this example:

```
# dummy data frame
df1 <- data.frame(x=rnorm(10,1,0.1), y=rnorm(10,1,0.1), t=1)
df2 <- data.frame(x=rnorm(10, 1, 0.12), y=rnorm(10, 1, 0.12), t=2)
df3 <- data.frame(x=rnorm(10, 1, 0.15), y=rnorm(10, 1, 0.15), t=3)
df <- rbind(df1, df2, df3)

# the plot
p <- ggplot(df, aes(x,y)) + geom_point() + xlim(0.5,1.5) + ylim(0.5,1.5) +
    geom_text_repel(aes(label=round(y,2)))
```
![a](https://user-images.githubusercontent.com/3249303/79801818-d1360700-832c-11ea-9810-d88640e49abe.png)

```
# animation shows "unrounded" labels:
p + transition_time(t)
```

![a boo](https://user-images.githubusercontent.com/3249303/79801747-aea3ee00-832c-11ea-869d-2c4b2113b6df.gif)

```
# workaround using as.character
p <- ggplot(df, aes(x,y)) + geom_point() + xlim(0.5,1.5) + ylim(0.5,1.5) +
    geom_text_repel(aes(label=as.character(round(y,2))))
p + transition_time(t)
```
![a round](https://user-images.githubusercontent.com/3249303/79801872-eb6fe500-832c-11ea-8b28-ef6e1416a836.gif)

Is this a known bug or "working as intended" here?  Not sure if this works similarly with other text that gets "adjusted" before making it to the plot.

**Comment by thomasp85** [comment]
It is sort of in-between. Numeric values will be tweened which means that no matter how you round the values in the static version, intermediate values will always be calculated.

This is mainly an issue for `geom_text()` and the "fix" is indeed to treat them as character strings instead...

I do want to find a better solution for this though, but haven't yet
