### ISSUE TITLE
transition_layers() examples don't work

### ISSUE THREAD

**Issue by drwilkins** [thomasp85/gganimate#390]
The examples in the transtition_layers() help don't work for me:

> anim <- ggplot(mtcars, aes(mpg, disp)) +geom_point() +geom_smooth(method="lm",colour = 'springgreen', se = FALSE) +
>   geom_smooth(method="lm",aes(colour = factor(gear))) +
>   transition_layers(layer_length = 1, transition_length = 1) +
>   enter_fade() + enter_grow()

gives me:

> `geom_smooth()` using formula 'y ~ x'
`geom_smooth()` using formula 'y ~ x'
Error in transform_path(data[0, ], data, ease, enter_length, NULL, enter,  : 
  transformr is required to tween paths and lines

**Comment by thomasp85** [comment]
yeah - the transformr package is required to tween lines and polygons. It is not a hard dependency because transformr depends on sf which is rather big.
