### ISSUE TITLE
directed graph in gganimate 

### ISSUE THREAD

**Issue by TriageDr** [thomasp85/gganimate#394]
Hi Thomas, 
I'm working on a directed graph dataset and want to make a gganimate of the directed graph over time. Each edge has a year associated with it, so my aim is to make an animation that shows the directed graph growing over time.  I was able to repurpose my data using your code here: https://gist.github.com/thomasp85/c8e22be4628e4420d4f66bcc6c88ac87. 

Creation of the timebins in the edges worked and I'm able to make all the  necessary objects for visualization: 

subGr <- subgraph.edges(edgesGraph, which(E(edgesGraph)$delay == 0))
V(subGr)$degree <- degree(subGr)
V(subGr)$group <- cluster_edge_betweenness(subGr)$membership
lay <- create_layout(subGr, layout = 'igraph', algorithm = 'lgl')
attr(lay, 'graph') <- edgesGraph

My Error occurs during the plot creation phase, specifically on the function gEdges 
**Error in gEdges(nodePar = "group") : could not find function "gEdges"
In addition: Warning message:
Ignoring unknown aesthetics: frame**

p <- ggraph(data) + 
  geom_node_point(aes(size = degree, colour = factor(group))) + 
    geom_edge_link(aes(frame = timebins, alpha = delay, width = delay), edge_colour = '#dccf9f') + 
    geom_edge_link0(aes(frame = timebins, alpha = delay, width = delay, colour = factor(node1.group)), data = gEdges(nodePar = 'group')) +  
  scale_edge_alpha(range = c(1, 0), guide = 'none') + 
  scale_edge_width(range = c(0.5, 1.5), trans = 'exp', guide = 'none') + 
  scale_size(guide = 'none') + 
  ggtitle('Temporal Ordering of Edge Attachment') +
  ggforce::theme_no_axes() + 
  theme(plot.background = element_rect(fill = '#000000'), 
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        plot.title = element_text(color = '#000000'),
        legend.position="none") 

Hope to hear from you some time -- awesome data visualization packages!

**Comment by thomasp85** [comment]
Hi - `gEdges()` is not an exported function from ggraph. Use `get_edges()` instead 🙂
