### ISSUE TITLE
Memory Exhausted

### ISSUE THREAD

**Issue by awgymer** [thomasp85/gganimate#399]
I am trying to plot an animated map.

```
world <- ggplot() +
  borders("world", colour = "gray85", fill = "gray80") +
  ggthemes::theme_map() 

map <- world + geom_polygon(data=w1, aes(x=long, y=lat, group=paste0(group, reldate), fill=as.numeric(age))) 

ani <-  (
  map + 
    labs(title = 'Date: {frame_time}') + 
    transition_time(reldate) +
    scale_fill_gradient(high='#236B1E', low='#bdd2bb')
)

animate(ani, nframes = 10000, renderer=ffmpeg_renderer(format='webm'))
Error: vector memory exhausted (limit reached?)
```

If I reduce to 1000 frames it works but takes a very long time and uses all my memory (32GB and peaks at 41GB registered by Activity Monitor). 

The `w1` dataframe has 7 million rows, which represent data spread across 130 distinct dates. I tried to run `file_renderer` thinking that it might reduce the load by outputting frames 1 by 1 but that doesn't appear to be the case and I just got the following error:

```
Error in (function (plot, frames, device, ref_frame, ...)  : 
  formal argument "frames" matched by multiple actual arguments
``` 

Is there any way to improve the memory load here or am I just trying something unreasonable?

**Comment by thomasp85** [comment]
I can't say that it is unreasonable, but it will not work with how gganimate is currently implemented. As it is now gganimate calculates that data for all frames up front and 10000 frames will result in a lot of data for most animation...

I do want to change this down the line but cannot give an estimate of how long it will take
