### ISSUE TITLE
FR: clearer error message on transformr error

### ISSUE THREAD

**Issue by ColinFay** [thomasp85/gganimate#406]
Hey, 

I just bumped into this error: 

```r
Error in transform_path(all_frames, states[[i]], ease, nframes[i], !!id,  : 
  transformr is required to tween paths and lines
```

And it took me a google search to understand what it meant. 
I think this message can be a little bit unclear if you've never heard of `{transformr}` before: would you consider making it more explicit that it's a package needing to be installed? 

I think something like "Error: the transformr package is required " would really benefit how users can handle this error. 

Cheers, 
Colin

**Comment by thomasp85** [comment]
You are right - Thanks
