### ISSUE TITLE
transition_time with shadow mark for only one geom

### ISSUE THREAD

**Issue by tjebo** [thomasp85/gganimate#407]
Just wondered if this could be a thing:

When using `transition_time`, to create a shadow mark for only one geom (e.g., for labelling)?

As a workaround, one could also create two plots (the plot and the title) and combine them, e.g., with patchwork, but I don't know how to use gganimate with patchwork or others. 
   
``` r
library(ggplot2)
library(gganimate)

myfoo <- data.frame(time = 1:100, x = 1:100, y = 1)

p <- 
  ggplot(myfoo) +
  geom_point(aes(x, y)) +
  geom_text(aes(x = 0, y = 0, label = time))

p_anim <- 
  p +
  transition_time(time) +
  shadow_mark()

animate(p_anim, height = 150, width = 250)
```
![](https://i.imgur.com/0lFUHT2.gif) The label in the bottom left should not have a shadow mark. 

What I am looking for is something like the following:
```
p_title <- 
  ggplot(myfoo) +
  geom_point(aes(x, y)) +
  labs(title = "{frame_time}")

p_title_anim <- 
  p_title +
  transition_time(time) +
  shadow_mark()

animate(p_title_anim, height = 150, width = 250)
```

![](https://i.imgur.com/fzp513T.gif) The interactive element from the title should be a plot annotation.

**Comment by thomasp85** [comment]
You can just use the `exclude_layer` argument in `shadow_mark()`

e.g.

```r
p_anim <- 
  p +
  transition_time(time) +
  shadow_mark(exclude_layer = 2)
```
