### ISSUE TITLE
Arrow pointing wrong direction using transition_reveal

### ISSUE THREAD

**Issue by petersmp** [thomasp85/gganimate#409]
I have simple plot:

    sample_data <-
      data.frame(
        x = 1:100
        , y = 1:100
      )
    
    temp_plot <-
      ggplot(sample_data
             , aes(x = x
                   , y = y)) +
      geom_line(
        size = 3
        , arrow = arrow()
        , lineend = "round"
        , linejoin = "round"
      ) +
      theme_minimal()

that looks like this:

[![enter image description here][1]][1]

And I want to animate it with `gganimate` like so:

```
temp_animate <-
  temp_plot +
  transition_reveal(x)

```
    anim_save("temp_animate.gif"
              , temp_animate
              , "~/Downloads/"
              , end_pause = 10)

However, when I do, the arrow is pointing the wrong direction right up until the very last frame (paused to make it clear that it is correct at that point).

[![enter image description here][2]][2]

I've tried playing with the values in `arrow` (including various angles, including negative) but nothing that I do seems to correct the orientation of the arrow (which should point along the current vector in each frame).

How can I get the arrow to point in the correct direction throughout? (I am cross-posting this on [StackOverflow](https://stackoverflow.com/q/64069501/2966222)).

  [1]: https://i.stack.imgur.com/Am7hM.png
  [2]: https://i.stack.imgur.com/89aJB.gif

**Comment by petersmp** [comment]
User Z.Lin on StackOverflow stated that the issue occurs due to conflicts when the tweening of the position generated by `transition_reveal` lands at the same location as a data point in the original data set. She built an alternative version of `transition_reveal` to handle this behavior. I suggest considering it for inclusion in the next update if it does not conflict with anything else.

Her full answer is [here](https://stackoverflow.com/a/64135523/2966222).

**Comment by jiaangou** [comment]
Not sure if this is the same problem, but my arrows are switching direction right at the transition point, then back to the original direction as it progress. 

`
samp <- data.frame(year = seq(1990, 2020, by = 3),
                   y = rpois(11, 5))

samp_p <- samp%>%
  ggplot(aes(x = year, y = y))+
  geom_path(arrow = arrow(length = unit(0.3,"cm")))+
  theme_bw()


samp_p + transition_reveal(year)
`
