### ISSUE TITLE
export set_last_animation?

### ISSUE THREAD

**Issue by mjskay** [thomasp85/gganimate#416]
I was wondering if you would be willing to export `set_last_animation()`? I'm working on a package ([plinko](https://mjskay.github.io/plinko/)), and I am currently using `set_last_animation()` internally (via `:::`) so that `gganimate::anim_save()` can be used easily to save animations output by the package. 

However, should I ever wish to push this package to CRAN I would either have to stop using `gganimate:::set_last_animation()` or obfuscate the usage of `:::` to avoid CRAN checks (neither of which is ideal). If `set_last_animation()` were exported I could avoid such ugliness.

**Comment by thomasp85** [comment]
I'm fine with this, but it will not happen before I take up development of gganimate again sometime next year (had hoped for it this fall, but this has been an unpredictable year)

**Comment by mjskay** [comment]
Cool thanks, much appreciated! I'm not in any rush
