### ISSUE TITLE
matrix visualize

### ISSUE THREAD

**Issue by PankajChohan9820** [thomasp85/gganimate#417]
if we have npy frames can we visualize as video from that in gganimate?

**Comment by PankajChohan9820** [comment]
my frames are 3000xmxn and I want to make a video with hiighest fps can we do that in gganimate?

**Comment by thomasp85** [comment]
I'm honestly not sure what you mean. What is "npy"?

**Comment by PankajChohan9820** [comment]
npy is basically numpy array means a matrix. Let say I've 1000 matrix of 10x10 or 1000 images u can say for easy which are in sequence and I want to visualize in gganimate.

**Comment by thomasp85** [comment]
So, you are working with python through reticulate?

sure, you could do that with gganimate, but the fastest way would probably be to just convert each slice to raster and plot it, then assemble it with the av package.

**Comment by PankajChohan9820** [comment]
Yeah that would be easy but the framerate is getting less around 30 even openCv gives 60fps I want around 100fps which I think gganimate can provide.

**Comment by thomasp85** [comment]
gganimate uses av to render video. You can set the frame rate in the function call: https://docs.ropensci.org/av/reference/capturing.html

**Comment by PankajChohan9820** [comment]
that helps a lot and this maybe the last question I would ask as I dont want to waste your time as you helped me a lot how can pass my matrix (56x224) as an input in gganimate? can u give me example of matrix input in ggplot?

**Comment by thomasp85** [comment]
you'd either need to convert it to long format, so you'd have a data.frame with `x`, `y`, and `value` and use `geom_raster()` or use `annotation_raster()` (you may need to convert the matrix to a raster object first, I can't remember)
