### ISSUE TITLE
Failure to render after warning (file_renderer failed to copy frames to the destination directory ) Mac OS

### ISSUE THREAD

**Issue by joseph-rickert** [thomasp85/gganimate#419]
A basic example from the gganimate pdf produces output but will not render

MAC os catalina 10.15.7
RStudio v 1.4.869
gganimate 1.0.7

library(gganimate)
anim <- ggplot(mtcars, aes(mpg, disp)) +
  transition_states(gear, transition_length = 2, state_length = 1) +
  enter_fade() + exit_fade()
anim

There is a warning after the last output line:100 /var/folders/w0/skxpg0h51jg72m5b01y_8n_c0000gn/T//RtmpScY1KY/146b91055849a/gganim_plot0100.png
Warning message:
file_renderer failed to copy frames to the destination directory

**Comment by thomasp85** [comment]
That would only happen if you do not have write access to the current working directory...

But it is also only using the file_renderer by default if you have not installed any of the renderer packages such as gifski
