### ISSUE TITLE
Cannot install `gganimate-0.1.1`

### ISSUE THREAD

**Issue by kusalhettiarachchi** [thomasp85/gganimate#423]
I tried installing gganimate package version 0.1.1 using,

1. Directly compiling the source. Although the package is installed in the library and I get the response correctly when I run the command `packageVersion("gganimate-0.1.1")`, I still get the following error when I try to load the library.

> Error in library("gganimate-0.1.1") : 
there is no package called ‘gganimate-0.1.1

2. I tried running the command `install_github("thomasp85/gganimate", ref = "v0.1.1")` (after loading `library(devtools)`) and I'm getting this error 

> Error : (converted from warning) C:/Users/abc/AppData/Local/Temp/RtmpUVzZBv/R.INSTALL222cebd2624/gganimate/man/gganimate_save.Rd:19: unexpected RCODE '[pkg=ggplot2]{ggsave', expecting '{'
ERROR: installing Rd objects failed for package 'gganimate'

What am I missing here? Any help is appreciated. TIA

PS: Output of my `version`

> platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out`

**Comment by thomasp85** [comment]
the old version is not in any way supported or guaranteed to work with newer packages... However it seems like this is simply a warning that gets converted to an error by devtools/remotes

You can turn that off with `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = 'true')` before trying to install
