### ISSUE TITLE
extra pause in transition_layers() 

### ISSUE THREAD

**Issue by jcaude** [thomasp85/gganimate#424]
Hello,

My goal is to animate subpart of a multilayer plot. For example a static set of points with some animation using just enter/exit effects. For this purpose I use transition layer + tweening as shown in the toy code below:

```r
point_A <- tibble(x = 1, y = 1)
point_B <- tibble(x = 2, y = 1)

p <- ggplot(point_B, aes(x=x,y=y)) +
  geom_point(data = point_A, aes(x=x,y=y), size = 4) + 
  geom_point(size = 4) + 
  xlim(0,3) +
  ylim(0,2)

anim <- p + transition_layers(layer_length = 0, transition_length = 1, 
                              from_blank = FALSE, keep_layers = c(Inf, 0)) + 
  enter_fade() + enter_grow() +
  ggtitle('Transition state: {transitioning}',
          subtitle = '{closest_layer} of {nlayers}')
```
I was expecting a loop over two states (one per layer/geom_point), but after the second one there is an additional animation step (transition_layers as transitioning & closest_layer equals NA) that introduces a pause in the animation.. 

Besides, if I execute the same code adding `exit_fade() + exit_shrink()` the time to perform these exit_ tweenings is exactly the same as the "pause" mentioned above.. I don't know if it's expected or if it's an issue, that's why I report it here.

... if anyone has a better suggestion to perform this kind of animation I would greatly appreciate any help. 

jC

btw/ thomas thx for this great package.

**Comment by thomasp85** [comment]
honestly I can't remember - I'll look into it 🙂

**Comment by thomasp85** [comment]
The culprit is your `keep_layers = c(Inf, 0)` setting - it basically says that the second layer should not be kept and the animation will include a part where it exits (you can see that by adding `+ exit_fade()` to your animation code

To avoid this simply set `keep_layers = TRUE`
