### ISSUE TITLE
frame_along shows local time instead of time in the original data frame

### ISSUE THREAD

**Issue by sanjay-k7r** [thomasp85/gganimate#425]
Firstly, thank you for the fantastic package!

Here is what I used for my time series data: 

```
anim <- transition_reveal(along=df$date) +
  ease_aes('sine-in-out')+
  ggtitle("Date: {frame_along}")
```

Where df$date is of type POSIXct and was recorded in another time zone (Australia)

This creates an animation. However, the Date: {frame_along} prints the time to my local time (Germany)

Expected behaviour - The original timestamp is shown.

**Comment by sanjay-k7r** [comment]
In case someone has this issue:
A workaround is to use Sys.setenv(TZ='whatever timezone your data was in ')
e.g. Sys.setenv(TZ='Australia/Melbourne')

**Comment by thomasp85** [comment]
This is really an issue around glue and the standard formatting of dates and times... 

If you do `glue("Date: {time_object}")` with `time_object` being a global variable I expect you get the same behaviour?
