### ISSUE TITLE
transition_reveal - minor issue with along variable naming???

### ISSUE THREAD

**Issue by will-rogers** [thomasp85/gganimate#427]
I spent the last few hours trying to figure out why a dataset of mine would not render. I have a static set of rasters with GPS points above them (different datasets and var names). I was able to render this when using a point-specific time variable - but I needed to bin times for plotting simplicity and named the new vector "time". When i just plotted points (commenting our the rasters on my ggplot code) the render was great! But, when adding back in the rasters, something was not running right and I got this cryptic error message 
"Error: along data must either be integer, numeric, POSIXct, Date, difftime, orhms
In addition: Warning messages:
1: In min(cl[cl != 0]) : no non-missing arguments to min; returning Inf
2: In min(cl[cl != 0]) : no non-missing arguments to min; returning Inf". 

I figured it was an issue with the "time" variable not showing up in the dataset, so I tried to track that down. I finally just decided to change the variable name from "time" to "tween.here". 

I think somewhere in the core of the code or helper functions "time" must be an introduced variable, hence the error when using it as an "along" tween. I don't know why it works to use "time" with only dynamic parts of the ggplot code, but fails with both static and dynamic. I don't really know how to create a minimal reproducible example of this, but maybe others have found a similar bug?

Idk, maybe this is just an intricacy of my code/data - but hopefully, this helps save a few hours for others.

**Comment by thomasp85** [comment]
Can I get you to post a reprex and I'd be happy to look into a fix
