### ISSUE TITLE
Animating Histograms gives weird graphs

### ISSUE THREAD

**Issue by lselzer** [thomasp85/gganimate#43]
I tried to animate histograms but I get this weird result

```library(ggplot2)
library(gganimate)
library(dplyr)

dtf <- replicate(10, data.frame(x = sample(1:10, 10, TRUE)), simplify = FALSE) %>% 
  do.call(rbind, .) %>% 
  mutate(frame = rep(1:10, each = 10))
p <- ggplot(dtf, aes(x)) +
  geom_histogram(aes(y = ..density.., frame = as.factor(frame)), 
                 binwidth = 1, fill = "transparent", colour = "grey10")
gganimate(p)
```
![test](https://cloud.githubusercontent.com/assets/411740/24337858/51700d1e-1277-11e7-904b-bfdbf32e36f0.gif)

I tried to look what is wrong but I couldn't get past what `ggplot_gtable()` is doing

**Comment by vadimus202** [comment]
I had the same problem animating `geom_col()` or `geom_bar()`. The animation shows incremental changes. Any ideas for a workaround?

```
df <- data.frame(frame = rep(1:10, each=10),
                 x = LETTERS[1:10] %>% rep(10),
                 y = sample(1:10, 100, replace = TRUE))

p <- ggplot(df, aes(x,y,frame=frame)) +geom_col()

gganimate(p)
```
![junk](https://cloud.githubusercontent.com/assets/7230548/26756375/2344ae8a-486f-11e7-96af-d2e6a63f83c0.gif)

**Comment by edwardoughton** [comment]
Using position = 'identity' worked for me. See here: 

https://stackoverflow.com/questions/35731811/gganimate-issue-with-geom-bar
