### ISSUE TITLE
transition_time

### ISSUE THREAD

**Issue by EliseD34** [thomasp85/gganimate#430]
Thanck you for this package.
I've been working on the population evolution, but when animate the plot with transition_time, some of the images are green and the gif flashes in green.

I don't know how to fix this.
Thanck you for your help.

This is the code I 've used
```
ggplot(population_princ, aes(x=Annee, y=Population, group = Annee, Commune = Commune)) +
  geom_line(size = 1)+
  labs(title="Evolution de la population de 1881 à 1999 dans l'Hérault",
       x="Années",
       y="Population",
       color="") +
  theme_light() +
  theme(panel.grid.minor.y = element_blank(), panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) +
  scale_colour_manual(values = couleurs) +
  transition_time(year)
```

**Comment by thomasp85** [comment]
related to #431 — unfortunately there is nothing gganimate can do about it. You may use the `magick_renderer()` or `av_renderer()` instead
