### ISSUE TITLE
Feature request - use of expressions in animated labels

### ISSUE THREAD

**Issue by tjebo** [thomasp85/gganimate#439]
background - stackoverflow https://stackoverflow.com/questions/67089930/not-getting-the-desired-title-in-gganimate-animated-labels-with-expression

The below is the original plot posted by the OP. No matter what combination I tried with `paste`, `expression`, `parse`, `substitute`, inside or outside of `{...}` (thinking this might do the trick kind because of the glue syntax), it either correctly parsed the expression (as in below) or the changing label, but never both. 
``` r
library(gganimate)
#> Loading required package: ggplot2
ggplot(mtcars, aes(wt, mpg)) + 
  geom_point() + 
  transition_states(hp) +
  labs(title = expression('Hp = {closest_state}' ~ m^2 ~ m^-2))
```

![](https://i.imgur.com/OZyYfPO.gif)

<sup>Created on 2021-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

One workaround was suggested with the `ggtext` package which allows at least sub/supscript, but it fails with any more complex expression.

**Comment by tfjaeger** [comment]
Is this something under development? I'm running into the same limitation. Trying use plotmath functionality combined with reference to gganimate variables like {closest_state}. Thank you.
