### ISSUE TITLE
Is it possible to use gganimate to plot a time series in real time i.e in milliseconds, as denoted by one axis?

### ISSUE THREAD

**Issue by sebsilas** [thomasp85/gganimate#440]
I would like to use gganimate to plot a time series in real-time, using the values on the x-axis, which are the time the event should occur after the origin in milliseconds. Is this (easily) possible?

An example of the dataset would be the following, where x is the time in millseconds from where the x/y point should be plotted from initialising the plot:

```
df <- data.frame(x = c(2078, 2525, 2995, 3448, 3942, 4452, 4824, 
                            4998, 5445, 5973, 6478), 
                    y = c(55, 58, 55, 54, 53, 48, 49, 56, 59, 57, 56))
```

**Comment by thomasp85** [comment]
This is not easily possible at the moment. You'd have to do some back-of-the-envelope calculations to match the length of the animation with the duration of the transition
