### ISSUE TITLE
gganimate object rendering output time

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [thomasp85/gganimate#442]
I am using gganimate for the first time and I am using in to render a[ generative art](https://github.com/cutterkom/generativeart) animation. My large gganim object is 12.5 MB in size and `animate()` has been running for about 30 minutes.
Does it take too long to render a 12.5 MB output? How can speed up the process?
Reference code [here](https://szczesnypawel.medium.com/animating-generative-art-r-with-gganimate-and-generativeart-packages-51725407e51d).

Edit:

Code ran for about 50 minutes and then gave this error:
`Error: vector memory exhausted (limit reached?)`

**Comment by thomasp85** [comment]
it very much depends. The way gganimate works under the hood is that it generates all the data for all the frames before beginning to plot it. This is often a good idea for short data animations as it leverages Rs vectorisation but it completely falls apart for longer animations with larger data as the data expansion can eat away the memory.

For now there is no way around this making gganimate not practical for some purposes
