### ISSUE TITLE
Feature request: Add muted, loop, and controls as options in video_file()

### ISSUE THREAD

**Issue by mccarthy-m-g** [thomasp85/gganimate#444]
Autoplay is currently switchable in `video_file()`, but muted, loop, and controls are not. Adding these switches would allow users to include videos in HTML documents that behave like GIFs by using a video tag with autoplay, muted, and loop, but no controls.

The main benefit of this is that videos tend to be much smaller and of higher quality than a GIF of the same content, which would be useful for users sharing their animations on the web. [This article](https://www.popularmechanics.com/technology/a21457/the-gif-is-dead-long-live-the-gif/) has some interesting history and discussion on the topic, noting that videos masquerading as GIFs are commonplace on the web now.

**Comment by thomasp85** [comment]
The switch resides in `as_html_video()` - do you envision the other features to be there as well?

**Comment by mccarthy-m-g** [comment]
Yeah, I think they would make sense there too
