### ISSUE TITLE
Is `sf` layers supported or not?

### ISSUE THREAD

**Issue by CGMossa** [thomasp85/gganimate#446]
Hey!

I'm currently getting this error `Error: sf layers not currently supported by transition_reveal`.
I'm perplexed by this as: I cannot see where this error is coming from.
There are blogposts / tutorials using `geom_sf` and `gganimate`. 
Looking around the issues here: I've installed dev versions of `gganimate`, `transformr` and `tweenr`. 

So, is there a support for sf layers or is my machine misconfigured somehow?

Thanks!

**Comment by CGMossa** [comment]
Other `transitions_` seem to work. :)

**Comment by thomasp85** [comment]
yes... there are sadly still limitations with which reveal types have support for polygons and sf
