### ISSUE TITLE
Animation progress triggered by user input

### ISSUE THREAD

**Issue by royfrancis** [thomasp85/gganimate#451]
This is probably beyond the scope of this package, but I will leave this here as a thought. Just wondering about the feasibility of controlling animation progress using user input.

Say, there are 3 states. Have the animation start and stop at state 1. There is a user input (press a key etc), the animation proceeds to state 2 and stops. Further user input to progress to state 3 etc.

Kind of like powerpoint. Animation pauses at breakpoints and further progress is triggered by user input.
This would be so useful in a teaching context so the whole animation doesn't just play out completely.

**Comment by jonspring** [comment]
I have done this in a powerpoint deck by rendering the animation in pieces and putting each on a different slide.

**Comment by thomasp85** [comment]
Yes, this is the purpose of the `split_animation()` function
