### ISSUE TITLE
error while trying to load gganimate

### ISSUE THREAD

**Issue by Aliya-Caldwell** [thomasp85/gganimate#456]
Hi,

When I try to load gganimate (regardless of load method), R throws the following error:

```{r}
Error: package or namespace load failed for ‘gganimate’ in namespaceExport(ns, exports):
 undefined exports: progress_bar
```
I am on a windows computer running R 4.1.2, the same as my mac on which gganimate loads just fine. I have tried deleting and redownloading gganimate from my library, have tried downloading it using devtools and without using devtools, and have tried updating all associated packages to no avail. 

I have seen people post about similar errors thrown for other packages, but still haven't found a solution that works for gganimate.

**Comment by thomasp85** [comment]
Is this still an issue. If so I'd suggest it is an issue with the progress package
