### ISSUE TITLE
Images becoming blurry

### ISSUE THREAD

**Issue by heerymichael** [thomasp85/gganimate#463]
Hi 

I was hoping I could get help with a general query.  I can add code if needed but the one I have is quite detailed and would need to think how to scale back.

I am creating a gganimate line chart video.  The lines "grow" from png headshots that I add to the plot using geom_image.

When I print out a static ggplot image these are crystal clear but in gganimate they become quite blurry?  Is there any way to protect the quality of these?

I have built them into the ggplot from a separate data frame (with only the 6 relevant images) than the lines which has lots of rows?

Hope this makes sense and appreciate any help you can offer

Michael

**Comment by thomasp85** [comment]
My best guess is that you need to increase the quality settings during the rendering - the defaults are set for speed and size, not quality - see the last example in the `animate()` docs
