### ISSUE TITLE
Animate and anim_save not working. 

### ISSUE THREAD

**Issue by mdubeau20** [thomasp85/gganimate#464]
Just yesterday these commands were working with the gg objects I had created. What's interesting is that the animations will render if I run them through ggplot but not when I specify "animate". Any idea what the issue could be? I've restarted R and my machine. I've also redownloaded the gganimate package, to no avail. 

Here's the code and errors I've received. 

res_remodel_animate <- plot_usmap(data = Res_Remodeler_all, values = "oty_annual_avg_estabs_chg") +
  scale_fill_stepsn(breaks=c(as.numeric(quantile(Res_Remodeler_all$oty_annual_avg_estabs_chg,seq(0,1,.15,)))),
                    colors=c("blue","red", "green", "yellow")) +
  labs(title =  'Change in number of Residential Remodelers by County from {as.integer(frame_time)}',
       fill = "Change in Number of Businesses") +
  theme(legend.position = "right")
  
res_remodel_animate + transition_time(year, range = c(2014,2021))

animate(res_remodel_animate, height = 800, width = 800, renderer = ffmpeg_renderer())

Error in animate.default(res_remodel_animate, height = 800, width = 800,  : 
  animation of gg objects not supported

Thanks for the help.

**Comment by thomasp85** [comment]
you never save the changes to `res_remodel_animate` back to the variable so `res_model_animate` is still a simple static ggplot2
