### ISSUE TITLE
Area chart does not render

### ISSUE THREAD

**Issue by avrenli2** [thomasp85/gganimate#476]
The animated chart does not render properly and it creates the following error messages:

**Error occurred in the 1st layer.
Caused by error in `unit()`:
'x' and 'units' must have length > 0
Problem while converting geom to grob.**

```r
library(ggplot2)
library(Rcpp)
library(gifski)
library(gganimate)
library(transformr)

library(quantmod)
CHAI <- getSymbols("SBUX" , from="2020-1-1" , to="2021-1-1" , auto.assign=F) 

CATROON <- ggplot(CHAI, aes(y=SBUX.Close,x=index(CHAI)))+
  geom_area(color="pink", size=1.2 , fill="pink" , alpha=0.3)+
  geom_point(color="#8F157E", size=4)+
  labs(x="Time", y="Close Price")+
  theme_bw() + transition_reveal(index(CHAI))  

animate(CARTOON, duration=7 , fps = 30)
```

**Comment by DavisVaughan** [comment]
See more information in https://github.com/r-lib/vctrs/issues/1778

**Comment by thomasp85** [comment]
this is not really an issue with vectors but an incompatibility between the way gganimate works and the new `stat_align()`

A quick fix is to let `geom_area()` use `stat_identity()` as in the old days

```r
CARTOON <- ggplot(CHAI, aes(y=SBUX.Close,x=index(CHAI)))+
  geom_area(color="pink", size=1.2 , fill="pink" , alpha=0.3, stat = "identity")+
  geom_point(color="#8F157E", size=4)+
  labs(x="Time", y="Close Price")+
  theme_bw() + transition_reveal(index(CHAI))  

animate(CARTOON, duration=7 , fps = 30)
```

**Comment by thomasp85** [comment]
This particular combination (`stat_align()` and `transition_reveal()`) now throws an error with information on how to fix it

another fix is to transition after the stat has been applied using `transition_reveal(after_stat(x))`
