### ISSUE TITLE
Laundry list of errors

### ISSUE THREAD

**Issue by ghost** [thomasp85/gganimate#54]
Just tried every install from devtools and every recommendation posted here, but I keep getting a laundry list of errors.

Here's my source simulating a few correlated datasets, plotting them, and attempting to use gganimate to animate them:

````
library(ggplot2)
library(gganimate)

meanx1=0  #mean of the predicted distribution.
sdx1=1    #SD of the predicted distribution.
meany1=0  #mean of the actual distribution.
sdy1=1    #SD of the actual distribution.
n=100    #sample size for both distribution.

data = data.frame(matrix(ncol = 3, nrow = 0))
colnames(data) <- c("r","x1","y1")

for (i in -99:-89){ 
  r = i/100
  x1 = rnorm(n=n, mean=meanx1, sd=sdx1) #Simulated x 
  y0 = rnorm(n=n, mean=meany1, sd=sdy1)
  y1 = x1*r+y0*(1-r^2)^0.5
  df = data.frame(r,x1,y1)
  data = rbind(data,df)
}

p = ggplot(df) +
  aes(x = x1, y = y1, frame = r) +
  scale_x_continuous(limits = c(-3,3)) +
  scale_y_continuous(limits = c(-3,3)) +
  geom_point(alpha = 0.4) +
  theme_bw()

gganimate(p)

````

Here's the errors:

I cannot find ImageMagick with convert = "magick"
I also cannot find ImageMagick with convert = "convert"
but I can find it from the Registry Hive: C:\Program Files\ImageMagick-7.0.6-Q16
Executing: 
"C:\Program Files\ImageMagick-7.0.6-Q16\convert.exe -loop 0 -delay 100 Rplot1.png
    "filefc4daa22d8.gif""
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
an error occurred in the conversion... see Notes in ?im.convert
Error in file(file, "rb") : cannot open the connection
In addition: Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c "C:\Program Files\ImageMagick-7.0.6-Q16\convert.exe" --version' had status 1 
2: running command 'C:\WINDOWS\system32\cmd.exe /c magick --version' had status 1 
3: running command 'C:\WINDOWS\system32\cmd.exe /c convert --version' had status 4 
4: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Program Files\ImageMagick-7.0.6-Q16/convert.exe": The system cannot find the file specified
5: running command 'C:\WINDOWS\system32\cmd.exe /c "C:\Program Files\ImageMagick-7.0.6-Q16\convert.exe -loop 0  -delay 100 Rplot1.png "filefc4daa22d8.gif""' had status 1 
6: In cmd.fun(convert) :
  '"C:\Program Files\ImageMagick-7.0.6-Q16\convert.exe -loop 0  -delay 100 Rplot1.png "filefc4daa22d8.gif""' execution failed with error code 1
7: running command '"C:\Program Files\ImageMagick-7.0.6-Q16\convert.exe -loop 0  -delay 100 Rplot1.png "filefc4daa22d8.gif""' had status 127 
8: In file(file, "rb") :
  cannot open file 'C:\Users\AJTHUR~1\AppData\Local\Temp\RtmpgvOP9S/gganimate\filefc4daa22d8.gif': No such file or directory
>

**Comment by GBIAN2** [comment]
I have the same problem. And there are bunch of discussions on this problem. The package needs to be modified and updated.

**Comment by ghost** [comment]
@GBIAN2 I think I was able to get an example running with gganimate after installing the package magick.  I think gganimate depends on it.  Not sure where I found this answer as it has been a month since I touched this.  I agree, this package needs to be updated or at least not broken in updates...

Try this:
`install.packages("magick")`
`library(gapminder)`
`library(ggplot2)`
`library(magick)`
`img <- image_graph(res = 96)`
`datalist <- split(gapminder, gapminder$year)`
`out <- lapply(datalist, function(data){`
`  p <- ggplot(data, aes(gdpPercap, lifeExp, size = pop, color = continent)) +`
`    scale_size("population", limits = range(gapminder$pop)) +`
`    scale_x_log10(limits = range(gapminder$gdpPercap)) +`
`    geom_point() + ylim(20, 90) +  ggtitle(data$year) + theme_classic()`
`  print(p)`
`})`
`dev.off()`
`animation <- image_animate(img, fps = 2)`
`image_write(animation, "animation.gif")`

**Comment by johnmackintosh** [comment]
You need to install  ImageMagick (or perhaps at least install the 'magick' r package
If using Windows, when installing ensure you tick the "install legacy utilities" box, (which may explain the "I cannot find ImageMagick with convert = 'convert'" error. Also you should ensure you select the option to add ImageMagick to the system Path variable.

Assuming you have an up to date R install, and the most recent version of ImageMagick, I found my initial plotting issues were resolved by reinstalling ImageMagick and selecting both of these options during setup

**Comment by aneisse** [comment]
Regarding the "I cannot find ImageMagick with convert = "magick" or "convert" issue, it's just like @johnmackintosh said. Also, you can fix it manually if there's at least one of them ("magick.exe" or "convert.exe") on the folder by just copying and renaming since they're both the same ".exe".

However, no matter how I fix the referred issue, it keeps stumbling on the **"'C:\Program' is not recognized as an internal or external command, operable program or batch file."** issue. 

It happens because there's a space in the 'C:\Program Files\...' path and the package should run it in the prompt as a double-quoted path so the prompt won't try and run 'C:\Program' as a command.

**Comment by popovs** [comment]
Some people have had some success using the `animation` library to point `gganimate` directly to `convert.exe`:

`library(animation)`
`gganimate(p,  interval=0.2, ani.options(convert = "C:/Program Files/ImageMagick-7.0.7-Q16/convert.exe"))`

Which for me results in:
`Error in savers[[saver]] : no such index at level 1`

Bummer this doesn't work on Windows.

**Comment by martinolmos** [comment]
Try with `ani.options(convert = "C:/Progra~1/ImageMagick-7.0.7-Q16/convert.exe")` instead of `ani.options(convert = "C:/Program Files/ImageMagick-7.0.7-Q16/convert.exe")`

**Comment by joshualeond** [comment]
@martinolmos That change got rid of @popovs `Error in savers[[saver]] : no such index at level 1` error for me. But I had to run the `ani.options()` outside of the `gganimate()` function call first. However, even though it appears to discover the right file paths now I then hit this error:

> convert.exe: unable to load module 'C:\Program Files\ImageMagick-7.0.7-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.

Which appears to be a problem discussed [here](https://www.imagemagick.org/discourse-server/viewtopic.php?t=32736):

> It seems that Windows no longer (or it never did?) loads referenced libraries from the directory of the executable. The `mod_png` dll is located in the modules/coders directory but it needs the `png` dll that is located in the same folder as the executable. I just pushed a patch with a workaround for this to our git repository.

I'm not sure if this is a one-off error or something all Windows users will run into.

**Comment by dkholo** [comment]
I am still getting an error after following all recommendations:
Executing: 
"C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0 -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png
    Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
an error occurred in the conversion... see Notes in ?im.convert
Error in file(file, "rb") : cannot open the connection
In addition: Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c "C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""' had status 1 
2: In cmd.fun(convert) :
  '"C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""' execution failed with error code 1
3: running command '"C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""' had status 127 
4: In file(file, "rb") :

**Comment by dkholo** [comment]
:(

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)

**Comment by yzhlinscau** [comment]
The new version gganimate, I can install, but running examples show error. codes and error message is as following. How to sovle this problem? Thanks a lot!

library(gapminder) # load data
head(gapminder)

p <- ggplot(gapminder, aes(x=gdpPercap, y=lifeExp, 
                           size=pop, color=continent,frame=year))+
               geom_point()+scale_x_log10()

animate(p)


> animate(p)
Error in seq.default(1, nframes_final, length.out = nframes) : 
  'to' must be of length 1
