### ISSUE TITLE
Can't find frame aesthetic with geom_density_2d

### ISSUE THREAD

**Issue by dgrtwo** [thomasp85/gganimate#56]
Example:

``` r
library(ggplot2)
library(gganimate)

p <- ggplot(mtcars, aes(mpg, wt, frame = cyl)) +
  stat_density_2d(h = c(10,10), col = "white")

gganimate(p)
#> Error in gganimate(p): No frame aesthetic found; cannot create animation
```

**Comment by gorkang** [comment]
As seen in a comment here: https://github.com/dgrtwo/gganimate/issues/13

Making cyl a factor solves it.

```
library(ggplot2)
library(gganimate)
library(dplyr)

p <- ggplot(mtcars %>% mutate(cyl = as.factor(cyl)), aes(mpg, wt, frame = cyl)) +
  stat_density_2d(h = c(10,10), col = "white")

gganimate(p)
```

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
