### ISSUE TITLE
gg_animate_save in README

### ISSUE THREAD

**Issue by ginolhac** [thomasp85/gganimate#6]
Thanks for a great and useful package!

In the README, the saving does not reflect the recent changes using an `gg_animate` object.

```
gg_animate(p)  %>% gg_animate_save("output.gif")
```

**Comment by dgrtwo** [comment]
The version in the README.Rmd works as well (it is a [shortcut](https://github.com/dgrtwo/gganimate/blob/master/R/gg_animate.R#L110) that calls the `gg_animate_save` function, to keep reverse compatibility and conciseness for a common use case).

**Comment by ginolhac** [comment]
Ah, sorry for the trouble. It does work. Anyway, wanted to thank you!
