### ISSUE TITLE
Error in file(file, "rb") : cannot open the connection

### ISSUE THREAD

**Issue by xiaotaichai** [thomasp85/gganimate#62]
I followed the tutorial and create the ggplot p. And when I run gganimate(p), it gave me this error.

**Comment by xiaotaichai** [comment]
Solved the issue by running **devtools::install_github("dgrtwo/gganimate")** and **devtools::install_github("yihui/animation")** together.

**Comment by Tani1989** [comment]
Thank you so much...I was stuck in this error from 2 days.
