### ISSUE TITLE
apply animations on sepcific geom only

### ISSUE THREAD

**Issue by xraynaud** [thomasp85/gganimate#85]
In the previous versions of gganimate, the frame argument allowed to apply animations to specific geom only. Is there a way to do a similar thing in the new version ? For example, with the following plot: 
    
    ggplot(data.frame(x=1:10,y=1:10),aes(x=x,y=y)) + geom_line() + geom_point() + transition_time(x)

is it possible to have only the geom_point() animated (so that I have points moving on the line) ? I have found a workaround by using another dataset that does not contains variable x in the geom_line   (e.g. geom_line(data.frame(x2=1:10,y=1:10),aes(x=x2,y=y))) but I don't find that really satisfactory.

Thanks

**Comment by thomasp85** [comment]
You're "workaround" is correct, and is precisely the same approach as used with faceting if you want a layer to appear in all facets
