### ISSUE TITLE
animate multiple plots

### ISSUE THREAD

**Issue by xraynaud** [thomasp85/gganimate#86]
One of the drawbacks of previous gganimate versions was that it didn't work with multiple plots produced by grid.arrange or plot_grid (or at least I never found how to do it). Is there/will there be a way to animate plots having insets or  panels produced with grid.arrange/plot_grid/patchwork ? I'm thinking about plots like this one https://upload.wikimedia.org/wikipedia/commons/3/3b/Circle_cos_sin.gif in which you have different panels that have to be animated together.

**Comment by thomasp85** [comment]
My plan is to provide gganimate support in patchwork eventually. A bit down the priority line though
