### ISSUE TITLE
view_follow keeps x-axis fixed while in transition

### ISSUE THREAD

**Issue by kanishkamisra** [thomasp85/gganimate#88]
Was writing an example for view_follow to show log transformation effects on data:

```r
library(tidyverse)
library(gapminder)
library(gganimate)

gapminder %>%
  filter(year == 2007) %>%
  mutate(log_gdp = log(gdpPercap)) %>%
  gather(gdpPercap, log_gdp, key = "gdp_scale", value = "value") %>%
  ggplot() +
  geom_density(aes(value)) +
  transition_states(gdp_scale, transition_length = 4, state_length = 1) +
  view_follow()
```
I get this: 
![gganimate_issue](https://user-images.githubusercontent.com/10777197/42413781-064428b6-81ed-11e8-81b9-53a3c28d6c5c.gif)

The x-axis remains constant while y changes appropriately (even though fixed_x is FALSE by default). Am I doing this wrong? Any ideas on how I can fix this?

**Comment by thomasp85** [comment]
It seems the density curve keeps the full range at all time so the view is doing the right thing. Try with a non-density example

**Comment by kanishkamisra** [comment]
Histogram also doesn't seem to work:

```r
library(tidyverse)
library(gapminder)
library(gganimate)

gapminder %>%
  filter(year == 2007) %>%
  mutate(log_gdp = log(gdpPercap)) %>%
  gather(gdpPercap, log_gdp, key = "gdp_scale", value = "value") %>%
  ggplot() +
  geom_histogram(aes(value)) +
  transition_states(gdp_scale, transition_length = 3, state_length = 2) +
  view_follow()
```
![preview_histogram](https://user-images.githubusercontent.com/10777197/42413986-bf9c5d48-81f1-11e8-89a5-572cc1716c8f.gif)

However, this works (like you said):

```r
library(tidyverse)
library(gapminder)
library(gganimate)

gapminder %>%
  filter(year == 2007) %>%
  mutate(log_gdp = log(gdpPercap)) %>%
  gather(gdpPercap, log_gdp, key = "gdp_scale", value = "value") %>%
  ggplot(aes(value, lifeExp)) +
  geom_point() +
  transition_states(gdp_scale, transition_length = 2, state_length = 1) +
  view_follow()
```

![preview2](https://user-images.githubusercontent.com/10777197/42413978-7c88d68a-81f1-11e8-823b-e129bcb918c1.gif)

**Comment by thomasp85** [comment]
I think the "problem" is that the different binning and density transformations keep data even if it is zero, so the view can't zoom in more...

I'll keep it open as it would be nice to solve but it is not obvious how it should be done

**Comment by thomasp85** [comment]
Closing - don't think this should be solved in gganimate

**Comment by shaggycamel** [comment]
Anyone know if this has been fixed, or an alternative found?
