### ISSUE TITLE
Can't run example on R 3.5

### ISSUE THREAD

**Issue by FilipeamTeixeira** [thomasp85/gganimate#91]
For some reason I can't even run the example in the ReadMe file. It renders but then nothing happens.
Nothing appears on the viewer or on the plots section.

**Comment by thomasp85** [comment]
There has been some problems in the print method - can I get you to try again?

**Comment by rbenel** [comment]
Hi, 
I am having the same issue on 3.5.1 :(

**Comment by FilipeamTeixeira** [comment]
@thomasp85 shall I update it again to the latest dev version?

**Comment by thomasp85** [comment]
Yes - it should be fixed

**Comment by FilipeamTeixeira** [comment]
Confirmed that it works. Thanks and sorry for the late reply.
