### ISSUE TITLE
Help needed with simple animation

### ISSUE THREAD

**Issue by neuwirthe** [thomasp85/gganimate#94]
I want to create a simple animation, `geom_line`
and using only rows 1:n for frame n,
so the points are "uncovered" incrementally. 
Can I get example code for this?

**Comment by ginolhac** [comment]
I don't really get what you want, but I think it will better to start with a small working example and then describe what you want.
 
using the example from https://github.com/thomasp85/gganimate/issues/85, see the following reprex


``` r
library(gganimate)
#> Loading required package: ggplot2
ggplot(dat = data.frame(x=1:10,y=1:10), aes(x=x,y=y)) +
  geom_point() +
  geom_line(data = data.frame(x2 = 1:10, y = 1:10),
            aes(x = x2, y = y, group = 1)) +
  transition_time(x)
animate(last_plot(), nframes = 50)
```

![](https://i.imgur.com/1urXwyO.gif)

Created on 2018-07-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ginolhac** [comment]
another small example when dots are "uncovered" using the trick of having dots excluded from animation by removing the `group` column.

The `exit_manual()` example comes from Thomas's keynote at useR2018 (https://www.data-imaginist.com/slides/user2018/assets/player/keynotedhtmlplayer#85)

``` r
library(gganimate)
#> Loading required package: ggplot2
tibble::tribble(
  ~i,  ~ x, ~ y,  ~ group, 
  1,   1,   1,    "A",      
  2,   2,   1,    "A",      
  3,   3,   1,    "A",
  1,   1,   1,    "B",      
  2,   2,   1,    "B",      
  1,   1,   1,    "C",
  1.5, 0,   1,    "D",
  ) -> tib
ggplot(tib) +
  geom_point(data = function(x) x[, 1:3], aes(i, y), size = 4, colour = "red") +
  geom_segment(aes(x = 0, xend = x  + 0.2, y = y, yend = y), size = 6) +
  transition_states(group, transition_length = 1, state_length = 1) +
  enter_grow() +
  exit_manual(function(x) {
    x$x <- x$x - 3
    x$xend <- x$xend - 3
    x
  }) +
  theme_void() +
  labs(title = '{closest_state}')
#> Warning in min(best[best != 0]): no non-missing arguments to min; returning
#> Inf

#> Warning in min(best[best != 0]): no non-missing arguments to min; returning
#> Inf
```

![](https://i.imgur.com/5GZVry6.gif)

Created on 2018-07-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
This will eventually be supported with `transition_reveal()`, which is on the roadmap

**Comment by neuwirthe** [comment]
Here is a minimalistic example of what I would like to do


```
library(tidyverse)
mydf <- data_frame(x=0:100,y=(0:100)^2)
plot_frame <- function(frame_no){
  xmax <- mydf %$% x %>% max()
  ymax <- mydf %$% y %>% max()
  xmin <- mydf %$% x %>% min()
  ymin <- mydf %$% y %>% min()
  mydf %>% filter(x <= frame_no) %>% 
    ggplot(aes(x=x,y=y)) + geom_line() +
    scale_x_continuous(limits=c(xmin,xmax)) +
    scale_y_continuous(limits=c(ymin,ymax)) 
}
plot_frame(90)

# this is what I would like to have as animation
# for (i in 80:100) plot_frame(i)
```

**Comment by ginolhac** [comment]
then, the new `transition_filter()` is very timely!

``` r
library(gganimate)
mydf <- data.frame(x = 0:100, y = (0:100)^2)
ggplot(mydf, aes(x = x, y = y)) +
  geom_line() +
  transition_filter(transition_length = 1, filter_length = 0.2, wrap = TRUE, keep = FALSE, 
    x < 80, x < 100) +
  labs(title = "{closest_expression} and {closest_filter}")
anim_save("line_square.gif")
```

![line_square](https://user-images.githubusercontent.com/710181/43077265-4e97da9e-8e87-11e8-8bb1-77d8a69b12fb.gif)

Of note, using `reprex` failed due to the new gifski though. Even if it is super fast, the upload to imgur failed.

**Comment by thomasp85** [comment]
Thanks for the reprex note - I’ll look into that
