### ISSUE TITLE
Changing size/resolution of output frames

### ISSUE THREAD

**Issue by mdmadhu** [thomasp85/gganimate#96]
I can't believe I am asking this, but here goes: how can one control the size and resolution of output frames. Everything I produce is 480x480 pixels. The earlier answers (of setting `animation::ani.options(ani.width = 1000, ani.height = 800, ani.res = 96)`) don't seem to work with the new API, which seems to use magick to create frames and render the GIF. I have clearly missed something that must be obvious, so If anyone has pointers, I'd appreciate very much. Thank you.

**Comment by thomasp85** [comment]
Look into `animate()`, which is the function that gets called automatically when you print a gganim object. It allows you to set the parameters of the device

**Comment by mdmadhu** [comment]
Thanks!

**Comment by RPanczak** [comment]
Have you managed to resolve the issue of resolution / dpi? `height` and `width` are easy to set up with `animate()` like @thomasp85 pointed out. How about image quality?

**Comment by tjebo** [comment]
@RPanczak see this SO post https://stackoverflow.com/a/61763614/7941188 

@thomasp85 I feel the animate()  documentation could include an example how to fully control dimension by unit and resolution. If you agree, I am happy to make a pull request.

**Comment by thomasp85** [comment]
@tjebo that would be great
