### ISSUE TITLE
Should shadow_mark() tween between line graph frames?

### ISSUE THREAD

**Issue by DavisVaughan** [thomasp85/gganimate#97]
I think the title is correct in what I'm asking for, but I'm not sure. 

Check out the difference in what I am doing below. The first using `shadow_mark()` results in a pretty rough looking plot with lots of gaps. I think it's doing what is intended, and I'm still getting used to the API, but I was going for the result in the second picture. Am I just doing something wrong? 

Eventually going to see if I can recreate some of Len Kiefer's charts using `gganimate` rather than just `animation` https://twitter.com/lenkiefer/status/1018183403328475137

``` r
library(gganimate)
library(dplyr)
library(tibbletime)
data("FB")

FB %>%
  ggplot(aes(x = date, y = close)) +
  geom_line() +
  transition_time(date) +
  shadow_mark()
```

![](https://i.imgur.com/cBpEqcw.gif)

``` r

frames <- seq_len(NROW(FB))

FB_framed <- purrr::map_dfr(seq_len(NROW(FB)), function(x) {
  FB_slice <- FB[which(frames <= x), , drop = FALSE]
  FB_slice$.frame <- x
  FB_slice
})

FB_framed %>%
  ggplot(aes(x = date, y = close)) +
  geom_line() +
  transition_manual(.frame)
#> geom_path: Each group consists of only one observation. Do you need to
#> adjust the group aesthetic?
#> geom_path: Each group consists of only one observation. Do you need to
#> adjust the group aesthetic?
```

![](https://i.imgur.com/GSUMMF4.gif)

**Comment by thomasp85** [comment]
The shadow is doing what it should, but this type of animation is best made with the yet-to-be-implemented `transition_reveal()`

**Comment by DavisVaughan** [comment]
Ah, makes sense. Good name too, I can easily imagine what it should do 👍
