### ISSUE TITLE
lp.assign error with sf and transition_states

### ISSUE THREAD

**Issue by alistaire47** [thomasp85/gganimate#98]
Thanks for your work! The new interface is excellent, and looks like it's only going to improve from here.

My issue: I've run into a cryptic error when trying to animate sf maps with `transition_states`:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, proj.4 4.9.3
library(tidyverse)
library(gganimate)

nc = st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source `/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs

# make inverse ratios for pair of variables
nc_ratio <- nc %>% 
  gather(year, bir, BIR74, BIR79) %>% 
  group_by(NAME) %>% 
  mutate(ratio = bir / rev(bir)) %>% 
  ungroup()

# facet_wrap works fine...
ggplot(nc_ratio, aes(fill = ratio)) + geom_sf() + facet_wrap(~year, nrow = 2)
```
![](https://i.imgur.com/9jNpKXz.png)

``` r
# ...but transition_states errors out
ggplot(nc_ratio, aes(fill = ratio)) + geom_sf() + transition_states(year, 1, 3)
#> Error in lp.assign(distance): NA/NaN/Inf in foreign function call (arg 4)
```
I can do the tweening with `tweenr::tween_states` and then use `transition_manual`, and it works fine (though the resulting object needs to be reclassed and wrapping takes some work), so it would seem this should be possible in the new interface.

I've replicated this on multiple map (multipolygon) datasets, but it does not seem to arise when point data is treated in precisely the same manner:
``` r
mtcars %>% 
  mutate(geometry = map2(wt, drat, ~st_point(c(...))) %>% st_sfc()) %>% 
  st_sf() %>% gather(i, x, wt, drat) %>% 
  ggplot(aes(color = x)) + 
  geom_sf() + 
  scale_color_distiller(type = 'div', palette = 2) + 
  transition_states(i, 1, 1)
```
![](https://i.imgur.com/SfbqlEU.gif)

I really have no idea what's causing the error; it appears pretty deep-rooted, beyond my debugging skills.

**Comment by thomasp85** [comment]
It’s an error from transformr when it tries to match shapes for creating the smoothest transition. Assuming you haven’t tried already, can I get you to update transformr from GitHub? I remember touching that code not long ago

**Comment by alistaire47** [comment]
The reason makes sense. When I tried to install, devools tells me that the SHA hasn't changed since my last install, though, so the error is occurring with the current version.

**Comment by thomasp85** [comment]
Ok - thanks for checking it out. I’ll look into it

**Comment by thomasp85** [comment]
Turns out I hadn't pushed the fix - can I get you to reinstall transformr and check again

**Comment by alistaire47** [comment]
Yep, that did it, thanks! The result had some artifacts, but then I updated to the gifski backend and those disappeared, so I'm happy. Closing.
